# **Start Section:**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os
os.environ["PIP_CONSTRAINT"] = "/tmp/numpy_constraint.txt"
!echo "numpy==1.26.4" > /tmp/numpy_constraint.txt

!pip uninstall -y torch torchaudio torchvision \
    torchao torchcodec torchdata torchtune torchsummary -q 2>/dev/null

!pip uninstall -y tensorflow tensorflow-text tensorflow-hub tf-keras \
    tensorflow_decision_forests tensorflow-probability \
    tensorflow-datasets tensorflow-metadata -q 2>/dev/null

!pip uninstall -y numpy scikit-learn shap xgboost lightgbm dask \
    seaborn plotly openpyxl Cython catboost interpret lime -q 2>/dev/null

!pip install numpy==1.26.4 -q
!pip install scikit-learn==1.6.1 -q
!pip install torch==2.9.0 -q

!pip install lightgbm==4.6.0 -q
!pip install xgboost==3.1.2 -q
!pip install catboost==1.2.8 -q
!pip install gpboost==1.6.1 -q
!pip install ngboost==0.5.8 -q
!pip install pgbm==2.2.0 -q
!pip install pytorch-tabnet2==4.5.3 -q

!pip install bayesian-optimization==3.2.0 -q
!pip install optuna==4.6.0 -q
!pip install optunahub==0.4.0 -q
!pip install cmaes==0.12.0 -q

!pip install shap==0.44.0 -q
!pip install lime==0.2.0.1 -q
!pip install interpret==0.7.4 -q

!pip install mapie==0.6.0 -q
!pip install puncc==0.8.0 -q
!pip install skorch==1.3.1 -q
!pip install properscoring==0.1 -q

!pip install dask[dataframe]==2025.12.0 -q
!pip install cython==3.0.12 -q
!pip install seaborn==0.13.2 -q
!pip install plotly==5.24.1 -q
!pip install kaleido==1.2.0 -q
!pip install openpyxl==3.1.5 -q
!pip install XlsxWriter==3.2.9 -q
!pip install cp==2020.12.3 -q

!pip install numpy==1.26.4 --force-reinstall --no-deps -q

os._exit(0)

Found existing installation: scikit-learn 1.6.1
Uninstalling scikit-learn-1.6.1:
  Successfully uninstalled scikit-learn-1.6.1
Collecting scikit-learn==1.5.2
  Downloading scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.5.2) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.5.2) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.5.2) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.5.2) (3.6.0)
Downloading scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.9/12.9 MB 82.8 MB/s eta 0:00:00
Installing collected packages: scikit-learn
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
hdbscan 0.8.41 requires scikit-learn>=1.6, but you have scikit-learn 1.5.2 which is incompatible.
umap-learn 0.5.11 requires scikit-learn>=1.6, but you have scikit-learn 1.5.2 which is incompatible.
Successfully installed scikit-learn-1.5.2
Collecting bayesian-optimization==3.2.0
  Downloading bayesian_optimization-3.2.0-py3-none-any.whl.metadata (11 kB)
Collecting colorama>=0.4.6 (from bayesian-optimization==3.2.0)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: numpy>=1.25 in /usr/local/lib/python3.12/dist-packages (from bayesian-optimization==3.2.0) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from bayesian-optimization==3.2.0) (26.0)
Requirement already satisfied: scikit-learn>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from bayesian-optimization==3.2.0) (1.5.2)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from bayesian-optimization==3.2.0) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0.0->bayesian-optimization==3.2.0) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0.0->bayesian-optimization==3.2.0) (3.6.0)
Downloading bayesian_optimization-3.2.0-py3-none-any.whl (37 kB)
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Installing collected packages: colorama, bayesian-optimization
Successfully installed bayesian-optimization-3.2.0 colorama-0.4.6
Collecting optuna==4.6.0
  Downloading optuna-4.6.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna==4.6.0) (1.18.4)
Collecting colorlog (from optuna==4.6.0)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna==4.6.0) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna==4.6.0) (26.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna==4.6.0) (2.0.46)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna==4.6.0) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna==4.6.0) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna==4.6.0) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna==4.6.0) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna==4.6.0) (3.3.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna==4.6.0) (3.0.3)
Downloading optuna-4.6.0-py3-none-any.whl (404 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 404.7/404.7 kB 16.2 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.6.0
Collecting gpboost==1.6.1
  Downloading gpboost-1.6.1-py3-none-manylinux1_x86_64.whl.metadata (7.9 kB)
Requirement already satisfied: wheel in /usr/local/lib/python3.12/dist-packages (from gpboost==1.6.1) (0.46.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from gpboost==1.6.1) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from gpboost==1.6.1) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from gpboost==1.6.1) (1.16.3)
Requirement already satisfied: scikit-learn!=0.22.0 in /usr/local/lib/python3.12/dist-packages (from gpboost==1.6.1) (1.5.2)
Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (from gpboost==1.6.1) (4.6.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn!=0.22.0->gpboost==1.6.1) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn!=0.22.0->gpboost==1.6.1) (3.6.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna->gpboost==1.6.1) (1.18.4)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna->gpboost==1.6.1) (6.10.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna->gpboost==1.6.1) (26.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna->gpboost==1.6.1) (2.0.46)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna->gpboost==1.6.1) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna->gpboost==1.6.1) (6.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->gpboost==1.6.1) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->gpboost==1.6.1) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->gpboost==1.6.1) (2025.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna->gpboost==1.6.1) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna->gpboost==1.6.1) (4.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->gpboost==1.6.1) (1.17.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna->gpboost==1.6.1) (3.3.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna->gpboost==1.6.1) (3.0.3)
Downloading gpboost-1.6.1-py3-none-manylinux1_x86_64.whl (5.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 12.4 MB/s eta 0:00:00
Installing collected packages: gpboost
Successfully installed gpboost-1.6.1
Requirement already satisfied: shap==0.50.0 in /usr/local/lib/python3.12/dist-packages (0.50.0)
Requirement already satisfied: numpy>=2 in /usr/local/lib/python3.12/dist-packages (from shap==0.50.0) (2.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from shap==0.50.0) (1.16.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from shap==0.50.0) (1.5.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from shap==0.50.0) (2.2.2)
Requirement already satisfied: tqdm>=4.27.0 in /usr/local/lib/python3.12/dist-packages (from shap==0.50.0) (4.67.3)
Requirement already satisfied: packaging>20.9 in /usr/local/lib/python3.12/dist-packages (from shap==0.50.0) (26.0)
Requirement already satisfied: slicer==0.0.8 in /usr/local/lib/python3.12/dist-packages (from shap==0.50.0) (0.0.8)
Requirement already satisfied: numba>=0.54 in /usr/local/lib/python3.12/dist-packages (from shap==0.50.0) (0.60.0)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from shap==0.50.0) (3.1.2)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from shap==0.50.0) (4.15.0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba>=0.54->shap==0.50.0) (0.43.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->shap==0.50.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->shap==0.50.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->shap==0.50.0) (2025.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->shap==0.50.0) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->shap==0.50.0) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->shap==0.50.0) (1.17.0)
Collecting ngboost==0.5.8
  Downloading ngboost-0.5.8-py3-none-any.whl.metadata (4.2 kB)
Collecting lifelines>=0.25 (from ngboost==0.5.8)
  Downloading lifelines-0.30.1-py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: numpy>=1.21.2 in /usr/local/lib/python3.12/dist-packages (from ngboost==0.5.8) (2.0.2)
Collecting scikit-learn<2.0,>=1.6 (from ngboost==0.5.8)
  Downloading scikit_learn-1.8.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (11 kB)
Requirement already satisfied: scipy>=1.7.2 in /usr/local/lib/python3.12/dist-packages (from ngboost==0.5.8) (1.16.3)
Requirement already satisfied: tqdm>=4.3 in /usr/local/lib/python3.12/dist-packages (from ngboost==0.5.8) (4.67.3)
Requirement already satisfied: pandas<3.0,>=2.1 in /usr/local/lib/python3.12/dist-packages (from lifelines>=0.25->ngboost==0.5.8) (2.2.2)
Requirement already satisfied: matplotlib>=3.0 in /usr/local/lib/python3.12/dist-packages (from lifelines>=0.25->ngboost==0.5.8) (3.10.0)
Requirement already satisfied: autograd>=1.5 in /usr/local/lib/python3.12/dist-packages (from lifelines>=0.25->ngboost==0.5.8) (1.8.0)
Collecting autograd-gamma>=0.3 (from lifelines>=0.25->ngboost==0.5.8)
  Downloading autograd-gamma-0.5.0.tar.gz (4.0 kB)
  Preparing metadata (setup.py) ... done
Collecting formulaic>=0.2.2 (from lifelines>=0.25->ngboost==0.5.8)
  Downloading formulaic-1.2.1-py3-none-any.whl.metadata (7.0 kB)
Requirement already satisfied: joblib>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2.0,>=1.6->ngboost==0.5.8) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2.0,>=1.6->ngboost==0.5.8) (3.6.0)
Collecting interface-meta>=1.2.0 (from formulaic>=0.2.2->lifelines>=0.25->ngboost==0.5.8)
  Downloading interface_meta-1.3.0-py3-none-any.whl.metadata (6.7 kB)
Requirement already satisfied: narwhals>=1.17 in /usr/local/lib/python3.12/dist-packages (from formulaic>=0.2.2->lifelines>=0.25->ngboost==0.5.8) (2.16.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.12/dist-packages (from formulaic>=0.2.2->lifelines>=0.25->ngboost==0.5.8) (4.15.0)
Requirement already satisfied: wrapt>=1.0 in /usr/local/lib/python3.12/dist-packages (from formulaic>=0.2.2->lifelines>=0.25->ngboost==0.5.8) (2.1.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines>=0.25->ngboost==0.5.8) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines>=0.25->ngboost==0.5.8) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines>=0.25->ngboost==0.5.8) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines>=0.25->ngboost==0.5.8) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines>=0.25->ngboost==0.5.8) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines>=0.25->ngboost==0.5.8) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines>=0.25->ngboost==0.5.8) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0->lifelines>=0.25->ngboost==0.5.8) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=2.1->lifelines>=0.25->ngboost==0.5.8) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0,>=2.1->lifelines>=0.25->ngboost==0.5.8) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.0->lifelines>=0.25->ngboost==0.5.8) (1.17.0)
Downloading ngboost-0.5.8-py3-none-any.whl (36 kB)
Downloading lifelines-0.30.1-py3-none-any.whl (350 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 350.0/350.0 kB 16.8 MB/s eta 0:00:00
Downloading scikit_learn-1.8.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (8.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 113.4 MB/s eta 0:00:00
Downloading formulaic-1.2.1-py3-none-any.whl (117 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.3/117.3 kB 14.4 MB/s eta 0:00:00
Downloading interface_meta-1.3.0-py3-none-any.whl (14 kB)
Building wheels for collected packages: autograd-gamma
  Building wheel for autograd-gamma (setup.py) ... done
  Created wheel for autograd-gamma: filename=autograd_gamma-0.5.0-py3-none-any.whl size=4030 sha256=814144a05a2931e7efe93a8316daf45f42ed5c0b237d054c56d4dde07b5cc336
  Stored in directory: /root/.cache/pip/wheels/50/37/21/0a719b9d89c635e89ff24bd93b862882ad675279552013b2fb
Successfully built autograd-gamma
Installing collected packages: interface-meta, scikit-learn, autograd-gamma, formulaic, lifelines, ngboost
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.5.2
    Uninstalling scikit-learn-1.5.2:
      Successfully uninstalled scikit-learn-1.5.2
Successfully installed autograd-gamma-0.5.0 formulaic-1.2.1 interface-meta-1.3.0 lifelines-0.30.1 ngboost-0.5.8 scikit-learn-1.8.0
Collecting dask==2025.12.0 (from dask[dataframe]==2025.12.0)
  Downloading dask-2025.12.0-py3-none-any.whl.metadata (3.8 kB)
Requirement already satisfied: click>=8.1 in /usr/local/lib/python3.12/dist-packages (from dask==2025.12.0->dask[dataframe]==2025.12.0) (8.3.1)
Requirement already satisfied: cloudpickle>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from dask==2025.12.0->dask[dataframe]==2025.12.0) (3.1.2)
Requirement already satisfied: fsspec>=2021.09.0 in /usr/local/lib/python3.12/dist-packages (from dask==2025.12.0->dask[dataframe]==2025.12.0) (2025.3.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from dask==2025.12.0->dask[dataframe]==2025.12.0) (26.0)
Requirement already satisfied: partd>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from dask==2025.12.0->dask[dataframe]==2025.12.0) (1.4.2)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.12/dist-packages (from dask==2025.12.0->dask[dataframe]==2025.12.0) (6.0.3)
Requirement already satisfied: toolz>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from dask==2025.12.0->dask[dataframe]==2025.12.0) (0.12.1)
Requirement already satisfied: pandas>=2.0 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]==2025.12.0) (2.2.2)
Requirement already satisfied: pyarrow>=14.0.1 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]==2025.12.0) (18.1.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0->dask[dataframe]==2025.12.0) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0->dask[dataframe]==2025.12.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0->dask[dataframe]==2025.12.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0->dask[dataframe]==2025.12.0) (2025.3)
Requirement already satisfied: locket in /usr/local/lib/python3.12/dist-packages (from partd>=1.4.0->dask==2025.12.0->dask[dataframe]==2025.12.0) (1.0.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.0->dask[dataframe]==2025.12.0) (1.17.0)
Downloading dask-2025.12.0-py3-none-any.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 30.4 MB/s eta 0:00:00
Installing collected packages: dask
  Attempting uninstall: dask
    Found existing installation: dask 2025.9.1
    Uninstalling dask-2025.9.1:
      Successfully uninstalled dask-2025.9.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
distributed 2025.9.1 requires dask==2025.9.1, but you have dask 2025.12.0 which is incompatible.
rapids-dask-dependency 25.10.0 requires dask==2025.9.1, but you have dask 2025.12.0 which is incompatible.
Successfully installed dask-2025.12.0
ERROR: Could not find a version that satisfies the requirement torch==2.9.0+cpu (from versions: 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 2.5.0, 2.5.1, 2.6.0, 2.7.0, 2.7.1, 2.8.0, 2.9.0, 2.9.1, 2.10.0)
ERROR: No matching distribution found for torch==2.9.0+cpu
Requirement already satisfied: seaborn==0.13.2 in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /usr/local/lib/python3.12/dist-packages (from seaborn==0.13.2) (2.0.2)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.12/dist-packages (from seaborn==0.13.2) (2.2.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /usr/local/lib/python3.12/dist-packages (from seaborn==0.13.2) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn==0.13.2) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn==0.13.2) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn==0.13.2) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn==0.13.2) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn==0.13.2) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn==0.13.2) (11.3.0)

Collecting catboost==1.2.8
  Downloading catboost-1.2.8-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost==1.2.8) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost==1.2.8) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost==1.2.8) (1.26.4)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost==1.2.8) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost==1.2.8) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost==1.2.8) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost==1.2.8) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost==1.2.8) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost==1.2.8) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost==1.2.8) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost==1.2.8) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost==1.2.8) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost==1.2.8) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost==1.2.8) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost==1.2.8) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost==1.2.8) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost==1.2.8) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost==1.2.8) (9.1.4)
Downloading catboost-1.2.8-cp312-cp312-manylinux2014_x86_64.whl (99.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.2/99.2 MB 8.6 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.8
Collecting pytorch-tabnet2==4.5.3
  Downloading pytorch_tabnet2-4.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting activations-plus>=0.1.1 (from pytorch-tabnet2==4.5.3)
  Downloading activations_plus-0.1.1-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from pytorch-tabnet2==4.5.3) (1.26.4)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from pytorch-tabnet2==4.5.3) (1.6.1)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from pytorch-tabnet2==4.5.3) (2.10.0+cu128)
Collecting torcheval (from pytorch-tabnet2==4.5.3)
  Downloading torcheval-0.0.7-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->pytorch-tabnet2==4.5.3) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->pytorch-tabnet2==4.5.3) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->pytorch-tabnet2==4.5.3) (3.6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (3.24.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch->pytorch-tabnet2==4.5.3) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch->pytorch-tabnet2==4.5.3) (1.3.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch->pytorch-tabnet2==4.5.3) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch->pytorch-tabnet2==4.5.3) (3.0.3)
Downloading pytorch_tabnet2-4.5.3-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.9/70.9 kB 4.5 MB/s eta 0:00:00
Downloading activations_plus-0.1.1-py3-none-any.whl (15 kB)
Downloading torcheval-0.0.7-py3-none-any.whl (179 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.2/179.2 kB 14.4 MB/s eta 0:00:00
Installing collected packages: torcheval, activations-plus, pytorch-tabnet2
Successfully installed activations-plus-0.1.1 pytorch-tabnet2-4.5.3 torcheval-0.0.7

# **Imports**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import randint
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.base import BaseEstimator, RegressorMixin
from sklearn.svm import SVR
import ngboost
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor
from gpboost import GPBoostRegressor
from ngboost import NGBRegressor
import optuna
import optunahub
from sklearn.experimental import enable_halving_search_cv
from sklearn.model_selection import HalvingGridSearchCV
from interpret import show
from interpret.blackbox import LimeTabular, ShapKernel
from optuna.samplers import RandomSampler
import random
import time
from ngboost.distns import Normal
from ngboost.scores import LogScore
from scipy.stats import norm
from optuna.samplers import BaseSampler
from optuna.samplers import GridSampler
from optuna.samplers import TPESampler
from optuna.samplers import PartialFixedSampler
from optuna.samplers import CmaEsSampler
from optuna.samplers import QMCSampler
from optuna.samplers import NSGAIIISampler
from optuna.samplers import NSGAIISampler
from optuna.samplers import BruteForceSampler
from optuna.samplers import GPSampler
from interpret import set_visualize_provider
from interpret.provider import InlineProvider
from interpret.glassbox import ExplainableBoostingRegressor
from interpret import show
import plotly.express as px
from io import BytesIO
from openpyxl import Workbook, load_workbook
import os
import properscoring as ps
import io
from openpyxl.drawing.image import Image as openpyxlImage
import warnings
import xlsxwriter
from openpyxl.drawing.image import Image
from pgbm.sklearn import HistGradientBoostingRegressor
import torch
from pgbm.torch import PGBM
import plotly.graph_objects as go
warnings.filterwarnings('ignore')
import pickle
import json
from mapie.subsample import Subsample
from mapie.regression import MapieRegressor
from deel.puncc.metrics import regression_sharpness, regression_mean_coverage
from deel.puncc.api.prediction import BasePredictor, DualPredictor
from deel.puncc.regression import SplitCP, CVPlus, CQR
from deel.puncc.plotting import plot_prediction_intervals
from sklearn.model_selection import train_test_split
from typing_extensions import TypedDict
from typing import Union
from mapie.metrics import regression_coverage_score
from sklearn.model_selection import KFold
from PIL import Image as PImage
from openpyxl.utils.dataframe import dataframe_to_rows
from scipy.stats import genpareto
from pytorch_tabnet import TabNetRegressor
import torch.nn as nn
import warnings
import io
import time
import numpy as np
import pandas as pd
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt
from openpyxl import load_workbook
from openpyxl.drawing.image import Image
from openpyxl.utils.dataframe import dataframe_to_rows

In [2]:
# Go to find & replace button and replace (Data_folder) with your folder name. Rename your train and test dataset as train.csv and test.csv.
# Modify the names of the feature in the below cell.
# Replace (Y_Label) with actual data label name.

In [3]:
feature_names = ['Qt', 'Qt-1', 'St-1']

In [4]:
train_data_path = "./drive/MyDrive/Data_folder/Data/train.csv"
test_data_path = "./drive/MyDrive/Data_folder/Data/test.csv"
train_data = pd.read_csv(train_data_path)
test_data = pd.read_csv(test_data_path)
print("Training data loaded successfully.")
print("Test data loaded successfully.")

Training data loaded successfully.
Test data loaded successfully.

In [5]:
print("\nShape of training data:", train_data.shape)
print("First 5 rows of training data:\n", train_data.head(5))
print("\nShape of test data:", test_data.shape)
print("First 5 rows of test data:\n", test_data.head(5))

Shape of training data: (1095, 4)
First 5 rows of training data:
       Qt   Qt-1    St-1      St
0  12.40  11.80  5930.0  5630.0
1   7.93  12.40  5630.0  1960.0
2   5.66   7.93  1960.0   491.0
3   5.04   5.66   491.0   692.0
4   4.84   5.04   692.0   452.0

Shape of test data: (365, 4)
First 5 rows of test data:
      Qt  Qt-1  St-1    St
0  5.27  5.49  45.0  44.0
1  5.13  5.27  44.0  29.0
2  4.84  5.13  29.0  23.0
3  5.04  4.84  23.0  26.0
4  5.21  5.04  26.0  30.0

In [6]:
X_train = train_data.iloc[:, :-1]
y_train = train_data.iloc[:, -1]
X_test = test_data.iloc[:, :-1]
y_test = test_data.iloc[:, -1]
x_test= X_test
print("\nShape of X_train:", X_train.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_test:", y_test.shape)

Shape of X_train: (1095, 3)
Shape of y_train: (1095,)
Shape of X_test: (365, 3)
Shape of y_test: (365,)

In [7]:
# Apply z-score normalization
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Print the first five rows of the normalized data
print("\nFirst five rows of normalized X_train:")
print(X_train[:5])

print("\nFirst five rows of normalized X_test:")
print(X_test[:5])

First five rows of normalized X_train:
[[-0.13088871 -0.15525695  1.01508124]
 [-0.31063021 -0.131129    0.95334642]
 [-0.40190834 -0.31088224  0.19812377]
 [-0.42683893 -0.40216633 -0.10417107]
 [-0.43488105 -0.42709855 -0.06280874]]

First five rows of normalized X_test:
[[-0.41759048 -0.40900259 -0.19595018]
 [-0.42321997 -0.4178495  -0.19615596]
 [-0.43488105 -0.42347936 -0.1992427 ]
 [-0.42683893 -0.4351412  -0.2004774 ]
 [-0.42000312 -0.42709855 -0.19986005]]

# **Functions:**

In [8]:
def get_best_model_params(results, model_name):
    # Map model names to dictionary keys, assuming keys are strings like 'XGBoost' and not objects
    model_keys = {
        'LightGBM': 'LightGBM',
        'XGBoost': 'XGBoost',
        'GPBoost': 'GPBoost',
        'NGBoost': 'NGBoost',
        'GradientBoosting': 'Gradient Boosting',
        'HGBR' : 'HistGradientBoosting',
        'CatBoost' : 'CatBoost',
        'TabNet' : 'TabNet',
        'PGBM' : 'PGBM'
    }

    # Ensure the requested model name is valid
    if model_name not in model_keys:
        raise ValueError(f"Model name '{model_name}' is not recognized. Available models are: {list(model_keys.keys())}")

    # Filter out entries for the specified model
    model_entries = {key: value for key, value in results.items() if key[0] == model_keys[model_name]}

    # Find the entry with the best (lowest) 'best_score'
    best_entry_key, best_entry_value = min(model_entries.items(), key=lambda item: item[1]['best_score'])

    # Return the best hyperparameters
    return best_entry_value['best_params']

In [9]:
class validate:
    @staticmethod
    def coverage(int_pred, y_test):
        return {strat_name: np.mean((y_test.to_numpy() >= int_pred[strat_name][:, 0]) & (y_test.to_numpy() <= int_pred[strat_name][:, 1])) for strat_name in int_pred}
    @staticmethod
    def width(int_pred): # Corrected: Removed y_test argument as it's not defined and not used
        return {strat_name: np.mean(int_pred[strat_name][:, 1] - int_pred[strat_name][:, 0]) for strat_name in int_pred}
    @staticmethod
    def rmse(y_pred, y_test):
        return {strat_name: np.sqrt(mean_squared_error(y_test, y_pred[strat_name])) for strat_name in y_pred}
    @staticmethod
    def cwc(int_pred, y_test, miscoverage):
        widths = validate.width(int_pred)
        coverages = validate.coverage(int_pred, y_test)
        return {strat_name: widths[strat_name] * (1 + (coverages[strat_name] < (1 - miscoverage)) * (1 - coverages[strat_name])) for strat_name in int_pred}

    @staticmethod
    def cond_coverage(int_pred, y_test, num_bins=10):
        cond_coverages = {}
        for strat_name in int_pred:
            widths = int_pred[strat_name][:, 1] - int_pred[strat_name][:, 0]
            bin_edges = np.histogram_bin_edges(widths, bins=num_bins)
            digitized_widths = np.digitize(widths, bin_edges)
            strategy_cond_coverage = []
            for bin_num in range(1, num_bins + 1):
                indices_in_bin = np.where(digitized_widths == bin_num)[0]
                if len(indices_in_bin) > 0:
                    bin_coverage = np.mean((y_test.to_numpy()[indices_in_bin] >= int_pred[strat_name][indices_in_bin, 0]) & (y_test.to_numpy()[indices_in_bin] <= int_pred[strat_name][indices_in_bin, 1]))
                    strategy_cond_coverage.append(bin_coverage)
                else:
                    strategy_cond_coverage.append(np.nan) # or handle empty bins as needed
            cond_coverages[strat_name] = strategy_cond_coverage
        return cond_coverages


class visualize:
    @staticmethod
    def coverage(int_pred, y_test):
        return {strat_name: np.mean((y_test.to_numpy() >= int_pred[strat_name][:, 0]) & (y_test.to_numpy() <= int_pred[strat_name][:, 1])) for strat_name in int_pred}
    @staticmethod
    def width(int_pred):
        return {strat_name: np.mean(int_pred[strat_name][:, 1] - int_pred[strat_name][:, 0]) for strat_name in int_pred}
    @staticmethod
    def rmse(y_pred, y_test):
        return {strat_name: np.sqrt(mean_squared_error(y_test, y_pred[strat_name])) for strat_name in y_pred}
    @staticmethod
    def cwc(int_pred, y_test, miscoverage):
        widths = visualize.width(int_pred)
        coverages = visualize.coverage(int_pred, y_test)
        return {strat_name: widths[strat_name] * (1 + (coverages[strat_name] < (1 - miscoverage)) * (1 - coverages[strat_name])) for strat_name in int_pred}
    @staticmethod
    def goodness(y_true, y_pred, y_pred_low, y_pred_up, coverage, width, rmse, cwc, ax=None, title="Goodness Plot"):
        if ax is None:
            fig, ax = plt.subplots()
        n_samples = len(y_true)
        y_true_np = y_true.to_numpy().ravel() # Ensure y_true is numpy array and flattened

        # Determine points inside and outside the interval
        inside_interval = (y_true_np >= y_pred_low) & (y_true_np <= y_pred_up)
        outside_interval = ~inside_interval

        # Plot points inside the interval in green
        ax.scatter(y_true_np[inside_interval], y_pred[inside_interval], color='green', s=10, label='Inside Interval')
        # Plot points outside the interval in orange
        ax.scatter(y_true_np[outside_interval], y_pred[outside_interval], color='orange', s=10, label='Outside Interval')

        # Plot all ground truth values as blue crosses
        ax.scatter(y_true_np, y_true_np, color='blue', marker='x', s=30, linewidths=0.7, label='Ground Truth Values')


        ax.vlines(y_true_np, y_pred_low, y_pred_up, color='gray', alpha=0.5, label='Prediction Intervals')
        ax.plot([min(y_true_np), max(y_true_np)], [min(y_true_np), max(y_true_np)], linestyle='--', color='blue', label='Ideal Prediction Line') # Changed label for clarity
        ax.set_xlabel('Ground Truth')
        ax.set_ylabel('Predictions')
        ax.set_title(f'{title}\nCoverage: {coverage*100:.2f}%, Width: {width:.2f}, RMSE: {rmse:.2f}, CWC: {cwc:.2f}')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax

    @staticmethod
    def width_size_occurrence(int_pred, train_intervals, num_bins=10, ax=None, x_lim=None, title="Width Size Occurrence"):
        if ax is None:
            fig, ax = plt.subplots()

        # Calculate interval widths for test and train sets
        widths_test = np.abs(int_pred[:, 1] - int_pred[:, 0])
        widths_train = np.abs(train_intervals[:, 1] - train_intervals[:, 0])

        # Plot histograms for both train and test widths
        ax.hist(widths_test, bins=num_bins, alpha=0.6, label='Test Interval Widths', color='red')
        ax.hist(widths_train, bins=num_bins, alpha=0.4, label='Train Interval Widths', color='blue')


        if x_lim is not None:
            ax.set_xlim(x_lim)
        ax.set_xlabel('Interval Width')
        ax.set_ylabel('Occurrence (Frequency)')
        ax.set_title(f'{title} - Interval Width Occurrence')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax

    @staticmethod
    def coverage_by_width(y_test, int_pred, miscoverage, cond_coverages, num_bins=10, ax=None, title="Coverage vs Width"):
        if ax is None:
            fig, ax = plt.subplots()

        widths = int_pred[:, 1] - int_pred[:, 0]
        bin_edges = np.histogram_bin_edges(widths, bins=num_bins)
        bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2
        bin_width = bin_edges[1] - bin_edges[0]

        ax.bar(bin_centers, cond_coverages, width=bin_width, color='blue', alpha=0.7, edgecolor='black', linewidth=0.8, label='Conditional Coverage')
        ax.axhline(1 - miscoverage, color='red', linestyle='--', label=f'Nominal Coverage ({(1 - miscoverage)*100:.0f}%)')

        ax.set_xlabel('Interval Width')
        ax.set_ylabel('Conditional Coverage')
        ax.set_title(f'{title} - Coverage vs Interval Width')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax


def weighted_quantile(values, weights, q):
    sorter = np.argsort(values)
    values = values[sorter]
    weights = weights[sorter]
    cum_weights = np.cumsum(weights)
    cum_weights = cum_weights / cum_weights[-1]
    return np.interp(q, cum_weights, values)

In [10]:
def conformal_predictions_NEXCP(
    model_class,
    best_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name,
    excel_file_path=None,
    alpha=0.05,
    decay=0.99,
    n_folds=5,
    n_bootstrap=50,
):

    warnings.filterwarnings("ignore")

    SEED = 123
    np.random.seed(SEED)

    strategies_names = {
        "NexCP-Split": "NexCP Split",
        "NexCP-Full": "NexCP Full",
        "NexCP-J+aB": "NexCP Jackknife+ aB",
        "NexCP-CV+": "NexCP CV+",
    }

    y_pred, int_pred = {}, {}

    # =========================================================
    # NexCP – Split
    # =========================================================
    model = model_class(**best_params)
    model.fit(X_train, y_train)

    yhat_train = model.predict(X_train)
    yhat_test = model.predict(X_test)

    res = np.abs(y_train.to_numpy() - yhat_train)
    weights = decay ** np.arange(len(res) - 1, -1, -1)
    q = weighted_quantile(res, weights, 1 - alpha)

    y_pred["NexCP-Split"] = yhat_test
    int_pred["NexCP-Split"] = np.c_[yhat_test - q, yhat_test + q]

    # =========================================================
    # NexCP – Full
    # =========================================================
    model = model_class(**best_params)
    model.fit(X_train, y_train)

    yhat_train = model.predict(X_train)
    yhat_test = model.predict(X_test)

    q = np.quantile(np.abs(y_train.to_numpy() - yhat_train), 1 - alpha)

    y_pred["NexCP-Full"] = yhat_test
    int_pred["NexCP-Full"] = np.c_[yhat_test - q, yhat_test + q]

    # =========================================================
    # NexCP – Jackknife+ after Bootstrap
    # =========================================================
    rng = np.random.default_rng(SEED)
    lowers_t, uppers_t, preds_t = [], [], []

    for _ in range(n_bootstrap):
        idx = rng.choice(len(X_train), len(X_train), replace=True)

        model = model_class(**best_params)
        model.fit(X_train[idx], y_train.iloc[idx])

        yte = model.predict(X_test)

        q = np.quantile(
            np.abs(y_train.iloc[idx].to_numpy() - model.predict(X_train[idx])),
            1 - alpha,
        )

        lowers_t.append(yte - q)
        uppers_t.append(yte + q)
        preds_t.append(yte)

    y_pred["NexCP-J+aB"] = np.mean(preds_t, axis=0)
    int_pred["NexCP-J+aB"] = np.c_[np.min(lowers_t, axis=0), np.max(uppers_t, axis=0)]

    # =========================================================
    # NexCP – CV+
    # =========================================================
    kf = KFold(n_splits=n_folds, shuffle=True, random_state=SEED)

    lowers_t, uppers_t, preds_t = [], [], []

    for tr, cal in kf.split(X_train):
        model = model_class(**best_params)
        model.fit(X_train[tr], y_train.iloc[tr])

        y_cal = model.predict(X_train[cal])
        q = np.quantile(np.abs(y_train.iloc[cal].to_numpy() - y_cal), 1 - alpha)

        yte = model.predict(X_test)

        lowers_t.append(yte - q)
        uppers_t.append(yte + q)
        preds_t.append(yte)

    y_pred["NexCP-CV+"] = np.mean(preds_t, axis=0)
    int_pred["NexCP-CV+"] = np.c_[np.mean(lowers_t, axis=0), np.mean(uppers_t, axis=0)]

    # =========================================================
    # Metrics
    # =========================================================
    def coverage(y, l, u):
        return np.mean((y >= l) & (y <= u))

    def width(l, u):
        return np.mean(u - l)

    def cwc(l, u, y, alpha):
        cov = coverage(y, l, u)
        w = width(l, u)
        penalty = np.exp(-50 * (cov - (1 - alpha)))
        return w * (1 + penalty if cov < (1 - alpha) else 1)

    y_true = y_test.to_numpy()

    summary_rows = []

    print("\n===== NEXCP RESULTS =====")

    for s in strategies_names:
        cov = coverage(y_true, int_pred[s][:, 0], int_pred[s][:, 1])
        wid = width(int_pred[s][:, 0], int_pred[s][:, 1])
        rmse = np.sqrt(mean_squared_error(y_true, y_pred[s]))
        cwc_val = cwc(int_pred[s][:, 0], int_pred[s][:, 1], y_true, alpha)

        summary_rows.append([
            strategies_names[s],
            cov,
            wid,
            rmse,
            cwc_val,
        ])

        print(f"{strategies_names[s]} - Coverage: {cov*100:.3f}% | Width: {wid:.3f}")

    summary_df = pd.DataFrame(
        summary_rows,
        columns=["Strategy", "Coverage", "Width", "RMSE", "CWC"],
    )

    # =========================================================
    # Plotting (SAVE ONLY — NO SHOW)
    # =========================================================
    idx = np.arange(len(y_test))
    plot_buffers = {}

    for s in strategies_names:
        fig, ax = plt.subplots(figsize=(10, 4))

        ax.scatter(idx, y_test, color="blue", s=10, alpha=0.7, label="True")
        ax.fill_between(
            idx,
            int_pred[s][:, 0],
            int_pred[s][:, 1],
            color="gray",
            alpha=0.5,
            label="Prediction interval",
        )
        ax.plot(idx, y_pred[s], color="red", linewidth=1, label="Predicted mean")

        ax.set_title(strategies_names[s])
        ax.set_xlabel("Sample Number")
        ax.set_ylabel("Y_Label")
        ax.legend(loc="upper left")

        plt.tight_layout()

        buf = io.BytesIO()
        fig.savefig(buf, format="png")
        buf.seek(0)
        plot_buffers[s] = buf

        plt.close(fig)

    # =========================================================
    # Excel Export
    # =========================================================
    if excel_file_path:
        wb = load_workbook(excel_file_path)

        # ---- Summary sheet ----
        sheet_name = "NEXCP_Summary"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name, 0)
        for r_idx, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c_idx, val in enumerate(row, 1):
                ws.cell(row=r_idx, column=c_idx, value=val)

        # ---- Plot sheets ----
        for s, buf in plot_buffers.items():
            img = Image(buf)

            sheet_name = f"NEXCP_Plot_{s}"
            base = sheet_name
            i = 1
            while sheet_name in wb.sheetnames:
                sheet_name = f"{base}_{i}"
                i += 1

            ws = wb.create_sheet(sheet_name)
            ws.add_image(img, "A1")

        # ---- Values sheet ----
        results_dict = {}
        for s in strategies_names:
            results_dict[f"{s}_true"] = y_true
            results_dict[f"{s}_pred"] = y_pred[s]
            results_dict[f"{s}_lower"] = int_pred[s][:, 0]
            results_dict[f"{s}_upper"] = int_pred[s][:, 1]

        df_vals = pd.DataFrame(results_dict)

        sheet_name = "NEXCP_Values"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r_idx, row in enumerate(dataframe_to_rows(df_vals, index=False, header=True), 1):
            for c_idx, val in enumerate(row, 1):
                ws.cell(row=r_idx, column=c_idx, value=val)

        wb.save(excel_file_path)

    return summary_df

In [11]:
def conformal_predictions_online_super(
    model_class,
    model_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name,
    excel_file_path=None,
    alpha=0.05,
    strategies="all",
    window_min=50,
    window_max=500,
    window_grid=(25, 50, 100, 200, 400),
    n_bootstrap=30,
):

    warnings.filterwarnings("ignore")

    SEED = 123
    np.random.seed(SEED)

    STRATEGY_NAMES = {
        "Online-Split": "Online Split",
        "Online-CV+": "Online CV+",
        "Online-J+aB": "Online Jackknife+ aB",
        "SAOCP": "SAOCP",
        "SF-OGD": "SF-OGD",
        "FACI": "FACI",
        "MFCS-Split": "MFCS Split",
        "MFCS-Full": "MFCS Full",
    }

    ALL_STRATEGIES = list(STRATEGY_NAMES.keys())
    if strategies == "all":
        strategies = ALL_STRATEGIES

    # =========================================================
    # Base model
    # =========================================================
    base_model = model_class(**model_params)
    base_model.fit(X_train, y_train)

    yhat_train = base_model.predict(X_train)

    X_all = np.vstack([X_train, X_test])
    y_all = np.concatenate([y_train.to_numpy(), y_test.to_numpy()])

    n_train = len(X_train)
    T = len(y_all)

    y_hat_all = np.zeros(T)
    y_hat_all[:n_train] = yhat_train
    for t in range(n_train, T):
        y_hat_all[t] = base_model.predict(X_all[t:t + 1])[0]

    residuals = np.abs(y_all - y_hat_all)

    y_pred, int_pred = {}, {}

    # =========================================================
    # Online methods (UNCHANGED LOGIC)
    # =========================================================
    if "Online-Split" in strategies:
        q = np.quantile(residuals[:n_train], 1 - alpha)
        y_pred["Online-Split"] = y_hat_all[n_train:]
        int_pred["Online-Split"] = np.c_[y_hat_all[n_train:] - q,
                                         y_hat_all[n_train:] + q]

    if "Online-CV+" in strategies:
        lower, upper = [], []
        for t in range(n_train, T):
            q = np.quantile(residuals[:t], 1 - alpha)
            lower.append(y_hat_all[t] - q)
            upper.append(y_hat_all[t] + q)
        y_pred["Online-CV+"] = y_hat_all[n_train:]
        int_pred["Online-CV+"] = np.c_[lower, upper]

    if "Online-J+aB" in strategies:
        lowers, uppers, preds = [], [], []
        for _ in range(n_bootstrap):
            idx = np.random.choice(n_train, n_train, replace=True)
            m = model_class(**model_params)
            m.fit(X_train[idx], y_train.iloc[idx])
            res = np.abs(y_train.iloc[idx] - m.predict(X_train[idx]))
            q = np.quantile(res, 1 - alpha)
            p = m.predict(X_test)
            preds.append(p)
            lowers.append(p - q)
            uppers.append(p + q)
        y_pred["Online-J+aB"] = np.mean(preds, axis=0)
        int_pred["Online-J+aB"] = np.c_[np.min(lowers, axis=0),
                                        np.max(uppers, axis=0)]

    if "SAOCP" in strategies:
        lower, upper = [], []
        for t in range(n_train, T):
            w = min(max(window_min, t // 2), window_max)
            start = max(0, t - w)
            q = np.quantile(residuals[start:t], 1 - alpha)
            lower.append(y_hat_all[t] - q)
            upper.append(y_hat_all[t] + q)
        y_pred["SAOCP"] = y_hat_all[n_train:]
        int_pred["SAOCP"] = np.c_[lower, upper]

    if "SF-OGD" in strategies:
        q_t = np.quantile(residuals[:n_train], 1 - alpha)
        lower, upper = [], []
        for t in range(n_train, T):
            r_t = residuals[t]
            grad = alpha - (r_t <= q_t)
            eta = 1.0 / np.sqrt(t - n_train + 1)
            q_t = max(0.0, q_t - eta * grad)
            lower.append(y_hat_all[t] - q_t)
            upper.append(y_hat_all[t] + q_t)
        y_pred["SF-OGD"] = y_hat_all[n_train:]
        int_pred["SF-OGD"] = np.c_[lower, upper]

    if "FACI" in strategies:
        windows = list(window_grid)
        losses = np.zeros(len(windows))
        lower, upper = [], []
        for t in range(n_train, T):
            r_t = residuals[t]
            qs = []
            for i, w in enumerate(windows):
                start = max(0, t - w)
                q = np.quantile(residuals[start:t], 1 - alpha)
                qs.append(q)
                losses[i] += alpha * q + (r_t - q) * (r_t > q)
            q_star = qs[np.argmin(losses)]
            lower.append(y_hat_all[t] - q_star)
            upper.append(y_hat_all[t] + q_star)
        y_pred["FACI"] = y_hat_all[n_train:]
        int_pred["FACI"] = np.c_[lower, upper]

    if "MFCS-Split" in strategies:
        q = np.quantile(residuals[:n_train], 1 - alpha)
        y_pred["MFCS-Split"] = y_hat_all[n_train:]
        int_pred["MFCS-Split"] = np.c_[y_hat_all[n_train:] - q,
                                       y_hat_all[n_train:] + q]

    if "MFCS-Full" in strategies:
        lower, upper, preds = [], [], []
        for t in range(n_train, T):
            m = model_class(**model_params)
            m.fit(X_all[:t], y_all[:t])
            yhat = m.predict(X_all[t:t + 1])[0]
            preds.append(yhat)
            res = np.abs(y_all[:t] - m.predict(X_all[:t]))
            q = np.quantile(res, 1 - alpha)
            lower.append(yhat - q)
            upper.append(yhat + q)
        y_pred["MFCS-Full"] = np.array(preds)
        int_pred["MFCS-Full"] = np.c_[lower, upper]

    # =========================================================
    # METRICS
    # =========================================================
    y_true = y_test.to_numpy().ravel()

    rows = []
    for s in y_pred:
        ymin, ymax = int_pred[s].T
        cov = np.mean((y_true >= ymin) & (y_true <= ymax))
        wid = np.mean(ymax - ymin)
        rmse = np.sqrt(mean_squared_error(y_true, y_pred[s]))
        cwc = wid * (1 + (cov < (1 - alpha)) * (1 - cov))

        rows.append([STRATEGY_NAMES[s], cov, wid, rmse, cwc])

    summary_df = pd.DataFrame(
        rows, columns=["Strategy", "Coverage", "Width", "RMSE", "CWC"]
    )

    print("\n===== ONLINE CP RESULTS =====")
    print(summary_df)

    # =========================================================
    # PLOTTING (SAVE ONLY)
    # =========================================================
    plot_buffers = {}
    idx = np.arange(len(y_test))

    for s in y_pred:
        fig, ax = plt.subplots(figsize=(10, 4))

        ax.scatter(idx, y_true, color="blue", s=10, alpha=0.7, label="True")
        ax.fill_between(idx,
                        int_pred[s][:, 0],
                        int_pred[s][:, 1],
                        color="gray",
                        alpha=0.5,
                        label="Prediction interval")
        ax.plot(idx, y_pred[s], color="red", linewidth=1, label="Predicted mean")

        ax.set_title(f"{STRATEGY_NAMES[s]} ({model_name})")
        ax.set_xlabel("Sample Number")
        ax.set_ylabel("Y_Label")
        ax.legend(loc="upper left")

        plt.tight_layout()

        buf = io.BytesIO()
        fig.savefig(buf, format="png")
        buf.seek(0)
        plot_buffers[s] = buf

        plt.close(fig)

    # =========================================================
    # EXCEL EXPORT (APPEND SAFE)
    # =========================================================
    if excel_file_path:
        wb = load_workbook(excel_file_path)

        # ---- Summary ----
        sheet_name = "ONLINECP_Summary"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        # ---- Plots ----
        for s, buf in plot_buffers.items():
            img = Image(buf)
            sheet_name = f"ONLINECP_Plot_{s}"
            base = sheet_name
            i = 1
            while sheet_name in wb.sheetnames:
                sheet_name = f"{base}_{i}"
                i += 1
            ws = wb.create_sheet(sheet_name)
            ws.add_image(img, "A1")

        # ---- Values ----
        values = {}
        for s in y_pred:
            values[f"{s}_true"] = y_true
            values[f"{s}_pred"] = y_pred[s]
            values[f"{s}_lower"] = int_pred[s][:, 0]
            values[f"{s}_upper"] = int_pred[s][:, 1]

        df_vals = pd.DataFrame(values)

        sheet_name = "ONLINECP_Values"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(df_vals, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        wb.save(excel_file_path)

    return summary_df

In [12]:
def conformal_predictions_COP(
    model_class,
    model_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name,
    excel_file_path=None,
    alpha=0.05,
    lr=0.05,          # Learning rate for COP
    T_burnin=50,      # Window size for distribution estimation
    scale=0.5,        # Scale factor for the integrator
    random_state=123,
):
    """
    Conformal Optimistic Prediction (COP)
    ✔ Implements the Distribution-Informed Gradient logic from the repository.
    ✔ Matches the "Excel-safe" and plotting structure of your previous functions.
    """

    warnings.filterwarnings("ignore")
    np.random.seed(random_state)

    # =========================================================
    # 1. Train Base Model & Generate Test Predictions
    # =========================================================
    # COP is an online calibration method, but we usually start with a pre-trained model
    # or an online model. Here we fit on Train and calibrate on Test stream.
    model = model_class(**model_params)
    model.fit(X_train, y_train)

    # Predict on test set
    y_pred_test = model.predict(X_test).ravel()
    y_true_test = y_test.to_numpy().ravel()

    # Calculate non-conformity scores (Absolute Residuals)
    # This assumes symmetric intervals.
    scores = np.abs(y_true_test - y_pred_test)
    T_test = len(scores)

    # =========================================================
    # 2. COP Initialization
    # =========================================================
    # Initialize quantiles based on training data residuals if possible
    y_pred_train = model.predict(X_train).ravel()
    scores_train = np.abs(y_train.to_numpy().ravel() - y_pred_train)
    init_q = np.quantile(scores_train, 1 - alpha)

    # Arrays to store history
    qs = np.zeros(T_test)          # Final adaptive quantile
    qts = np.zeros(T_test)         # Base quantile term
    integrators = np.zeros(T_test) # Optimistic integrator term
    covereds = np.zeros(T_test)    # Coverage boolean

    # Set initial values
    qs[0] = init_q
    qts[0] = init_q

    # =========================================================
    # 3. Online COP Loop
    # =========================================================
    # Logic adapted from `core/methods.py` function `COP`

    for t in range(T_test - 1):
        # 1. Observe coverage at current step t
        covereds[t] = 1 if qs[t] >= scores[t] else 0

        # 2. Calculate Standard Gradient
        # If covered, we decrease q (grad is positive). If not, increase q.
        grad = alpha if covereds[t] else -(1 - alpha)

        # 3. Calculate Distribution-Informed Gradient (The "Optimistic" part)
        if t < T_burnin:
            grad_i = 0
        else:
            # Look at the window of recent scores
            window_s = scores[t - T_burnin : t]

            # Calculate ECDF at the predicted next quantile step
            # logic: np.mean(window_s <= qts[t] - lr * grad) - (1 - alpha)
            current_target = qts[t] - lr * grad
            grad_i = np.mean(window_s <= current_target) - (1 - alpha)

        # 4. Update Terms
        integrator = -scale * grad_i

        # Update base quantile (Gradient Descent)
        qts[t + 1] = qts[t] - lr * grad

        # Update integrator state
        integrators[t + 1] = lr * integrator

        # Combine for final quantile
        qs[t + 1] = qts[t + 1] + integrators[t + 1]

        # Safety: Ensure quantile implies non-negative width
        qs[t + 1] = max(0, qs[t + 1])

    # Handle the final step coverage for metrics
    covereds[-1] = 1 if qs[-1] >= scores[-1] else 0

    # =========================================================
    # 4. Construct Prediction Intervals
    # =========================================================
    ymin = y_pred_test - qs
    ymax = y_pred_test + qs

    # =========================================================
    # 5. Metrics
    # =========================================================
    rmse = np.sqrt(mean_squared_error(y_true_test, y_pred_test))
    coverage = np.mean(covereds)
    avg_width = np.mean(ymax - ymin)

    print(f"\n===== CONFORMAL OPTIMISTIC PREDICTION ({model_name}) =====")
    print(f"Coverage : {coverage*100:.3f}%")
    print(f"Avg Width: {avg_width:.3f}")
    print(f"RMSE     : {rmse:.3f}")
    print(f"Final q  : {qs[-1]:.3f}")

    # =========================================================
    # 6. Summary Tables
    # =========================================================
    summary_df = pd.DataFrame([{
        "Strategy": "COP",
        "Coverage": coverage,
        "Width": avg_width,
        "RMSE": rmse,
        "Alpha": alpha,
        "LR": lr,
        "Scale": scale
    }])

    values_df = pd.DataFrame({
        "sample_index": np.arange(len(y_true_test)),
        "y_true": y_true_test,
        "y_pred": y_pred_test,
        "ymin": ymin,
        "ymax": ymax,
        "width": ymax - ymin,
        "is_covered": covereds.astype(int),
        "score_residual": scores,
        "adaptive_q": qs
    })

    # =========================================================
    # 7. Plotting
    # =========================================================
    idx = np.arange(len(y_true_test))
    fig, ax = plt.subplots(figsize=(10, 4))

    ax.scatter(idx, y_true_test, color="blue", s=10, alpha=0.7, label="True")
    ax.fill_between(idx, ymin, ymax, color="gray", alpha=0.5, label="COP Interval")
    ax.plot(idx, y_pred_test, color="red", linewidth=1, label="Predicted mean")

    ax.set_title(f"Conformal Optimistic Prediction (COP) - {model_name}")
    ax.set_xlabel("Sample Number")
    ax.set_ylabel("Y_Label")
    ax.legend(loc="upper left")

    plt.tight_layout()

    buf = io.BytesIO()
    fig.savefig(buf, format="png")
    buf.seek(0)
    plt.close(fig)

    # =========================================================
    # 8. Excel Export
    # =========================================================
    if excel_file_path:
        try:
            wb = load_workbook(excel_file_path)
        except FileNotFoundError:
            # Create a new workbook if it doesn't exist
            from openpyxl import Workbook
            wb = Workbook()
            wb.remove(wb.active) # Remove default sheet

        # ---- Summary ----
        sheet_name = "COP_Summary"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        # ---- Plot ----
        img = Image(buf)
        sheet_name = "COP_Plot"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        ws.add_image(img, "A1")

        # ---- Values ----
        sheet_name = "COP_Values"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        wb.save(excel_file_path)

    return summary_df

In [13]:
def conformal_predictions_EXTREME(
    model_class,
    model_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name,
    excel_file_path=None,
    alpha=0.05,
    calib_size=0.2,
    gpd_threshold_quantile=0.95,
    n_bootstrap=30,
    random_state=123,
):
    """
    Extreme Conformal Prediction (upper-tail, single-sided)
    ✔ Same structure as NexCP & OnlineCP
    ✔ No return values
    ✔ Excel-safe
    """

    warnings.filterwarnings("ignore")
    np.random.seed(random_state)

    # =========================================================
    # Train / calibration split
    # =========================================================
    X_fit, X_calib, y_fit, y_calib = train_test_split(
        X_train,
        y_train,
        test_size=calib_size,
        random_state=random_state,
        shuffle=True,
    )

    # =========================================================
    # Train model
    # =========================================================
    model = model_class(**model_params)
    model.fit(X_fit, y_fit)

    y_pred_test = model.predict(X_test).ravel()
    y_pred_calib = model.predict(X_calib).ravel()

    # =========================================================
    # Nonconformity scores (upper tail only)
    # =========================================================
    scores = y_calib.to_numpy().ravel() - y_pred_calib
    scores = scores[scores > 0]

    if len(scores) < 30:
        raise RuntimeError("Too few calibration exceedances for GPD fitting.")

    # =========================================================
    # Peaks-over-threshold
    # =========================================================
    u = np.quantile(scores, gpd_threshold_quantile)
    excesses = scores[scores > u] - u

    # =========================================================
    # Bootstrap GPD extreme quantile
    # =========================================================
    boot_q = []
    n_exc = len(excesses)
    n_scores = len(scores)

    for _ in range(n_bootstrap):
        resampled = np.random.choice(excesses, size=n_exc, replace=True)
        xi_b, _, sigma_b = genpareto.fit(resampled, floc=0)

        q_b = (
            u
            + (sigma_b / xi_b)
            * ((n_scores / (n_scores * alpha)) ** xi_b - 1)
        )
        boot_q.append(q_b)

    q_extreme = np.quantile(boot_q, 0.95)

    # =========================================================
    # Finite prediction intervals (for plotting & width)
    # =========================================================
    ymin = y_pred_test - q_extreme
    ymax = y_pred_test + q_extreme

    # =========================================================
    # Metrics
    # =========================================================
    y_true = y_test.to_numpy().ravel()

    rmse = np.sqrt(mean_squared_error(y_true, y_pred_test))
    coverage = np.mean(y_true <= ymax)
    width = q_extreme  # meaningful one-sided width

    print(f"\n===== EXTREME CONFORMAL PREDICTION ({model_name}) =====")
    print(f"Coverage : {coverage*100:.3f}%")
    print(f"Width    : {width:.3f}")
    print(f"RMSE     : {rmse:.3f}")
    print(f"q_extreme: {q_extreme:.3f}")
    print(f"u        : {u:.3f}")
    print(f"#Exceed. : {len(scores)}")

    # =========================================================
    # Summary table
    # =========================================================
    summary_df = pd.DataFrame([{
        "Strategy": "EXTREME CP",
        "Coverage": coverage,
        "Width": width,
        "RMSE": rmse,
        "q_extreme": q_extreme,
        "threshold_u": u,
        "n_exceedances": len(scores),
    }])

    # =========================================================
    # Values table
    # =========================================================
    values_df = pd.DataFrame({
        "sample_index": np.arange(len(y_true)),
        "y_true": y_true,
        "y_pred": y_pred_test,
        "ymin": ymin,
        "ymax": ymax,
        "width": ymax - ymin,
        "is_covered": (y_true <= ymax).astype(int),
        "residual": y_true - y_pred_test,
    })

    # =========================================================
    # Plot (SAVE ONLY)
    # =========================================================
    idx = np.arange(len(y_true))

    fig, ax = plt.subplots(figsize=(10, 4))
    ax.scatter(idx, y_true, s=10, alpha=0.7, label="True")
    ax.fill_between(idx, ymin, ymax, alpha=0.4, label="Extreme PI")
    ax.plot(idx, y_pred_test, color="red", lw=1, label="Prediction")

    ax.set_title(f"Extreme Conformal Prediction ({model_name})")
    ax.set_xlabel("Sample Number")
    ax.set_ylabel("Y_Label")
    ax.legend(loc="upper left")

    plt.tight_layout()

    buf = io.BytesIO()
    fig.savefig(buf, format="png")
    buf.seek(0)
    plt.close(fig)

    # =========================================================
    # Excel export (append-safe, SAME FILE)
    # =========================================================
    if excel_file_path:
        wb = load_workbook(excel_file_path)

        # ---- Summary ----
        sheet_name = "EXTREMECP_Summary"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        # ---- Plot ----
        img = Image(buf)
        sheet_name = "EXTREMECP_Plot"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        ws.add_image(img, "A1")

        # ---- Values ----
        sheet_name = "EXTREMECP_Values"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        wb.save(excel_file_path)

In [14]:


try:
    from tqdm.auto import tqdm
    HAS_TQDM = True
except ImportError:
    HAS_TQDM = False
    print("[Info] Install tqdm for progress bars: pip install tqdm")


# ═══════════════════════════════════════════════════════════
# AlphaNet Architecture  (FIXED)
# ═══════════════════════════════════════════════════════════
class AlphaNet(nn.Module):
    """
    Maps a feature vector (sum of LOO scores) → learned α̃.
    Output is clamped to (alpha_min, 1) so that the conformal
    denominator α̃·(n+1)−1 is always positive.
    """

    def __init__(self, input_dim, alpha_min=0.05):
        super().__init__()
        self.fc1 = nn.Linear(input_dim, 32)
        self.fc2 = nn.Linear(32, 1)
        self.relu = nn.ReLU()
        self.sigmoid = nn.Sigmoid()
        self.alpha_min = alpha_min  # lower bound for valid α̃
        self._initialize_near_one()

    def _initialize_near_one(self):
        """Bias output toward α̃ ≈ 1 at init (sigmoid(5) ≈ 0.993)."""
        with torch.no_grad():
            self.fc2.weight.data.normal_(0, 0.01)
            self.fc2.bias.data.fill_(5.0)

    def forward(self, x):
        x = self.relu(self.fc1(x))
        raw = self.sigmoid(self.fc2(x)).squeeze(-1)
        # Remap from (0,1) → (alpha_min, 1) so denominator stays positive
        return self.alpha_min + (1.0 - self.alpha_min) * raw


def _interval_size(scores, alpha, eps=1e-8):
    """
    Conformal interval width = 2 * Σscores / (α̃·(n+1) − 1).
    Denominator is clamped to be strictly positive.
    """
    n = len(scores)
    denom = alpha * (n + 1) - 1
    denom = torch.clamp(denom, min=eps)   # ← KEY FIX: prevent negative/zero
    r = scores.sum() / denom
    return 2 * r


def _fmt_time(seconds):
    """Format seconds into human-readable string."""
    if seconds < 60:
        return f"{seconds:.0f}s"
    elif seconds < 3600:
        return f"{seconds/60:.1f}min"
    else:
        return f"{seconds/3600:.1f}hr"


# ═══════════════════════════════════════════════════════════
# Main function  (CORRECTED + PROGRESS TRACKING)
# ═══════════════════════════════════════════════════════════
def conformal_predictions_AlphaNet(
    model_class,
    model_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name,
    excel_file_path=None,
    alpha=0.05,
    lambda_reg=20.0,
    num_epochs=50,
    batch_size=32,
    lr_alpha=1e-3,
    calib_fraction=0.5,
    num_runs=4,
    random_state=123,
):
    """
    Learned-α Conformal Prediction via AlphaNet.
    - FIXED: α̃ clamped to valid range (no negative intervals)
    - FIXED: LOO scores precomputed (massive speedup)
    - ADDED: tqdm progress bars + ETA estimates
    """

    warnings.filterwarnings("ignore")
    np.random.seed(random_state)
    torch.manual_seed(random_state)
    device = "cuda" if torch.cuda.is_available() else "cpu"

    t_start_total = time.time()

    # --- numpy-ify if pandas ---
    y_train_np = y_train.to_numpy().ravel() if hasattr(y_train, "to_numpy") else np.asarray(y_train).ravel()
    y_test_np  = y_test.to_numpy().ravel()  if hasattr(y_test,  "to_numpy") else np.asarray(y_test).ravel()
    X_train_np = X_train.to_numpy() if hasattr(X_train, "to_numpy") else np.asarray(X_train)
    X_test_np  = X_test.to_numpy()  if hasattr(X_test,  "to_numpy") else np.asarray(X_test)

    # =================================================================
    # 1.  Split training data → fit + calibration
    # =================================================================
    n_total = len(X_train_np)
    n_fit   = int(n_total * (1 - calib_fraction))
    perm    = np.random.permutation(n_total)

    fit_idx   = perm[:n_fit]
    calib_idx = perm[n_fit:]

    X_fit,   y_fit   = X_train_np[fit_idx],   y_train_np[fit_idx]
    X_calib, y_calib = X_train_np[calib_idx],  y_train_np[calib_idx]
    n_calib = len(X_calib)

    # Compute alpha_min: must satisfy α̃·(n+1) − 1 > 0  →  α̃ > 1/(n+1)
    alpha_min = 1.0 / (n_calib + 1) + 0.01   # small margin above threshold
    print(f"  [Info] n_calib={n_calib} | alpha_min={alpha_min:.4f}")

    # =================================================================
    # 2.  Train base regression model
    # =================================================================
    print(f"  [Step 2/9] Training base {model_name} model...")
    t0 = time.time()
    base_model = model_class(**model_params)
    base_model.fit(X_fit, y_fit)
    print(f"  [Step 2/9] Done in {_fmt_time(time.time()-t0)}")

    # =================================================================
    # 3.  PRECOMPUTE all LOO scores  (KEY SPEEDUP)
    # =================================================================
    print(f"  [Step 3/9] Precomputing {n_calib} LOO score vectors...")
    t0 = time.time()

    precomputed_scores = []
    precomputed_sums   = []

    iterator = tqdm(range(n_calib), desc="    LOO precompute", leave=False) if HAS_TQDM else range(n_calib)

    for i in iterator:
        loo_X = np.delete(X_calib, i, axis=0)
        loo_y = np.delete(y_calib, i, axis=0)
        scores_loo = np.abs(base_model.predict(loo_X).ravel() - loo_y)

        scores_tensor = torch.tensor(scores_loo, dtype=torch.float32).to(device)
        precomputed_scores.append(scores_tensor)
        precomputed_sums.append(scores_loo.sum())

    elapsed_precompute = time.time() - t0
    print(f"  [Step 3/9] Done in {_fmt_time(elapsed_precompute)}")

    # Build feature matrix (sum of LOO scores per sample)
    X_alpha = torch.tensor(
        np.array(precomputed_sums).reshape(-1, 1),
        dtype=torch.float32,
    ).to(device)

    # =================================================================
    # 4.  Train AlphaNet (multiple runs, keep best)
    # =================================================================
    print(f"  [Step 4/9] Training AlphaNet: {num_runs} runs × {num_epochs} epochs")

    best_net   = None
    best_loss  = np.inf
    history    = {"losses": [], "sizes": [], "alphas": []}

    t0_train = time.time()

    for run in range(num_runs):
        np.random.seed(run)
        torch.manual_seed(run)

        alpha_net = AlphaNet(input_dim=1, alpha_min=alpha_min).to(device)
        optimizer = optim.Adam(alpha_net.parameters(), lr=lr_alpha)

        dataset = TensorDataset(X_alpha, torch.arange(n_calib))
        loader  = DataLoader(dataset, batch_size=batch_size, shuffle=True)

        run_losses, run_sizes, run_alphas = [], [], []

        epoch_iter = (
            tqdm(range(num_epochs), desc=f"    Run {run+1}/{num_runs}", leave=False)
            if HAS_TQDM else range(num_epochs)
        )

        for epoch in epoch_iter:
            t_epoch_start = time.time()
            epoch_loss = epoch_size = epoch_alpha = 0.0

            for x_batch, idx_batch in loader:
                x_batch = x_batch.to(device)
                alpha_pred = alpha_net(x_batch)

                batch_sizes = []
                for j, idx in enumerate(idx_batch):
                    # USE PRECOMPUTED scores instead of calling predict()
                    scores_t = precomputed_scores[idx.item()]
                    size_j = _interval_size(scores_t, alpha_pred[j])
                    batch_sizes.append(size_j)

                batch_sizes = torch.stack(batch_sizes)
                loss = (batch_sizes + lambda_reg * alpha_pred).mean()

                optimizer.zero_grad()
                loss.backward()
                optimizer.step()

                epoch_loss  += loss.item()
                epoch_size  += batch_sizes.mean().item()
                epoch_alpha += alpha_pred.mean().item()

            n_batches = len(loader)
            run_losses.append(epoch_loss  / n_batches)
            run_sizes.append(epoch_size   / n_batches)
            run_alphas.append(epoch_alpha / n_batches)

            epoch_time = time.time() - t_epoch_start

            if epoch % 10 == 0 or epoch == num_epochs - 1:
                epochs_done = (run * num_epochs) + epoch + 1
                epochs_total = num_runs * num_epochs
                elapsed_train = time.time() - t0_train
                eta = (elapsed_train / epochs_done) * (epochs_total - epochs_done)

                print(
                    f"  λ={lambda_reg} | Run {run+1}/{num_runs} | "
                    f"Epoch {epoch}/{num_epochs} | "
                    f"Loss: {run_losses[-1]:.4f} | "
                    f"Size: {run_sizes[-1]:.4f} | "
                    f"α̃: {run_alphas[-1]:.4f} | "
                    f"⏱ {epoch_time:.2f}s/epoch | "
                    f"ETA: {_fmt_time(eta)}"
                )

        if run_losses[-1] < best_loss:
            best_loss = run_losses[-1]
            best_net  = alpha_net

        history["losses"].append(run_losses)
        history["sizes"].append(run_sizes)
        history["alphas"].append(run_alphas)

        print(f"  ✓ Run {run+1} complete | Final loss: {run_losses[-1]:.4f}")

    train_time = time.time() - t0_train
    print(f"  [Step 4/9] Training done in {_fmt_time(train_time)}")

    alpha_net = best_net
    alpha_net.eval()

    # =================================================================
    # 5.  Compute conformal intervals on the TEST set
    # =================================================================
    print(f"  [Step 5/9] Computing conformal intervals on test set...")

    scores_calib = np.abs(base_model.predict(X_calib).ravel() - y_calib)
    sum_scores   = scores_calib.sum()

    with torch.no_grad():
        feat_test = torch.tensor([sum_scores], dtype=torch.float32).to(device)
        alpha_val = alpha_net(feat_test).item()

    denom = alpha_val * (n_calib + 1) - 1
    if denom <= 0:
        q = np.quantile(scores_calib, 1 - alpha)
        half_width = q
        print(f"  [Warning] α̃ too small (denom={denom:.4f}); fallback q={q:.4f}")
    else:
        half_width = sum_scores / denom

    y_pred_test = base_model.predict(X_test_np).ravel()
    ymin = y_pred_test - half_width
    ymax = y_pred_test + half_width

    # =================================================================
    # 6.  Metrics
    # =================================================================
    y_true_test = y_test_np
    is_covered  = ((y_true_test >= ymin) & (y_true_test <= ymax)).astype(int)
    coverage    = is_covered.mean()
    avg_width   = np.mean(ymax - ymin)
    rmse        = np.sqrt(mean_squared_error(y_true_test, y_pred_test))

    total_time = time.time() - t_start_total

    print(f"\n{'='*55}")
    print(f"  ALPHANET CONFORMAL ({model_name})")
    print(f"{'='*55}")
    print(f"  Learned α̃     : {alpha_val:.4f}")
    print(f"  Half-width (r) : {half_width:.4f}")
    print(f"  Coverage       : {coverage*100:.3f}%")
    print(f"  Avg Width      : {avg_width:.4f}")
    print(f"  RMSE           : {rmse:.4f}")
    print(f"  Total time     : {_fmt_time(total_time)}")
    print(f"    ├─ Precompute: {_fmt_time(elapsed_precompute)}")
    print(f"    └─ Training  : {_fmt_time(train_time)}")
    print(f"{'='*55}")

    # =================================================================
    # 7.  Summary & values DataFrames
    # =================================================================
    summary_df = pd.DataFrame([{
        "Strategy":       "AlphaNet Conformal",
        "Coverage":       coverage,
        "Width":          avg_width,
        "RMSE":           rmse,
        "Alpha_nominal":  alpha,
        "Alpha_learned":  alpha_val,
        "Lambda_reg":     lambda_reg,
        "Total_time_sec": round(total_time, 2),
    }])

    values_df = pd.DataFrame({
        "sample_index": np.arange(len(y_true_test)),
        "y_true":       y_true_test,
        "y_pred":       y_pred_test,
        "ymin":         ymin,
        "ymax":         ymax,
        "width":        ymax - ymin,
        "is_covered":   is_covered,
    })

    # =================================================================
    # 8.  Plotting (SAVE ONLY — NO SHOW)
    # =================================================================
    print(f"  [Step 8/9] Generating plots...")
    idx = np.arange(len(y_true_test))

    # --- PI plot ---
    fig_pi, ax_pi = plt.subplots(figsize=(10, 4))
    ax_pi.scatter(idx, y_true_test, color="blue", s=10, alpha=0.7, label="True")
    ax_pi.fill_between(idx, ymin, ymax, color="gray", alpha=0.5,
                       label=f"AlphaNet Interval (α̃={alpha_val:.3f})")
    ax_pi.plot(idx, y_pred_test, color="red", linewidth=1, label="Predicted mean")
    ax_pi.set_title(f"AlphaNet Conformal – {model_name}")
    ax_pi.set_xlabel("Sample Number")
    ax_pi.set_ylabel("Y_Label")
    ax_pi.legend(loc="upper left")
    plt.tight_layout()

    buf_pi = io.BytesIO()
    fig_pi.savefig(buf_pi, format="png")
    buf_pi.seek(0)
    plt.close(fig_pi)

    # --- Training curves ---
    arr_losses = np.array(history["losses"])
    arr_sizes  = np.array(history["sizes"])
    arr_alphas = np.array(history["alphas"])
    epochs_arr = np.arange(1, num_epochs + 1)

    fig_tc, axs = plt.subplots(1, 3, figsize=(14, 4))
    for ax, data, ylabel, title in zip(
        axs,
        [arr_losses, arr_sizes, arr_alphas],
        ["Loss", "Mean Interval Size", r"Mean $\tilde{\alpha}$"],
        ["Training Loss", "Interval Size", r"Learned $\tilde{\alpha}$"],
    ):
        m = data.mean(axis=0)
        s = data.std(axis=0)
        ax.plot(epochs_arr, m, color="#0077bb")
        ax.fill_between(epochs_arr, m - s, m + s, color="#0077bb", alpha=0.25)
        ax.set_xlabel("Epoch")
        ax.set_ylabel(ylabel)
        ax.set_title(title)
        ax.grid(True, linewidth=0.5)
    plt.tight_layout()

    buf_tc = io.BytesIO()
    fig_tc.savefig(buf_tc, format="png")
    buf_tc.seek(0)
    plt.close(fig_tc)

    # =================================================================
    # 9.  Excel Export
    # =================================================================
    if excel_file_path:
        print(f"  [Step 9/9] Saving to Excel...")
        try:
            wb = load_workbook(excel_file_path)
        except FileNotFoundError:
            from openpyxl import Workbook
            wb = Workbook()
            wb.remove(wb.active)

        def _unique_sheet(wb, name):
            base, i = name, 1
            while name in wb.sheetnames:
                name = f"{base}_{i}"; i += 1
            return name

        sn = _unique_sheet(wb, "AlphaNet_Summary")
        ws = wb.create_sheet(sn, 0)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        sn = _unique_sheet(wb, "AlphaNet_Plot_PI")
        ws = wb.create_sheet(sn)
        ws.add_image(Image(buf_pi), "A1")

        sn = _unique_sheet(wb, "AlphaNet_Plot_Train")
        ws = wb.create_sheet(sn)
        ws.add_image(Image(buf_tc), "A1")

        sn = _unique_sheet(wb, "AlphaNet_Values")
        ws = wb.create_sheet(sn)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        wb.save(excel_file_path)
        print(f"  [Step 9/9] Saved!")

    print(f"\n  ✅ AlphaNet Conformal complete in {_fmt_time(total_time)}")
    return summary_df

# **Tuned Parameters**

In [15]:
best_scores_autosampler = {('Random Forest', 'MedianPruner'): {'best_score': 125647.84335013448,
  'best_params': {'n_estimators': 700,
   'criterion': 'absolute_error',
   'max_depth': 20,
   'min_samples_split': 0.01,
   'min_samples_leaf': 5,
   'min_weight_fraction_leaf': 0.01,
   'max_features': 'sqrt',
   'max_leaf_nodes': 50,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.1},
  'test_mse': 125647.84335013448,
  'test_rmse': 354.4683954178912,
  'test_corr_coef': 0.9579299217249909,
  'pruner': 'MedianPruner'},
 ('Random Forest', 'NopPruner'): {'best_score': 115703.5673107638,
  'best_params': {'n_estimators': 300,
   'criterion': 'absolute_error',
   'max_depth': None,
   'min_samples_split': 10,
   'min_samples_leaf': 0.01,
   'min_weight_fraction_leaf': 0.01,
   'max_features': 1.0,
   'max_leaf_nodes': 200,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.01},
  'test_mse': 115703.5673107638,
  'test_rmse': 340.1522707711413,
  'test_corr_coef': 0.9615119752252415,
  'pruner': 'NopPruner'},
 ('Random Forest', 'PatientPruner'): {'best_score': 115629.12224649779,
  'best_params': {'n_estimators': 300,
   'criterion': 'absolute_error',
   'max_depth': 40,
   'min_samples_split': 2,
   'min_samples_leaf': 0.01,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 1.0,
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.2,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.1},
  'test_mse': 115629.12224649779,
  'test_rmse': 340.04282413616346,
  'test_corr_coef': 0.9615056996911798,
  'pruner': 'PatientPruner'},
 ('Random Forest', 'PercentilePruner'): {'best_score': 117503.65849868047,
  'best_params': {'n_estimators': 200,
   'criterion': 'absolute_error',
   'max_depth': None,
   'min_samples_split': 5,
   'min_samples_leaf': 0.01,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 1.0,
   'max_leaf_nodes': 50,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.001},
  'test_mse': 117503.65849868047,
  'test_rmse': 342.78806644730275,
  'test_corr_coef': 0.9609173489911242,
  'pruner': 'PercentilePruner'},
 ('Random Forest',
  'SuccessiveHalvingPruner'): {'best_score': 126584.35298970548, 'best_params': {'n_estimators': 200,
   'criterion': 'absolute_error',
   'max_depth': 20,
   'min_samples_split': 0.01,
   'min_samples_leaf': 5,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 0.3,
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.01,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.01}, 'test_mse': 126584.35298970548, 'test_rmse': 355.7869488748927, 'test_corr_coef': 0.9595107925559148, 'pruner': 'SuccessiveHalvingPruner'},
 ('Random Forest', 'HyperbandPruner'): {'best_score': 125243.55676457845,
  'best_params': {'n_estimators': 500,
   'criterion': 'absolute_error',
   'max_depth': 40,
   'min_samples_split': 5,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.01,
   'max_features': 'sqrt',
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.01,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.001},
  'test_mse': 125243.55676457845,
  'test_rmse': 353.8976642542,
  'test_corr_coef': 0.9581547133700536,
  'pruner': 'HyperbandPruner'},
 ('Random Forest', 'ThresholdPruner'): {'best_score': 124854.97625512879,
  'best_params': {'n_estimators': 700,
   'criterion': 'absolute_error',
   'max_depth': None,
   'min_samples_split': 0.01,
   'min_samples_leaf': 3,
   'min_weight_fraction_leaf': 0.01,
   'max_features': 'sqrt',
   'max_leaf_nodes': 100,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.0},
  'test_mse': 124854.97625512879,
  'test_rmse': 353.348236524719,
  'test_corr_coef': 0.9581803650792393,
  'pruner': 'ThresholdPruner'},
 ('Random Forest', 'WilcoxonPruner'): {'best_score': 127823.90890176565,
  'best_params': {'n_estimators': 500,
   'criterion': 'absolute_error',
   'max_depth': None,
   'min_samples_split': 5,
   'min_samples_leaf': 5,
   'min_weight_fraction_leaf': 0.0,
   'max_features': 0.5,
   'max_leaf_nodes': None,
   'min_impurity_decrease': 0.0,
   'n_jobs': -1,
   'random_state': 42,
   'verbose': 0,
   'warm_start': False,
   'ccp_alpha': 0.001},
  'test_mse': 127823.90890176565,
  'test_rmse': 357.5246969116478,
  'test_corr_coef': 0.9601312789260384,
  'pruner': 'WilcoxonPruner'},
 ('Gradient Boosting', 'MedianPruner'): {'best_score': 98151.97595540313,
  'best_params': {'loss': 'huber',
   'learning_rate': 0.1,
   'n_estimators': 300,
   'subsample': 1.0,
   'criterion': 'friedman_mse',
   'min_samples_split': 0.01,
   'min_samples_leaf': 3,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 10,
   'min_impurity_decrease': 0.01,
   'init': None,
   'random_state': 42,
   'max_features': 'sqrt',
   'alpha': 0.5,
   'verbose': 0,
   'max_leaf_nodes': None,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': None,
   'tol': 0.001,
   'ccp_alpha': 0.001},
  'test_mse': 98151.97595540313,
  'test_rmse': 313.2921575070195,
  'test_corr_coef': 0.9675686886787896,
  'pruner': 'MedianPruner'},
 ('Gradient Boosting', 'NopPruner'): {'best_score': 106575.03780853433,
  'best_params': {'loss': 'huber',
   'learning_rate': 0.1,
   'n_estimators': 100,
   'subsample': 0.7,
   'criterion': 'friedman_mse',
   'min_samples_split': 5,
   'min_samples_leaf': 0.01,
   'min_weight_fraction_leaf': 0.0,
   'max_depth': 5,
   'min_impurity_decrease': 0.01,
   'init': None,
   'random_state': 42,
   'max_features': None,
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': 10,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.001,
   'ccp_alpha': 0.001},
  'test_mse': 106575.03780853433,
  'test_rmse': 326.45832476525135,
  'test_corr_coef': 0.9653413824999147,
  'pruner': 'NopPruner'},
 ('Gradient Boosting', 'PatientPruner'): {'best_score': 104595.41518900798,
  'best_params': {'loss': 'huber',
   'learning_rate': 0.2,
   'n_estimators': 500,
   'subsample': 1.0,
   'criterion': 'squared_error',
   'min_samples_split': 5,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 10,
   'min_impurity_decrease': 0.01,
   'init': None,
   'random_state': 42,
   'max_features': None,
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': 30,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': None,
   'tol': 0.0001,
   'ccp_alpha': 0.0},
  'test_mse': 104595.41518900798,
  'test_rmse': 323.4121444674086,
  'test_corr_coef': 0.965322863260212,
  'pruner': 'PatientPruner'},
 ('Gradient Boosting', 'PercentilePruner'): {'best_score': 99725.80067490121,
  'best_params': {'loss': 'huber',
   'learning_rate': 0.05,
   'n_estimators': 300,
   'subsample': 0.9,
   'criterion': 'friedman_mse',
   'min_samples_split': 10,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 7,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': None,
   'alpha': 0.1,
   'verbose': 0,
   'max_leaf_nodes': 50,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': None,
   'tol': 0.001,
   'ccp_alpha': 0.001},
  'test_mse': 99725.80067490121,
  'test_rmse': 315.79392121271303,
  'test_corr_coef': 0.9695611559059057,
  'pruner': 'PercentilePruner'},
 ('Gradient Boosting',
  'SuccessiveHalvingPruner'): {'best_score': 115388.14082603931, 'best_params': {'loss': 'absolute_error',
   'learning_rate': 0.2,
   'n_estimators': 700,
   'subsample': 0.9,
   'criterion': 'friedman_mse',
   'min_samples_split': 0.01,
   'min_samples_leaf': 5,
   'min_weight_fraction_leaf': 0.0,
   'max_depth': 5,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': None,
   'alpha': 0.5,
   'verbose': 0,
   'max_leaf_nodes': 30,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 10,
   'tol': 0.001,
   'ccp_alpha': 0.01}, 'test_mse': 115388.14082603931, 'test_rmse': 339.6882995130084, 'test_corr_coef': 0.9613694345764211, 'pruner': 'SuccessiveHalvingPruner'},
 ('Gradient Boosting', 'HyperbandPruner'): {'best_score': 94870.04457542315,
  'best_params': {'loss': 'absolute_error',
   'learning_rate': 0.2,
   'n_estimators': 200,
   'subsample': 0.5,
   'criterion': 'friedman_mse',
   'min_samples_split': 10,
   'min_samples_leaf': 5,
   'min_weight_fraction_leaf': 0.05,
   'max_depth': 7,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': 0.5,
   'alpha': 0.1,
   'verbose': 0,
   'max_leaf_nodes': 10,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': None,
   'tol': 0.001,
   'ccp_alpha': 0.0},
  'test_mse': 94870.04457542315,
  'test_rmse': 308.0098124661342,
  'test_corr_coef': 0.9693954848146131,
  'pruner': 'HyperbandPruner'},
 ('Gradient Boosting', 'ThresholdPruner'): {'best_score': 104617.67213635288,
  'best_params': {'loss': 'huber',
   'learning_rate': 0.1,
   'n_estimators': 700,
   'subsample': 0.9,
   'criterion': 'squared_error',
   'min_samples_split': 2,
   'min_samples_leaf': 0.01,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 7,
   'min_impurity_decrease': 0.01,
   'init': None,
   'random_state': 42,
   'max_features': None,
   'alpha': 0.9,
   'verbose': 0,
   'max_leaf_nodes': None,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 10,
   'tol': 0.0001,
   'ccp_alpha': 0.001},
  'test_mse': 104617.67213635288,
  'test_rmse': 323.4465522097165,
  'test_corr_coef': 0.9670218469145725,
  'pruner': 'ThresholdPruner'},
 ('Gradient Boosting', 'WilcoxonPruner'): {'best_score': 115965.93616321213,
  'best_params': {'loss': 'absolute_error',
   'learning_rate': 0.2,
   'n_estimators': 200,
   'subsample': 0.9,
   'criterion': 'friedman_mse',
   'min_samples_split': 10,
   'min_samples_leaf': 1,
   'min_weight_fraction_leaf': 0.01,
   'max_depth': 10,
   'min_impurity_decrease': 0.0,
   'init': None,
   'random_state': 42,
   'max_features': None,
   'alpha': 0.1,
   'verbose': 0,
   'max_leaf_nodes': None,
   'warm_start': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 20,
   'tol': 0.0001,
   'ccp_alpha': 0.0},
  'test_mse': 115965.93616321213,
  'test_rmse': 340.5377162124808,
  'test_corr_coef': 0.9661622534830681,
  'pruner': 'WilcoxonPruner'},
 ('XGBoost', 'MedianPruner'): {'best_score': 144897.269725111,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.1,
   'max_depth': 7,
   'min_child_weight': 3,
   'gamma': 0.5,
   'subsample': 0.8,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.9,
   'reg_alpha': 0.1,
   'reg_lambda': 10,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 144897.269725111,
  'test_rmse': 380.65373993317206,
  'test_corr_coef': 0.9645849926785167,
  'pruner': 'MedianPruner'},
 ('XGBoost', 'NopPruner'): {'best_score': 112489.26747933708,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.05,
   'max_depth': 5,
   'min_child_weight': 1,
   'gamma': 1,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.7,
   'reg_alpha': 0.1,
   'reg_lambda': 5,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 112489.26747933708,
  'test_rmse': 335.3941971461896,
  'test_corr_coef': 0.96564448358986,
  'pruner': 'NopPruner'},
 ('XGBoost', 'PatientPruner'): {'best_score': 126101.16516872347,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.01,
   'max_depth': 7,
   'min_child_weight': 1,
   'gamma': 0,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.5,
   'reg_alpha': 0.01,
   'reg_lambda': 5,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 126101.16516872347,
  'test_rmse': 355.1072586821107,
  'test_corr_coef': 0.9614123668357902,
  'pruner': 'PatientPruner'},
 ('XGBoost', 'PercentilePruner'): {'best_score': 136726.62651782745,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.01,
   'max_depth': 7,
   'min_child_weight': 1,
   'gamma': 0.1,
   'subsample': 0.5,
   'colsample_bytree': 0.7,
   'colsample_bylevel': 0.9,
   'reg_alpha': 0,
   'reg_lambda': 10,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 136726.62651782745,
  'test_rmse': 369.76563728641344,
  'test_corr_coef': 0.957646899373698,
  'pruner': 'PercentilePruner'},
 ('XGBoost', 'SuccessiveHalvingPruner'): {'best_score': 113753.5246155919,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.15,
   'max_depth': 5,
   'min_child_weight': 1,
   'gamma': 0.5,
   'subsample': 0.5,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.9,
   'reg_alpha': 0.1,
   'reg_lambda': 5,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 113753.5246155919,
  'test_rmse': 337.2736642781228,
  'test_corr_coef': 0.966771646445439,
  'pruner': 'SuccessiveHalvingPruner'},
 ('XGBoost', 'HyperbandPruner'): {'best_score': 133430.5131094733,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.01,
   'max_depth': 7,
   'min_child_weight': 1,
   'gamma': 0.1,
   'subsample': 0.5,
   'colsample_bytree': 0.7,
   'colsample_bylevel': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 10,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 133430.5131094733,
  'test_rmse': 365.2814163209967,
  'test_corr_coef': 0.9606698458763485,
  'pruner': 'HyperbandPruner'},
 ('XGBoost', 'ThresholdPruner'): {'best_score': 115799.52745518631,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.05,
   'max_depth': 7,
   'min_child_weight': 1,
   'gamma': 0,
   'subsample': 0.7,
   'colsample_bytree': 0.9,
   'colsample_bylevel': 0.7,
   'reg_alpha': 0.01,
   'reg_lambda': 10,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 115799.52745518631,
  'test_rmse': 340.2932962242811,
  'test_corr_coef': 0.9654423196285966,
  'pruner': 'ThresholdPruner'},
 ('XGBoost', 'WilcoxonPruner'): {'best_score': 123304.66533714374,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.01,
   'max_depth': 7,
   'min_child_weight': 1,
   'gamma': 0.5,
   'subsample': 0.5,
   'colsample_bytree': 0.7,
   'colsample_bylevel': 0.9,
   'reg_alpha': 0.01,
   'reg_lambda': 10,
   'objective': 'reg:squarederror',
   'random_state': 42,
   'n_jobs': -1},
  'test_mse': 123304.66533714374,
  'test_rmse': 351.14764036960827,
  'test_corr_coef': 0.9635628198182367,
  'pruner': 'WilcoxonPruner'},
 ('LightGBM', 'MedianPruner'): {'best_score': 86044.08662798398,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.05,
   'num_leaves': 31,
   'max_depth': 5,
   'min_child_samples': 5,
   'subsample': 0.8,
   'colsample_bytree': 0.5,
   'reg_alpha': 0.1,
   'reg_lambda': 10,
   'min_child_weight': 1e-05,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 86044.08662798398,
  'test_rmse': 293.332723418278,
  'test_corr_coef': 0.9714165057095582,
  'pruner': 'MedianPruner'},
 ('LightGBM', 'NopPruner'): {'best_score': 94477.59834052388,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.01,
   'num_leaves': 31,
   'max_depth': -1,
   'min_child_samples': 10,
   'subsample': 0.7,
   'colsample_bytree': 0.5,
   'reg_alpha': 1,
   'reg_lambda': 10,
   'min_child_weight': 1e-05,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 94477.59834052388,
  'test_rmse': 307.3720845173222,
  'test_corr_coef': 0.969908476703405,
  'pruner': 'NopPruner'},
 ('LightGBM', 'PatientPruner'): {'best_score': 87830.23792054132,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.01,
   'num_leaves': 31,
   'max_depth': 7,
   'min_child_samples': 1,
   'subsample': 0.6,
   'colsample_bytree': 0.7,
   'reg_alpha': 1,
   'reg_lambda': 10,
   'min_child_weight': 0.1,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 87830.23792054132,
  'test_rmse': 296.36166742772474,
  'test_corr_coef': 0.9721975978240425,
  'pruner': 'PatientPruner'},
 ('LightGBM', 'PercentilePruner'): {'best_score': 94715.31767890525,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.05,
   'num_leaves': 63,
   'max_depth': 5,
   'min_child_samples': 1,
   'subsample': 0.5,
   'colsample_bytree': 0.7,
   'reg_alpha': 1,
   'reg_lambda': 10,
   'min_child_weight': 0.1,
   'bagging_freq': 5,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 94715.31767890525,
  'test_rmse': 307.7585379463992,
  'test_corr_coef': 0.9691775251113111,
  'pruner': 'PercentilePruner'},
 ('LightGBM', 'SuccessiveHalvingPruner'): {'best_score': 86867.50262566945,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.01,
   'num_leaves': 15,
   'max_depth': -1,
   'min_child_samples': 5,
   'subsample': 0.8,
   'colsample_bytree': 0.5,
   'reg_alpha': 0.1,
   'reg_lambda': 10,
   'min_child_weight': 0.01,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 86867.50262566945,
  'test_rmse': 294.7329344095591,
  'test_corr_coef': 0.9720684448833871,
  'pruner': 'SuccessiveHalvingPruner'},
 ('LightGBM', 'HyperbandPruner'): {'best_score': 88709.00101436477,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.01,
   'num_leaves': 15,
   'max_depth': -1,
   'min_child_samples': 1,
   'subsample': 0.9,
   'colsample_bytree': 0.7,
   'reg_alpha': 1,
   'reg_lambda': 10,
   'min_child_weight': 0.001,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 88709.00101436477,
  'test_rmse': 297.84056307757135,
  'test_corr_coef': 0.9712796302011322,
  'pruner': 'HyperbandPruner'},
 ('LightGBM', 'ThresholdPruner'): {'best_score': 99979.74519447866,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.05,
   'num_leaves': 15,
   'max_depth': 3,
   'min_child_samples': 5,
   'subsample': 0.5,
   'colsample_bytree': 0.7,
   'reg_alpha': 1,
   'reg_lambda': 0.1,
   'min_child_weight': 1e-05,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 99979.74519447866,
  'test_rmse': 316.1957387354843,
  'test_corr_coef': 0.9671420731714029,
  'pruner': 'ThresholdPruner'},
 ('LightGBM', 'WilcoxonPruner'): {'best_score': 100736.29445203877,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.01,
   'num_leaves': 15,
   'max_depth': -1,
   'min_child_samples': 5,
   'subsample': 0.5,
   'colsample_bytree': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 1,
   'min_child_weight': 1e-05,
   'bagging_freq': 1,
   'objective': 'regression',
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 100736.29445203877,
  'test_rmse': 317.3898146633549,
  'test_corr_coef': 0.9693661922645916,
  'pruner': 'WilcoxonPruner'},
 ('GPBoost', 'MedianPruner'): {'best_score': 112096.46959308149,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.01,
   'max_depth': 3,
   'num_leaves': 31,
   'min_child_samples': 10,
   'subsample': 1.0,
   'colsample_bytree': 1.0,
   'reg_alpha': 1.0,
   'reg_lambda': 1.0,
   'min_child_weight': 0.01,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 112096.46959308149,
  'test_rmse': 334.80810861310016,
  'test_corr_coef': 0.9663622360328146,
  'pruner': 'MedianPruner'},
 ('GPBoost', 'NopPruner'): {'best_score': 111537.3357855164,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.01,
   'max_depth': 3,
   'num_leaves': 31,
   'min_child_samples': 5,
   'subsample': 0.8,
   'colsample_bytree': 0.9,
   'reg_alpha': 0,
   'reg_lambda': 0.5,
   'min_child_weight': 0.001,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 111537.3357855164,
  'test_rmse': 333.9720583903935,
  'test_corr_coef': 0.9658655126335507,
  'pruner': 'NopPruner'},
 ('GPBoost', 'PatientPruner'): {'best_score': 115032.42871913446,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.01,
   'max_depth': -1,
   'num_leaves': 63,
   'min_child_samples': 20,
   'subsample': 0.7,
   'colsample_bytree': 1.0,
   'reg_alpha': 0.5,
   'reg_lambda': 0.1,
   'min_child_weight': 1e-05,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 115032.42871913446,
  'test_rmse': 339.1643093238651,
  'test_corr_coef': 0.9641114404740005,
  'pruner': 'PatientPruner'},
 ('GPBoost', 'PercentilePruner'): {'best_score': 114200.00943677705,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.01,
   'max_depth': 3,
   'num_leaves': 31,
   'min_child_samples': 5,
   'subsample': 0.9,
   'colsample_bytree': 1.0,
   'reg_alpha': 0,
   'reg_lambda': 1.0,
   'min_child_weight': 0.01,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 114200.00943677705,
  'test_rmse': 337.9349189367341,
  'test_corr_coef': 0.9651040557662787,
  'pruner': 'PercentilePruner'},
 ('GPBoost', 'SuccessiveHalvingPruner'): {'best_score': 121675.81844833051,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.01,
   'max_depth': 3,
   'num_leaves': 15,
   'min_child_samples': 10,
   'subsample': 0.9,
   'colsample_bytree': 0.5,
   'reg_alpha': 0.5,
   'reg_lambda': 1.0,
   'min_child_weight': 0.01,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 121675.81844833051,
  'test_rmse': 348.820610698867,
  'test_corr_coef': 0.9629349493155991,
  'pruner': 'SuccessiveHalvingPruner'},
 ('GPBoost', 'HyperbandPruner'): {'best_score': 115913.92866273696,
  'best_params': {'n_estimators': 300,
   'learning_rate': 0.01,
   'max_depth': 7,
   'num_leaves': 31,
   'min_child_samples': 20,
   'subsample': 0.6,
   'colsample_bytree': 1.0,
   'reg_alpha': 0.5,
   'reg_lambda': 0.5,
   'min_child_weight': 0.1,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 115913.92866273696,
  'test_rmse': 340.4613467968676,
  'test_corr_coef': 0.9639397986834962,
  'pruner': 'HyperbandPruner'},
 ('GPBoost', 'ThresholdPruner'): {'best_score': 120416.85819599114,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.05,
   'max_depth': 3,
   'num_leaves': 31,
   'min_child_samples': 5,
   'subsample': 1.0,
   'colsample_bytree': 0.7,
   'reg_alpha': 0,
   'reg_lambda': 0.5,
   'min_child_weight': 0.01,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 120416.85819599114,
  'test_rmse': 347.0113228642419,
  'test_corr_coef': 0.9627972779246036,
  'pruner': 'ThresholdPruner'},
 ('GPBoost', 'WilcoxonPruner'): {'best_score': 114811.89688417579,
  'best_params': {'n_estimators': 400,
   'learning_rate': 0.01,
   'max_depth': 3,
   'num_leaves': 31,
   'min_child_samples': 5,
   'subsample': 0.9,
   'colsample_bytree': 1.0,
   'reg_alpha': 0.5,
   'reg_lambda': 1.0,
   'min_child_weight': 0.1,
   'random_state': 42,
   'n_jobs': -1,
   'verbose': -1},
  'test_mse': 114811.89688417579,
  'test_rmse': 338.8390427388435,
  'test_corr_coef': 0.9649777410550676,
  'pruner': 'WilcoxonPruner'},
 ('CatBoost', 'MedianPruner'): {'best_score': 101537.83907013081,
  'best_params': {'iterations': 200,
   'learning_rate': 0.03,
   'depth': 10,
   'l2_leaf_reg': 1,
   'border_count': 64,
   'min_data_in_leaf': 1,
   'rsm': 1.0,
   'bagging_temperature': 10,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 101537.83907013081,
  'test_rmse': 318.65002600051804,
  'test_corr_coef': 0.9666880340359085,
  'pruner': 'MedianPruner'},
 ('CatBoost', 'NopPruner'): {'best_score': 109091.92676281127,
  'best_params': {'iterations': 200,
   'learning_rate': 0.1,
   'depth': 10,
   'l2_leaf_reg': 5,
   'border_count': 64,
   'min_data_in_leaf': 10,
   'rsm': 0.6,
   'bagging_temperature': 1,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 109091.92676281127,
  'test_rmse': 330.2906701116628,
  'test_corr_coef': 0.9637561849388776,
  'pruner': 'NopPruner'},
 ('CatBoost', 'PatientPruner'): {'best_score': 111987.22701024539,
  'best_params': {'iterations': 200,
   'learning_rate': 0.1,
   'depth': 10,
   'l2_leaf_reg': 5,
   'border_count': 64,
   'min_data_in_leaf': 1,
   'rsm': 0.8,
   'bagging_temperature': 1,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 111987.22701024539,
  'test_rmse': 334.64492676603567,
  'test_corr_coef': 0.9630756672808098,
  'pruner': 'PatientPruner'},
 ('CatBoost', 'PercentilePruner'): {'best_score': 101537.83907013081,
  'best_params': {'iterations': 200,
   'learning_rate': 0.03,
   'depth': 10,
   'l2_leaf_reg': 1,
   'border_count': 64,
   'min_data_in_leaf': 20,
   'rsm': 1.0,
   'bagging_temperature': 1,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 101537.83907013081,
  'test_rmse': 318.65002600051804,
  'test_corr_coef': 0.9666880340359085,
  'pruner': 'PercentilePruner'},
 ('CatBoost', 'SuccessiveHalvingPruner'): {'best_score': 108300.3730298083,
  'best_params': {'iterations': 200,
   'learning_rate': 0.05,
   'depth': 10,
   'l2_leaf_reg': 3,
   'border_count': 64,
   'min_data_in_leaf': 10,
   'rsm': 0.6,
   'bagging_temperature': 0,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 108300.3730298083,
  'test_rmse': 329.09022019775716,
  'test_corr_coef': 0.9640724970413321,
  'pruner': 'SuccessiveHalvingPruner'},
 ('CatBoost', 'HyperbandPruner'): {'best_score': 118902.81904556698,
  'best_params': {'iterations': 500,
   'learning_rate': 0.03,
   'depth': 10,
   'l2_leaf_reg': 5,
   'border_count': 64,
   'min_data_in_leaf': 1,
   'rsm': 0.6,
   'bagging_temperature': 1,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 118902.81904556698,
  'test_rmse': 344.8228806874146,
  'test_corr_coef': 0.9603030735997221,
  'pruner': 'HyperbandPruner'},
 ('CatBoost', 'ThresholdPruner'): {'best_score': 106739.36867174642,
  'best_params': {'iterations': 200,
   'learning_rate': 0.03,
   'depth': 6,
   'l2_leaf_reg': 1,
   'border_count': 64,
   'min_data_in_leaf': 5,
   'rsm': 1.0,
   'bagging_temperature': 10,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 106739.36867174642,
  'test_rmse': 326.709915172078,
  'test_corr_coef': 0.9645246862965655,
  'pruner': 'ThresholdPruner'},
 ('CatBoost', 'WilcoxonPruner'): {'best_score': 112522.21218165623,
  'best_params': {'iterations': 1000,
   'learning_rate': 0.01,
   'depth': 10,
   'l2_leaf_reg': 1,
   'border_count': 64,
   'min_data_in_leaf': 5,
   'rsm': 0.8,
   'bagging_temperature': 10,
   'random_seed': 42,
   'verbose': 0},
  'test_mse': 112522.21218165623,
  'test_rmse': 335.44330695611774,
  'test_corr_coef': 0.9641808624579986,
  'pruner': 'WilcoxonPruner'},
 ('NGBoost', 'MedianPruner'): {'best_score': 139059.60517846112,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.03,
   'natural_gradient': True,
   'minibatch_frac': 0.7,
   'col_sample': 0.9,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 139059.60517846112,
  'test_rmse': 372.90696584867,
  'test_corr_coef': 0.9560637639116014,
  'pruner': 'MedianPruner'},
 ('NGBoost', 'NopPruner'): {'best_score': 144252.83582636862,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.01,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.7,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 144252.83582636862,
  'test_rmse': 379.80631356833527,
  'test_corr_coef': 0.9655551114748977,
  'pruner': 'NopPruner'},
 ('NGBoost', 'PatientPruner'): {'best_score': 129173.46426120309,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.05,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.9,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 129173.46426120309,
  'test_rmse': 359.4071010166648,
  'test_corr_coef': 0.9630813831659504,
  'pruner': 'PatientPruner'},
 ('NGBoost', 'PercentilePruner'): {'best_score': 170535.12440821258,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.01,
   'natural_gradient': True,
   'minibatch_frac': 1.0,
   'col_sample': 1.0,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 170535.12440821258,
  'test_rmse': 412.9589863512024,
  'test_corr_coef': 0.956531348075053,
  'pruner': 'PercentilePruner'},
 ('NGBoost', 'SuccessiveHalvingPruner'): {'best_score': 150107.8515952292,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.01,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.7,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 150107.8515952292,
  'test_rmse': 387.4375454124564,
  'test_corr_coef': 0.9648418504016317,
  'pruner': 'SuccessiveHalvingPruner'},
 ('NGBoost', 'HyperbandPruner'): {'best_score': 159522.47310411773,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.01,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.7,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 159522.47310411773,
  'test_rmse': 399.402645339409,
  'test_corr_coef': 0.964985616741838,
  'pruner': 'HyperbandPruner'},
 ('NGBoost', 'ThresholdPruner'): {'best_score': 167575.8434276094,
  'best_params': {'n_estimators': 200,
   'learning_rate': 0.01,
   'natural_gradient': True,
   'minibatch_frac': 0.9,
   'col_sample': 0.9,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 167575.8434276094,
  'test_rmse': 409.36028560133843,
  'test_corr_coef': 0.9636766208312282,
  'pruner': 'ThresholdPruner'},
 ('NGBoost', 'WilcoxonPruner'): {'best_score': 152421.19764256236,
  'best_params': {'n_estimators': 1000,
   'learning_rate': 0.05,
   'natural_gradient': True,
   'minibatch_frac': 0.5,
   'col_sample': 0.9,
   'Dist': ngboost.distns.normal.Normal,
   'Score': ngboost.scores.LogScore,
   'random_state': 42,
   'verbose': 0},
  'test_mse': 152421.19764256236,
  'test_rmse': 390.4115746780087,
  'test_corr_coef': 0.9569635429927064,
  'pruner': 'WilcoxonPruner'},
 ('TabNet', 'MedianPruner'): {'best_score': 320466.64675731334,
  'best_params': {'n_d': 64,
   'n_a': 8,
   'n_steps': 5,
   'gamma': 2.0,
   'lambda_sparse': 0.0001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'sparsemax',
   'n_shared': 2,
   'n_independent': 2,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 320466.64675731334,
  'test_rmse': 566.0977360468008,
  'test_corr_coef': 0.9590577932813041,
  'pruner': 'MedianPruner'},
 ('TabNet', 'NopPruner'): {'best_score': 262884.08066848107,
  'best_params': {'n_d': 32,
   'n_a': 64,
   'n_steps': 10,
   'gamma': 1.0,
   'lambda_sparse': 0.001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'sparsemax',
   'n_shared': 2,
   'n_independent': 2,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 262884.08066848107,
  'test_rmse': 512.7222256431654,
  'test_corr_coef': 0.9737017384987599,
  'pruner': 'NopPruner'},
 ('TabNet', 'PatientPruner'): {'best_score': 234676.12036911483,
  'best_params': {'n_d': 32,
   'n_a': 64,
   'n_steps': 10,
   'gamma': 1.5,
   'lambda_sparse': 0.001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'sparsemax',
   'n_shared': 2,
   'n_independent': 3,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 234676.12036911483,
  'test_rmse': 484.43381422967866,
  'test_corr_coef': 0.9577097500704689,
  'pruner': 'PatientPruner'},
 ('TabNet', 'PercentilePruner'): {'best_score': 356553.65101214184,
  'best_params': {'n_d': 64,
   'n_a': 64,
   'n_steps': 5,
   'gamma': 1.5,
   'lambda_sparse': 0.0001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'sparsemax',
   'n_shared': 1,
   'n_independent': 3,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 356553.65101214184,
  'test_rmse': 597.1211359616589,
  'test_corr_coef': 0.9440491878609079,
  'pruner': 'PercentilePruner'},
 ('TabNet', 'SuccessiveHalvingPruner'): {'best_score': 115329.83105861585,
  'best_params': {'n_d': 64,
   'n_a': 64,
   'n_steps': 10,
   'gamma': 1.0,
   'lambda_sparse': 0.001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'sparsemax',
   'n_shared': 2,
   'n_independent': 3,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 115329.83105861585,
  'test_rmse': 339.6024603247389,
  'test_corr_coef': 0.9695843406490969,
  'pruner': 'SuccessiveHalvingPruner'},
 ('TabNet', 'HyperbandPruner'): {'best_score': 234574.8695731652,
  'best_params': {'n_d': 32,
   'n_a': 32,
   'n_steps': 7,
   'gamma': 1.0,
   'lambda_sparse': 0.001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 3,
   'n_independent': 3,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 234574.8695731652,
  'test_rmse': 484.32929869373504,
  'test_corr_coef': 0.9585848067836743,
  'pruner': 'HyperbandPruner'},
 ('TabNet', 'ThresholdPruner'): {'best_score': 197564.61639049702,
  'best_params': {'n_d': 64,
   'n_a': 64,
   'n_steps': 10,
   'gamma': 1.5,
   'lambda_sparse': 0.001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 2,
   'n_independent': 3,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 197564.61639049702,
  'test_rmse': 444.48241403962993,
  'test_corr_coef': 0.9557576961290063,
  'pruner': 'ThresholdPruner'},
 ('TabNet', 'WilcoxonPruner'): {'best_score': 136359.22694099968,
  'best_params': {'n_d': 64,
   'n_a': 64,
   'n_steps': 10,
   'gamma': 1.0,
   'lambda_sparse': 0.0001,
   'optimizer_params': {'lr': 0.02},
   'mask_type': 'entmax',
   'n_shared': 3,
   'n_independent': 2,
   'scheduler_params': {'step_size': 10, 'gamma': 0.9},
   'scheduler_fn': torch.optim.lr_scheduler.StepLR,
   'seed': 42,
   'verbose': 0},
  'test_mse': 136359.22694099968,
  'test_rmse': 369.26850250325936,
  'test_corr_coef': 0.9572939602193796,
  'pruner': 'WilcoxonPruner'},
 ('HistGradientBoosting', 'MedianPruner'): {'best_score': 97200.1226064393,
  'best_params': {'learning_rate': 0.1,
   'max_iter': 500,
   'max_depth': None,
   'min_samples_leaf': 10,
   'max_leaf_nodes': 15,
   'l2_regularization': 0.1,
   'max_bins': 255,
   'early_stopping': True,
   'validation_fraction': 0.1,
   'n_iter_no_change': 5,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 97200.1226064393,
  'test_rmse': 311.7693419925046,
  'test_corr_coef': 0.9718101341850087,
  'pruner': 'MedianPruner'},
 ('HistGradientBoosting', 'NopPruner'): {'best_score': 121844.6068738407,
  'best_params': {'learning_rate': 0.01,
   'max_iter': 400,
   'max_depth': 3,
   'min_samples_leaf': 5,
   'max_leaf_nodes': None,
   'l2_regularization': 0.0,
   'max_bins': 255,
   'early_stopping': False,
   'validation_fraction': 0.1,
   'n_iter_no_change': 5,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 121844.6068738407,
  'test_rmse': 349.06246844059405,
  'test_corr_coef': 0.9607058811367111,
  'pruner': 'NopPruner'},
 ('HistGradientBoosting', 'PatientPruner'): {'best_score': 98723.42448097974,
  'best_params': {'learning_rate': 0.15,
   'max_iter': 400,
   'max_depth': 3,
   'min_samples_leaf': 10,
   'max_leaf_nodes': 63,
   'l2_regularization': 0.5,
   'max_bins': 255,
   'early_stopping': True,
   'validation_fraction': 0.1,
   'n_iter_no_change': 15,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 98723.42448097974,
  'test_rmse': 314.20283970865023,
  'test_corr_coef': 0.9672188283074789,
  'pruner': 'PatientPruner'},
 ('HistGradientBoosting',
  'PercentilePruner'): {'best_score': 98723.42448097974, 'best_params': {'learning_rate': 0.15,
   'max_iter': 500,
   'max_depth': 3,
   'min_samples_leaf': 10,
   'max_leaf_nodes': 63,
   'l2_regularization': 0.5,
   'max_bins': 255,
   'early_stopping': True,
   'validation_fraction': 0.1,
   'n_iter_no_change': 15,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0}, 'test_mse': 98723.42448097974, 'test_rmse': 314.20283970865023, 'test_corr_coef': 0.9672188283074789, 'pruner': 'PercentilePruner'},
 ('HistGradientBoosting',
  'SuccessiveHalvingPruner'): {'best_score': 112723.87184121429, 'best_params': {'learning_rate': 0.15,
   'max_iter': 100,
   'max_depth': None,
   'min_samples_leaf': 20,
   'max_leaf_nodes': 31,
   'l2_regularization': 0.0,
   'max_bins': 128,
   'early_stopping': True,
   'validation_fraction': 0.1,
   'n_iter_no_change': 5,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0}, 'test_mse': 112723.87184121429, 'test_rmse': 335.7437591992058, 'test_corr_coef': 0.963128045661365, 'pruner': 'SuccessiveHalvingPruner'},
 ('HistGradientBoosting',
  'HyperbandPruner'): {'best_score': 101709.92992105405, 'best_params': {'learning_rate': 0.05,
   'max_iter': 200,
   'max_depth': 3,
   'min_samples_leaf': 10,
   'max_leaf_nodes': 15,
   'l2_regularization': 1.0,
   'max_bins': 255,
   'early_stopping': True,
   'validation_fraction': 0.1,
   'n_iter_no_change': 10,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0}, 'test_mse': 101709.92992105405, 'test_rmse': 318.91994280862093, 'test_corr_coef': 0.9688923783881614, 'pruner': 'HyperbandPruner'},
 ('HistGradientBoosting', 'ThresholdPruner'): {'best_score': 98801.3336264882,
  'best_params': {'learning_rate': 0.15,
   'max_iter': 300,
   'max_depth': 5,
   'min_samples_leaf': 10,
   'max_leaf_nodes': None,
   'l2_regularization': 0.1,
   'max_bins': 255,
   'early_stopping': True,
   'validation_fraction': 0.1,
   'n_iter_no_change': 5,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 98801.3336264882,
  'test_rmse': 314.3267943184103,
  'test_corr_coef': 0.9700348280080318,
  'pruner': 'ThresholdPruner'},
 ('HistGradientBoosting', 'WilcoxonPruner'): {'best_score': 104614.56815861314,
  'best_params': {'learning_rate': 0.1,
   'max_iter': 500,
   'max_depth': None,
   'min_samples_leaf': 10,
   'max_leaf_nodes': 15,
   'l2_regularization': 0.5,
   'max_bins': 255,
   'early_stopping': True,
   'validation_fraction': 0.1,
   'n_iter_no_change': 15,
   'loss': 'squared_error',
   'random_state': 42,
   'verbose': 0},
  'test_mse': 104614.56815861314,
  'test_rmse': 323.4417538887228,
  'test_corr_coef': 0.9706866758128522,
  'pruner': 'WilcoxonPruner'},
 ('PGBM', 'MedianPruner'): {'best_score': 92073.78363045836,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.01,
   'max_leaves': 52,
   'min_split_gain': 1.0,
   'reg_lambda': 5.0,
   'feature_fraction': 0.9,
   'bagging_fraction': 0.5,
   'tree_correlation': 0.2,
   'min_data_in_leaf': 3,
   'max_bin': 128,
   'distribution': 'laplace'},
  'test_mse': 92073.78363045836,
  'test_rmse': 303.4366220983525,
  'test_corr_coef': 0.9693307274788633,
  'pruner': 'MedianPruner'},
 ('PGBM', 'NopPruner'): {'best_score': 91450.71937529996,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.05,
   'max_leaves': 42,
   'min_split_gain': 0.0,
   'reg_lambda': 0.1,
   'feature_fraction': 1.0,
   'bagging_fraction': 0.5,
   'tree_correlation': 0.2,
   'min_data_in_leaf': 10,
   'max_bin': 128,
   'distribution': 'normal'},
  'test_mse': 91450.71937529996,
  'test_rmse': 302.40819991412263,
  'test_corr_coef': 0.9696453678440501,
  'pruner': 'NopPruner'},
 ('PGBM', 'PatientPruner'): {'best_score': 88349.57707765196,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.01,
   'max_leaves': 40,
   'min_split_gain': 0.5,
   'reg_lambda': 5.0,
   'feature_fraction': 1.0,
   'bagging_fraction': 0.7,
   'tree_correlation': 0.0,
   'min_data_in_leaf': 10,
   'max_bin': 64,
   'distribution': 'normal'},
  'test_mse': 88349.57707765196,
  'test_rmse': 297.2365675310694,
  'test_corr_coef': 0.971513544690967,
  'pruner': 'PatientPruner'},
 ('PGBM', 'PercentilePruner'): {'best_score': 90954.58096772693,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.05,
   'max_leaves': 44,
   'min_split_gain': 0.5,
   'reg_lambda': 1.0,
   'feature_fraction': 1.0,
   'bagging_fraction': 0.5,
   'tree_correlation': 0.3,
   'min_data_in_leaf': 10,
   'max_bin': 64,
   'distribution': 'studentt'},
  'test_mse': 90954.58096772693,
  'test_rmse': 301.5867718712592,
  'test_corr_coef': 0.9710871704344548,
  'pruner': 'PercentilePruner'},
 ('PGBM', 'SuccessiveHalvingPruner'): {'best_score': 88349.46474146072,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.01,
   'max_leaves': 49,
   'min_split_gain': 0.0,
   'reg_lambda': 5.0,
   'feature_fraction': 1.0,
   'bagging_fraction': 0.7,
   'tree_correlation': 0.0,
   'min_data_in_leaf': 10,
   'max_bin': 64,
   'distribution': 'studentt'},
  'test_mse': 88349.46474146072,
  'test_rmse': 297.23637856335944,
  'test_corr_coef': 0.9715135648364278,
  'pruner': 'SuccessiveHalvingPruner'},
 ('PGBM', 'HyperbandPruner'): {'best_score': 90948.86630655531,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.05,
   'max_leaves': 28,
   'min_split_gain': 0.1,
   'reg_lambda': 1.0,
   'feature_fraction': 1.0,
   'bagging_fraction': 0.5,
   'tree_correlation': 0.3,
   'min_data_in_leaf': 10,
   'max_bin': 64,
   'distribution': 'studentt'},
  'test_mse': 90948.86630655531,
  'test_rmse': 301.57729739911673,
  'test_corr_coef': 0.9710884818595122,
  'pruner': 'HyperbandPruner'},
 ('PGBM', 'ThresholdPruner'): {'best_score': 88349.46474146072,
  'best_params': {'n_estimators': 500,
   'learning_rate': 0.01,
   'max_leaves': 57,
   'min_split_gain': 0.1,
   'reg_lambda': 5.0,
   'feature_fraction': 1.0,
   'bagging_fraction': 0.7,
   'tree_correlation': 0.1,
   'min_data_in_leaf': 10,
   'max_bin': 64,
   'distribution': 'studentt'},
  'test_mse': 88349.46474146072,
  'test_rmse': 297.23637856335944,
  'test_corr_coef': 0.9715135648364278,
  'pruner': 'ThresholdPruner'},
 ('PGBM', 'WilcoxonPruner'): {'best_score': 86773.2618088813,
  'best_params': {'n_estimators': 100,
   'learning_rate': 0.05,
   'max_leaves': 34,
   'min_split_gain': 0.0,
   'reg_lambda': 10.0,
   'feature_fraction': 1.0,
   'bagging_fraction': 0.7,
   'tree_correlation': 0.0,
   'min_data_in_leaf': 10,
   'max_bin': 64,
   'distribution': 'studentt'},
  'test_mse': 86773.2618088813,
  'test_rmse': 294.57301609088586,
  'test_corr_coef': 0.9713851074419442,
  'pruner': 'WilcoxonPruner'}}

# **Conformal Predictions with Lightgbm**

In [16]:
best_params = get_best_model_params(best_scores_autosampler, 'LightGBM')

In [17]:
conformal_predictions_NEXCP(
    model_class=LGBMRegressor,
    best_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="LightGBM",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/LightGBM.xlsx",
    alpha=0.05,
)

===== NEXCP RESULTS =====
NexCP Split - Coverage: 92.055% | Width: 471.324
NexCP Full - Coverage: 97.808% | Width: 1925.006
NexCP Jackknife+ aB - Coverage: 99.452% | Width: 3018.773
NexCP CV+ - Coverage: 97.808% | Width: 2901.802

              Strategy  Coverage        Width        RMSE          CWC
0          NexCP Split  0.920548   471.324452  293.332723  2526.567632
1           NexCP Full  0.978082  1925.006158  293.332723  1925.006158
2  NexCP Jackknife+ aB  0.994521  3018.773252  331.774523  3018.773252
3            NexCP CV+  0.978082  2901.801807  394.534183  2901.801807

In [18]:
conformal_predictions_online_super(
    model_class=LGBMRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="LightGBM",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/LightGBM.xlsx",
    alpha=0.05,
)

===== ONLINE CP RESULTS =====
               Strategy  Coverage        Width        RMSE          CWC
0          Online Split  0.978082  1925.006158  293.332723  1925.006158
1            Online CV+  0.972603  1614.118538  293.332723  1614.118538
2  Online Jackknife+ aB  0.994521  3033.911122  328.863754  3033.911122
3                 SAOCP  0.931507   612.148658  293.332723   654.076648
4                SF-OGD  0.978082  1970.150427  293.332723  1970.150427
5                  FACI  0.884932   670.586164  293.332723   747.749504
6            MFCS Split  0.978082  1925.006158  293.332723  1925.006158
7             MFCS Full  0.972603  1699.457794  325.905200  1699.457794

               Strategy  Coverage        Width        RMSE          CWC
0          Online Split  0.978082  1925.006158  293.332723  1925.006158
1            Online CV+  0.972603  1614.118538  293.332723  1614.118538
2  Online Jackknife+ aB  0.994521  3033.911122  328.863754  3033.911122
3                 SAOCP  0.931507   612.148658  293.332723   654.076648
4                SF-OGD  0.978082  1970.150427  293.332723  1970.150427
5                  FACI  0.884932   670.586164  293.332723   747.749504
6            MFCS Split  0.978082  1925.006158  293.332723  1925.006158
7             MFCS Full  0.972603  1699.457794  325.905200  1699.457794

In [19]:
conformal_predictions_COP(
    model_class=LGBMRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="LightGBM",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/LightGBM.xlsx",
    alpha=0.05,
)

===== CONFORMAL OPTIMISTIC PREDICTION (LightGBM) =====
Coverage : 97.808%
Avg Width: 1924.409
RMSE     : 293.333
Final q  : 961.992

  Strategy  Coverage        Width        RMSE  Alpha    LR  Scale
0      COP  0.978082  1924.408728  293.332723   0.05  0.05    0.5

In [20]:
conformal_predictions_EXTREME(
    model_class=LGBMRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="LightGBM",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/LightGBM.xlsx",
    alpha=0.05,
    calib_size=0.3,
)

===== EXTREME CONFORMAL PREDICTION (LightGBM) =====
Coverage : 100.000%
Width    : 188400.110
RMSE     : 318.326
q_extreme: 188400.110
u        : 2616.385
#Exceed. : 76

In [21]:
conformal_predictions_AlphaNet(
    model_class=LGBMRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="LightGBM",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/LightGBM.xlsx",
    alpha=0.05,
)

  [Info] n_calib=548 | alpha_min=0.0118
  [Step 2/9] Training base LightGBM model...
  [Step 2/9] Done in 0s
  [Step 3/9] Precomputing 548 LOO score vectors...

    LOO precompute:   0%|          | 0/548 [00:00<?, ?it/s]

  [Step 3/9] Done in 2s
  [Step 4/9] Training AlphaNet: 4 runs × 50 epochs

    Run 1/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 1/4 | Epoch 0/50 | Loss: 57412.3919 | Size: 57412.1545 | α̃: 0.0118 | ⏱ 0.89s/epoch | ETA: 3.1min
  λ=20.0 | Run 1/4 | Epoch 10/50 | Loss: 57411.0987 | Size: 57410.8613 | α̃: 0.0118 | ⏱ 0.17s/epoch | ETA: 47s
  λ=20.0 | Run 1/4 | Epoch 20/50 | Loss: 57325.1944 | Size: 57324.9562 | α̃: 0.0118 | ⏱ 0.17s/epoch | ETA: 38s
  λ=20.0 | Run 1/4 | Epoch 30/50 | Loss: 57413.6454 | Size: 57413.4076 | α̃: 0.0118 | ⏱ 0.23s/epoch | ETA: 38s
  λ=20.0 | Run 1/4 | Epoch 40/50 | Loss: 57413.5239 | Size: 57413.2854 | α̃: 0.0118 | ⏱ 0.18s/epoch | ETA: 35s
  λ=20.0 | Run 1/4 | Epoch 49/50 | Loss: 57365.6589 | Size: 57365.4206 | α̃: 0.0118 | ⏱ 0.18s/epoch | ETA: 32s
  ✓ Run 1 complete | Final loss: 57365.6589

    Run 2/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 2/4 | Epoch 0/50 | Loss: 594.9673 | Size: 574.9673 | α̃: 1.0000 | ⏱ 0.19s/epoch | ETA: 32s
  λ=20.0 | Run 2/4 | Epoch 10/50 | Loss: 594.9783 | Size: 574.9783 | α̃: 1.0000 | ⏱ 0.20s/epoch | ETA: 29s
  λ=20.0 | Run 2/4 | Epoch 20/50 | Loss: 594.9833 | Size: 574.9833 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 26s
  λ=20.0 | Run 2/4 | Epoch 30/50 | Loss: 594.9879 | Size: 574.9879 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 24s
  λ=20.0 | Run 2/4 | Epoch 40/50 | Loss: 594.9867 | Size: 574.9867 | α̃: 1.0000 | ⏱ 0.19s/epoch | ETA: 22s
  λ=20.0 | Run 2/4 | Epoch 49/50 | Loss: 594.9797 | Size: 574.9797 | α̃: 1.0000 | ⏱ 0.24s/epoch | ETA: 20s
  ✓ Run 2 complete | Final loss: 594.9797

    Run 3/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 3/4 | Epoch 0/50 | Loss: 594.9439 | Size: 574.9439 | α̃: 1.0000 | ⏱ 0.22s/epoch | ETA: 20s
  λ=20.0 | Run 3/4 | Epoch 10/50 | Loss: 594.9860 | Size: 574.9860 | α̃: 1.0000 | ⏱ 0.17s/epoch | ETA: 18s
  λ=20.0 | Run 3/4 | Epoch 20/50 | Loss: 594.9638 | Size: 574.9638 | α̃: 1.0000 | ⏱ 0.17s/epoch | ETA: 16s
  λ=20.0 | Run 3/4 | Epoch 30/50 | Loss: 594.9907 | Size: 574.9907 | α̃: 1.0000 | ⏱ 0.19s/epoch | ETA: 14s
  λ=20.0 | Run 3/4 | Epoch 40/50 | Loss: 594.8527 | Size: 574.8527 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 12s
  λ=20.0 | Run 3/4 | Epoch 49/50 | Loss: 594.9324 | Size: 574.9324 | α̃: 1.0000 | ⏱ 0.17s/epoch | ETA: 10s
  ✓ Run 3 complete | Final loss: 594.9324

    Run 4/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 4/4 | Epoch 0/50 | Loss: 594.9008 | Size: 574.9008 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 10s
  λ=20.0 | Run 4/4 | Epoch 10/50 | Loss: 594.8891 | Size: 574.8891 | α̃: 1.0000 | ⏱ 0.27s/epoch | ETA: 8s
  λ=20.0 | Run 4/4 | Epoch 20/50 | Loss: 594.9848 | Size: 574.9848 | α̃: 1.0000 | ⏱ 0.26s/epoch | ETA: 6s
  λ=20.0 | Run 4/4 | Epoch 30/50 | Loss: 594.9455 | Size: 574.9455 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 4s
  λ=20.0 | Run 4/4 | Epoch 40/50 | Loss: 594.9902 | Size: 574.9902 | α̃: 1.0000 | ⏱ 0.17s/epoch | ETA: 2s
  λ=20.0 | Run 4/4 | Epoch 49/50 | Loss: 594.9212 | Size: 574.9212 | α̃: 1.0000 | ⏱ 0.17s/epoch | ETA: 0s
  ✓ Run 4 complete | Final loss: 594.9212
  [Step 4/9] Training done in 40s
  [Step 5/9] Computing conformal intervals on test set...

=======================================================
  ALPHANET CONFORMAL (LightGBM)
=======================================================
  Learned α̃     : 1.0000
  Half-width (r) : 287.4721
  Coverage       : 91.781%
  Avg Width      : 574.9441
  RMSE           : 395.2125
  Total time     : 41s
    ├─ Precompute: 2s
    └─ Training  : 40s
=======================================================
  [Step 8/9] Generating plots...
  [Step 9/9] Saving to Excel...
  [Step 9/9] Saved!

  ✅ AlphaNet Conformal complete in 41s

,Strategy,Coverage,Width,RMSE,Alpha_nominal,Alpha_learned,Lambda_reg,Total_time_sec
0,AlphaNet Conformal,0.917808,574.944127,395.212481,0.05,1.0,20.0,41.19

# **Conformal Predictions with XGBoost**

In [22]:
best_params = get_best_model_params(best_scores_autosampler, 'XGBoost')

In [23]:
conformal_predictions_NEXCP(
    model_class=XGBRegressor,
    best_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="XGBoost",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/XGBoost.xlsx",
    alpha=0.05,
)

===== NEXCP RESULTS =====
NexCP Split - Coverage: 89.041% | Width: 381.869
NexCP Full - Coverage: 97.534% | Width: 1512.258
NexCP Jackknife+ aB - Coverage: 99.178% | Width: 2725.217
NexCP CV+ - Coverage: 96.164% | Width: 2835.553

              Strategy  Coverage        Width        RMSE          CWC
0          NexCP Split  0.890411   381.868927  335.394197  7895.915930
1           NexCP Full  0.975342  1512.257568  335.394197  1512.257568
2  NexCP Jackknife+ aB  0.991781  2725.217285  551.715296  2725.217285
3            NexCP CV+  0.961644  2835.552734  598.251139  2835.552734

In [24]:
conformal_predictions_online_super(
    model_class=XGBRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="XGBoost",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/XGBoost.xlsx",
    alpha=0.05,
)

===== ONLINE CP RESULTS =====
               Strategy  Coverage        Width        RMSE          CWC
0          Online Split  0.975342  1512.257739  335.394197  1512.257739
1            Online CV+  0.964384  1433.018927  335.394197  1433.018927
2  Online Jackknife+ aB  0.989041  2646.165039  519.045327  2646.165039
3                 SAOCP  0.920548   584.046572  335.394197   630.450272
4                SF-OGD  0.975342  1557.372318  335.394197  1557.372318
5                  FACI  0.865753   787.162542  335.394197   892.836418
6            MFCS Split  0.975342  1512.257739  335.394197  1512.257739
7             MFCS Full  0.958904  1510.892032  331.844967  1510.892032

               Strategy  Coverage        Width        RMSE          CWC
0          Online Split  0.975342  1512.257739  335.394197  1512.257739
1            Online CV+  0.964384  1433.018927  335.394197  1433.018927
2  Online Jackknife+ aB  0.989041  2646.165039  519.045327  2646.165039
3                 SAOCP  0.920548   584.046572  335.394197   630.450272
4                SF-OGD  0.975342  1557.372318  335.394197  1557.372318
5                  FACI  0.865753   787.162542  335.394197   892.836418
6            MFCS Split  0.975342  1512.257739  335.394197  1512.257739
7             MFCS Full  0.958904  1510.892032  331.844967  1510.892032

In [25]:
conformal_predictions_COP(
    model_class=XGBRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="XGBoost",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/XGBoost.xlsx",
    alpha=0.05,
)

===== CONFORMAL OPTIMISTIC PREDICTION (XGBoost) =====
Coverage : 97.534%
Avg Width: 1511.685
RMSE     : 335.394
Final q  : 755.668

  Strategy  Coverage        Width        RMSE  Alpha    LR  Scale
0      COP  0.975342  1511.685104  335.394197   0.05  0.05    0.5

In [26]:
conformal_predictions_EXTREME(
    model_class=XGBRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="XGBoost",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/XGBoost.xlsx",
    alpha=0.05,
    calib_size=0.3,
)

===== EXTREME CONFORMAL PREDICTION (XGBoost) =====
Coverage : 100.000%
Width    : 381721.783
RMSE     : 326.483
q_extreme: 381721.783
u        : 3404.986
#Exceed. : 90

In [27]:
conformal_predictions_AlphaNet(
    model_class=XGBRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="XGBoost",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/XGBoost.xlsx",
    alpha=0.05,
)

  [Info] n_calib=548 | alpha_min=0.0118
  [Step 2/9] Training base XGBoost model...
  [Step 2/9] Done in 0s
  [Step 3/9] Precomputing 548 LOO score vectors...

    LOO precompute:   0%|          | 0/548 [00:00<?, ?it/s]

  [Step 3/9] Done in 1s
  [Step 4/9] Training AlphaNet: 4 runs × 50 epochs

    Run 1/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 1/4 | Epoch 0/50 | Loss: 55398.1354 | Size: 55397.8974 | α̃: 0.0118 | ⏱ 0.20s/epoch | ETA: 44s
  λ=20.0 | Run 1/4 | Epoch 10/50 | Loss: 55397.8362 | Size: 55397.5981 | α̃: 0.0118 | ⏱ 0.17s/epoch | ETA: 35s
  λ=20.0 | Run 1/4 | Epoch 20/50 | Loss: 55351.7444 | Size: 55351.5067 | α̃: 0.0118 | ⏱ 0.18s/epoch | ETA: 33s
  λ=20.0 | Run 1/4 | Epoch 30/50 | Loss: 55399.5135 | Size: 55399.2754 | α̃: 0.0118 | ⏱ 0.24s/epoch | ETA: 32s
  λ=20.0 | Run 1/4 | Epoch 40/50 | Loss: 55399.3574 | Size: 55399.1200 | α̃: 0.0118 | ⏱ 0.29s/epoch | ETA: 33s
  λ=20.0 | Run 1/4 | Epoch 49/50 | Loss: 55352.5992 | Size: 55352.3615 | α̃: 0.0118 | ⏱ 0.17s/epoch | ETA: 30s
  ✓ Run 1 complete | Final loss: 55352.5992

    Run 2/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 2/4 | Epoch 0/50 | Loss: 574.7842 | Size: 554.7842 | α̃: 1.0000 | ⏱ 0.19s/epoch | ETA: 30s
  λ=20.0 | Run 2/4 | Epoch 10/50 | Loss: 574.7908 | Size: 554.7908 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 28s
  λ=20.0 | Run 2/4 | Epoch 20/50 | Loss: 574.8144 | Size: 554.8144 | α̃: 1.0000 | ⏱ 0.19s/epoch | ETA: 25s
  λ=20.0 | Run 2/4 | Epoch 30/50 | Loss: 574.8111 | Size: 554.8111 | α̃: 1.0000 | ⏱ 0.17s/epoch | ETA: 23s
  λ=20.0 | Run 2/4 | Epoch 40/50 | Loss: 574.8044 | Size: 554.8044 | α̃: 1.0000 | ⏱ 0.17s/epoch | ETA: 21s
  λ=20.0 | Run 2/4 | Epoch 49/50 | Loss: 574.8184 | Size: 554.8184 | α̃: 1.0000 | ⏱ 0.22s/epoch | ETA: 19s
  ✓ Run 2 complete | Final loss: 574.8184

    Run 3/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 3/4 | Epoch 0/50 | Loss: 574.7868 | Size: 554.7868 | α̃: 1.0000 | ⏱ 0.26s/epoch | ETA: 19s
  λ=20.0 | Run 3/4 | Epoch 10/50 | Loss: 574.8142 | Size: 554.8142 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 18s
  λ=20.0 | Run 3/4 | Epoch 20/50 | Loss: 574.8044 | Size: 554.8044 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 16s
  λ=20.0 | Run 3/4 | Epoch 30/50 | Loss: 574.8177 | Size: 554.8177 | α̃: 1.0000 | ⏱ 0.17s/epoch | ETA: 14s
  λ=20.0 | Run 3/4 | Epoch 40/50 | Loss: 574.5068 | Size: 554.5068 | α̃: 1.0000 | ⏱ 0.17s/epoch | ETA: 12s
  λ=20.0 | Run 3/4 | Epoch 49/50 | Loss: 574.7457 | Size: 554.7457 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 10s
  ✓ Run 3 complete | Final loss: 574.7457

    Run 4/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 4/4 | Epoch 0/50 | Loss: 574.7552 | Size: 554.7552 | α̃: 1.0000 | ⏱ 0.20s/epoch | ETA: 10s
  λ=20.0 | Run 4/4 | Epoch 10/50 | Loss: 574.7022 | Size: 554.7022 | α̃: 1.0000 | ⏱ 0.20s/epoch | ETA: 8s
  λ=20.0 | Run 4/4 | Epoch 20/50 | Loss: 574.8158 | Size: 554.8158 | α̃: 1.0000 | ⏱ 0.24s/epoch | ETA: 6s
  λ=20.0 | Run 4/4 | Epoch 30/50 | Loss: 574.7494 | Size: 554.7494 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 4s
  λ=20.0 | Run 4/4 | Epoch 40/50 | Loss: 574.8191 | Size: 554.8191 | α̃: 1.0000 | ⏱ 0.17s/epoch | ETA: 2s
  λ=20.0 | Run 4/4 | Epoch 49/50 | Loss: 574.7260 | Size: 554.7260 | α̃: 1.0000 | ⏱ 0.20s/epoch | ETA: 0s
  ✓ Run 4 complete | Final loss: 574.7260
  [Step 4/9] Training done in 39s
  [Step 5/9] Computing conformal intervals on test set...

=======================================================
  ALPHANET CONFORMAL (XGBoost)
=======================================================
  Learned α̃     : 1.0000
  Half-width (r) : 277.3874
  Coverage       : 89.863%
  Avg Width      : 554.7747
  RMSE           : 713.2222
  Total time     : 40s
    ├─ Precompute: 1s
    └─ Training  : 39s
=======================================================
  [Step 8/9] Generating plots...
  [Step 9/9] Saving to Excel...
  [Step 9/9] Saved!

  ✅ AlphaNet Conformal complete in 40s

,Strategy,Coverage,Width,RMSE,Alpha_nominal,Alpha_learned,Lambda_reg,Total_time_sec
0,AlphaNet Conformal,0.89863,554.774719,713.222161,0.05,1.0,20.0,40.22

# **Conformal Predictions with GPBoost**

In [28]:
best_params = get_best_model_params(best_scores_autosampler, 'GPBoost')

In [29]:
conformal_predictions_NEXCP(
    model_class=GPBoostRegressor,
    best_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GPBoost",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/GPBoost.xlsx",
    alpha=0.05,
)

===== NEXCP RESULTS =====
NexCP Split - Coverage: 92.603% | Width: 444.250
NexCP Full - Coverage: 96.986% | Width: 1939.049
NexCP Jackknife+ aB - Coverage: 99.178% | Width: 3747.320
NexCP CV+ - Coverage: 95.342% | Width: 4016.665

              Strategy  Coverage        Width        RMSE          CWC
0          NexCP Split  0.926027   444.250132  333.972058  1917.193398
1           NexCP Full  0.969863  1939.048561  333.972058  1939.048561
2  NexCP Jackknife+ aB  0.991781  3747.320350  435.164473  3747.320350
3            NexCP CV+  0.953425  4016.664978  701.412902  4016.664978

In [30]:
conformal_predictions_online_super(
    model_class=GPBoostRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GPBoost",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/GPBoost.xlsx",
    alpha=0.05,
)

===== ONLINE CP RESULTS =====
               Strategy  Coverage        Width        RMSE          CWC
0          Online Split  0.969863  1939.048561  333.972058  1939.048561
1            Online CV+  0.967123  1776.154519  333.972058  1776.154519
2  Online Jackknife+ aB  0.994521  3137.841539  426.607306  3137.841539
3                 SAOCP  0.936986   563.650855  333.972058   599.168580
4                SF-OGD  0.969863  1983.661153  333.972058  1983.661153
5                  FACI  0.873973   767.293918  333.972058   863.993973
6            MFCS Split  0.969863  1939.048561  333.972058  1939.048561
7             MFCS Full  0.961644  1813.829999  325.705093  1813.829999

               Strategy  Coverage        Width        RMSE          CWC
0          Online Split  0.969863  1939.048561  333.972058  1939.048561
1            Online CV+  0.967123  1776.154519  333.972058  1776.154519
2  Online Jackknife+ aB  0.994521  3137.841539  426.607306  3137.841539
3                 SAOCP  0.936986   563.650855  333.972058   599.168580
4                SF-OGD  0.969863  1983.661153  333.972058  1983.661153
5                  FACI  0.873973   767.293918  333.972058   863.993973
6            MFCS Split  0.969863  1939.048561  333.972058  1939.048561
7             MFCS Full  0.961644  1813.829999  325.705093  1813.829999

In [31]:
conformal_predictions_COP(
    model_class=GPBoostRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GPBoost",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/GPBoost.xlsx",
    alpha=0.05,
)

===== CONFORMAL OPTIMISTIC PREDICTION (GPBoost) =====
Coverage : 96.986%
Avg Width: 1938.611
RMSE     : 333.972
Final q  : 969.163

  Strategy  Coverage        Width        RMSE  Alpha    LR  Scale
0      COP  0.969863  1938.610632  333.972058   0.05  0.05    0.5

In [32]:
conformal_predictions_EXTREME(
    model_class=GPBoostRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GPBoost",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/GPBoost.xlsx",
    alpha=0.05,
    calib_size=0.3,
)

===== EXTREME CONFORMAL PREDICTION (GPBoost) =====
Coverage : 100.000%
Width    : 127111.722
RMSE     : 610.133
q_extreme: 127111.722
u        : 2714.570
#Exceed. : 76

In [33]:
conformal_predictions_AlphaNet(
    model_class=GPBoostRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GPBoost",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/GPBoost.xlsx",
    alpha=0.05,
)

  [Info] n_calib=548 | alpha_min=0.0118
  [Step 2/9] Training base GPBoost model...
  [Step 2/9] Done in 0s
  [Step 3/9] Precomputing 548 LOO score vectors...

    LOO precompute:   0%|          | 0/548 [00:00<?, ?it/s]

  [Step 3/9] Done in 3s
  [Step 4/9] Training AlphaNet: 4 runs × 50 epochs

    Run 1/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 1/4 | Epoch 0/50 | Loss: 56501.5979 | Size: 56501.3589 | α̃: 0.0118 | ⏱ 0.20s/epoch | ETA: 42s
  λ=20.0 | Run 1/4 | Epoch 10/50 | Loss: 56498.5579 | Size: 56498.3190 | α̃: 0.0118 | ⏱ 0.19s/epoch | ETA: 34s
  λ=20.0 | Run 1/4 | Epoch 20/50 | Loss: 56487.0668 | Size: 56486.8286 | α̃: 0.0118 | ⏱ 0.23s/epoch | ETA: 34s
  λ=20.0 | Run 1/4 | Epoch 30/50 | Loss: 56501.7932 | Size: 56501.5556 | α̃: 0.0118 | ⏱ 0.31s/epoch | ETA: 35s
  λ=20.0 | Run 1/4 | Epoch 40/50 | Loss: 56501.4269 | Size: 56501.1897 | α̃: 0.0118 | ⏱ 0.17s/epoch | ETA: 32s
  λ=20.0 | Run 1/4 | Epoch 49/50 | Loss: 56460.6619 | Size: 56460.4232 | α̃: 0.0118 | ⏱ 0.18s/epoch | ETA: 30s
  ✓ Run 1 complete | Final loss: 56460.6619

    Run 2/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 2/4 | Epoch 0/50 | Loss: 585.8547 | Size: 565.8547 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 30s
  λ=20.0 | Run 2/4 | Epoch 10/50 | Loss: 585.8562 | Size: 565.8562 | α̃: 1.0000 | ⏱ 0.17s/epoch | ETA: 27s
  λ=20.0 | Run 2/4 | Epoch 20/50 | Loss: 585.7766 | Size: 565.7766 | α̃: 1.0000 | ⏱ 0.19s/epoch | ETA: 25s
  λ=20.0 | Run 2/4 | Epoch 30/50 | Loss: 585.8566 | Size: 565.8566 | α̃: 1.0000 | ⏱ 0.17s/epoch | ETA: 23s
  λ=20.0 | Run 2/4 | Epoch 40/50 | Loss: 585.8576 | Size: 565.8576 | α̃: 1.0000 | ⏱ 0.23s/epoch | ETA: 21s
  λ=20.0 | Run 2/4 | Epoch 49/50 | Loss: 585.8593 | Size: 565.8593 | α̃: 1.0000 | ⏱ 0.29s/epoch | ETA: 20s
  ✓ Run 2 complete | Final loss: 585.8593

    Run 3/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 3/4 | Epoch 0/50 | Loss: 585.8361 | Size: 565.8361 | α̃: 1.0000 | ⏱ 0.24s/epoch | ETA: 20s
  λ=20.0 | Run 3/4 | Epoch 10/50 | Loss: 585.8591 | Size: 565.8591 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 18s
  λ=20.0 | Run 3/4 | Epoch 20/50 | Loss: 585.8501 | Size: 565.8501 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 15s
  λ=20.0 | Run 3/4 | Epoch 30/50 | Loss: 585.8604 | Size: 565.8604 | α̃: 1.0000 | ⏱ 0.17s/epoch | ETA: 13s
  λ=20.0 | Run 3/4 | Epoch 40/50 | Loss: 585.6765 | Size: 565.6765 | α̃: 1.0000 | ⏱ 0.19s/epoch | ETA: 11s
  λ=20.0 | Run 3/4 | Epoch 49/50 | Loss: 585.8354 | Size: 565.8354 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 10s
  ✓ Run 3 complete | Final loss: 585.8354

    Run 4/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 4/4 | Epoch 0/50 | Loss: 585.7548 | Size: 565.7548 | α̃: 1.0000 | ⏱ 0.19s/epoch | ETA: 9s
  λ=20.0 | Run 4/4 | Epoch 10/50 | Loss: 585.8139 | Size: 565.8139 | α̃: 1.0000 | ⏱ 0.26s/epoch | ETA: 8s
  λ=20.0 | Run 4/4 | Epoch 20/50 | Loss: 585.8600 | Size: 565.8600 | α̃: 1.0000 | ⏱ 0.19s/epoch | ETA: 6s
  λ=20.0 | Run 4/4 | Epoch 30/50 | Loss: 585.8137 | Size: 565.8137 | α̃: 1.0000 | ⏱ 0.17s/epoch | ETA: 4s
  λ=20.0 | Run 4/4 | Epoch 40/50 | Loss: 585.8573 | Size: 565.8573 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 2s
  λ=20.0 | Run 4/4 | Epoch 49/50 | Loss: 585.8337 | Size: 565.8337 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 0s
  ✓ Run 4 complete | Final loss: 585.8337
  [Step 4/9] Training done in 39s
  [Step 5/9] Computing conformal intervals on test set...

=======================================================
  ALPHANET CONFORMAL (GPBoost)
=======================================================
  Learned α̃     : 1.0000
  Half-width (r) : 282.9099
  Coverage       : 91.507%
  Avg Width      : 565.8198
  RMSE           : 891.3597
  Total time     : 42s
    ├─ Precompute: 3s
    └─ Training  : 39s
=======================================================
  [Step 8/9] Generating plots...
  [Step 9/9] Saving to Excel...
  [Step 9/9] Saved!

  ✅ AlphaNet Conformal complete in 42s

,Strategy,Coverage,Width,RMSE,Alpha_nominal,Alpha_learned,Lambda_reg,Total_time_sec
0,AlphaNet Conformal,0.915068,565.819784,891.359705,0.05,1.0,20.0,42.26

# **Conformal Predictions with NGBoost**

In [34]:
best_params = get_best_model_params(best_scores_autosampler, 'NGBoost')

In [35]:
conformal_predictions_NEXCP(
    model_class=NGBRegressor,
    best_params={**best_params, "Dist": Normal},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="NGBoost",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/NGBoost.xlsx",
    alpha=0.05,
)

===== NEXCP RESULTS =====
NexCP Split - Coverage: 90.685% | Width: 429.934
NexCP Full - Coverage: 93.973% | Width: 1388.543
NexCP Jackknife+ aB - Coverage: 98.630% | Width: 1668.453
NexCP CV+ - Coverage: 97.260% | Width: 3588.635

              Strategy  Coverage        Width        RMSE          CWC
0          NexCP Split  0.906849   429.933931  387.139580  4148.769188
1           NexCP Full  0.939726  1388.542884  485.894316  3709.439405
2  NexCP Jackknife+ aB  0.986301  1668.453355  531.025986  1668.453355
3            NexCP CV+  0.972603  3588.635103  553.596958  3588.635103

In [36]:
conformal_predictions_online_super(
    model_class=NGBRegressor,
    model_params={**best_params, "Dist": Normal},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="NGBoost",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/NGBoost.xlsx",
    alpha=0.05,
)

===== ONLINE CP RESULTS =====
               Strategy  Coverage        Width        RMSE          CWC
0          Online Split  0.956164  1513.620602  387.139580  1513.620602
1            Online CV+  0.956164  1430.112888  387.139580  1430.112888
2  Online Jackknife+ aB  0.989041  1752.481206  579.549300  1752.481206
3                 SAOCP  0.915068   618.607462  387.139580   671.146726
4                SF-OGD  0.961644  1558.114054  387.139580  1558.114054
5                  FACI  0.871233   764.228380  387.139580   862.635870
6            MFCS Split  0.956164  1513.620602  387.139580  1513.620602
7             MFCS Full  0.945205  1335.964278  426.644803  1409.167800

               Strategy  Coverage        Width        RMSE          CWC
0          Online Split  0.956164  1513.620602  387.139580  1513.620602
1            Online CV+  0.956164  1430.112888  387.139580  1430.112888
2  Online Jackknife+ aB  0.989041  1752.481206  579.549300  1752.481206
3                 SAOCP  0.915068   618.607462  387.139580   671.146726
4                SF-OGD  0.961644  1558.114054  387.139580  1558.114054
5                  FACI  0.871233   764.228380  387.139580   862.635870
6            MFCS Split  0.956164  1513.620602  387.139580  1513.620602
7             MFCS Full  0.945205  1335.964278  426.644803  1409.167800

In [37]:
conformal_predictions_COP(
    model_class=NGBRegressor,
    model_params={**best_params, "Dist": Normal},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="NGBoost",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/NGBoost.xlsx",
    alpha=0.05,
)

===== CONFORMAL OPTIMISTIC PREDICTION (NGBoost) =====
Coverage : 95.616%
Avg Width: 1513.335
RMSE     : 387.140
Final q  : 756.699

  Strategy  Coverage        Width       RMSE  Alpha    LR  Scale
0      COP  0.956164  1513.334591  387.13958   0.05  0.05    0.5

In [38]:
conformal_predictions_EXTREME(
    model_class=NGBRegressor,
    model_params={**best_params, "Dist": Normal},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="NGBoost",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/NGBoost.xlsx",
    alpha=0.05,
    calib_size=0.3,
)

===== EXTREME CONFORMAL PREDICTION (NGBoost) =====
Coverage : 100.000%
Width    : 1830671.141
RMSE     : 653.583
q_extreme: 1830671.141
u        : 882.805
#Exceed. : 127

In [39]:
conformal_predictions_AlphaNet(
    model_class=NGBRegressor,
    model_params={**best_params, "Dist": Normal},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="NGBoost",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/NGBoost.xlsx",
    alpha=0.05,
)

  [Info] n_calib=548 | alpha_min=0.0118
  [Step 2/9] Training base NGBoost model...
  [Step 2/9] Done in 2s
  [Step 3/9] Precomputing 548 LOO score vectors...

    LOO precompute:   0%|          | 0/548 [00:00<?, ?it/s]

  [Step 3/9] Done in 45s
  [Step 4/9] Training AlphaNet: 4 runs × 50 epochs

    Run 1/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 1/4 | Epoch 0/50 | Loss: 67585.5616 | Size: 67585.3273 | α̃: 0.0118 | ⏱ 0.19s/epoch | ETA: 40s
  λ=20.0 | Run 1/4 | Epoch 10/50 | Loss: 67581.2986 | Size: 67581.0642 | α̃: 0.0118 | ⏱ 0.18s/epoch | ETA: 34s
  λ=20.0 | Run 1/4 | Epoch 20/50 | Loss: 67505.1667 | Size: 67504.9323 | α̃: 0.0118 | ⏱ 0.19s/epoch | ETA: 33s
  λ=20.0 | Run 1/4 | Epoch 30/50 | Loss: 67585.9753 | Size: 67585.7409 | α̃: 0.0118 | ⏱ 0.26s/epoch | ETA: 32s
  λ=20.0 | Run 1/4 | Epoch 40/50 | Loss: 67585.9679 | Size: 67585.7331 | α̃: 0.0118 | ⏱ 0.29s/epoch | ETA: 33s
  λ=20.0 | Run 1/4 | Epoch 49/50 | Loss: 67555.8707 | Size: 67555.6363 | α̃: 0.0118 | ⏱ 0.20s/epoch | ETA: 30s
  ✓ Run 1 complete | Final loss: 67555.8707

    Run 2/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 2/4 | Epoch 0/50 | Loss: 696.8504 | Size: 676.8504 | α̃: 1.0000 | ⏱ 0.19s/epoch | ETA: 30s
  λ=20.0 | Run 2/4 | Epoch 10/50 | Loss: 696.8444 | Size: 676.8444 | α̃: 1.0000 | ⏱ 0.20s/epoch | ETA: 28s
  λ=20.0 | Run 2/4 | Epoch 20/50 | Loss: 696.8491 | Size: 676.8491 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 25s
  λ=20.0 | Run 2/4 | Epoch 30/50 | Loss: 696.8621 | Size: 676.8621 | α̃: 1.0000 | ⏱ 0.17s/epoch | ETA: 23s
  λ=20.0 | Run 2/4 | Epoch 40/50 | Loss: 696.8641 | Size: 676.8641 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 21s
  λ=20.0 | Run 2/4 | Epoch 49/50 | Loss: 696.8688 | Size: 676.8688 | α̃: 1.0000 | ⏱ 0.23s/epoch | ETA: 20s
  ✓ Run 2 complete | Final loss: 696.8688

    Run 3/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 3/4 | Epoch 0/50 | Loss: 696.7981 | Size: 676.7981 | α̃: 1.0000 | ⏱ 0.26s/epoch | ETA: 19s
  λ=20.0 | Run 3/4 | Epoch 10/50 | Loss: 696.8598 | Size: 676.8598 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 18s
  λ=20.0 | Run 3/4 | Epoch 20/50 | Loss: 696.8545 | Size: 676.8545 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 16s
  λ=20.0 | Run 3/4 | Epoch 30/50 | Loss: 696.8686 | Size: 676.8686 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 14s
  λ=20.0 | Run 3/4 | Epoch 40/50 | Loss: 696.7654 | Size: 676.7654 | α̃: 1.0000 | ⏱ 0.19s/epoch | ETA: 12s
  λ=20.0 | Run 3/4 | Epoch 49/50 | Loss: 696.7938 | Size: 676.7938 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 10s
  ✓ Run 3 complete | Final loss: 696.7938

    Run 4/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 4/4 | Epoch 0/50 | Loss: 696.6830 | Size: 676.6830 | α̃: 1.0000 | ⏱ 0.19s/epoch | ETA: 10s
  λ=20.0 | Run 4/4 | Epoch 10/50 | Loss: 696.8419 | Size: 676.8419 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 8s
  λ=20.0 | Run 4/4 | Epoch 20/50 | Loss: 696.8657 | Size: 676.8657 | α̃: 1.0000 | ⏱ 0.25s/epoch | ETA: 6s
  λ=20.0 | Run 4/4 | Epoch 30/50 | Loss: 696.8497 | Size: 676.8497 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 4s
  λ=20.0 | Run 4/4 | Epoch 40/50 | Loss: 696.8675 | Size: 676.8675 | α̃: 1.0000 | ⏱ 0.17s/epoch | ETA: 2s
  λ=20.0 | Run 4/4 | Epoch 49/50 | Loss: 696.7878 | Size: 676.7878 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 0s
  ✓ Run 4 complete | Final loss: 696.7878
  [Step 4/9] Training done in 40s
  [Step 5/9] Computing conformal intervals on test set...

=======================================================
  ALPHANET CONFORMAL (NGBoost)
=======================================================
  Learned α̃     : 1.0000
  Half-width (r) : 338.4055
  Coverage       : 92.055%
  Avg Width      : 676.8110
  RMSE           : 675.4472
  Total time     : 1.5min
    ├─ Precompute: 45s
    └─ Training  : 40s
=======================================================
  [Step 8/9] Generating plots...
  [Step 9/9] Saving to Excel...
  [Step 9/9] Saved!

  ✅ AlphaNet Conformal complete in 1.5min

,Strategy,Coverage,Width,RMSE,Alpha_nominal,Alpha_learned,Lambda_reg,Total_time_sec
0,AlphaNet Conformal,0.920548,676.811002,675.447242,0.05,1.0,20.0,87.41

# **Conformal Predictions with Gradient Boosting**

In [40]:
best_params = get_best_model_params(best_scores_autosampler, 'GradientBoosting')

In [41]:
conformal_predictions_NEXCP(
    model_class=GradientBoostingRegressor,
    best_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GradientBoosting",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/Gradient Boosting.xlsx",
    alpha=0.05,
)

===== NEXCP RESULTS =====
NexCP Split - Coverage: 90.411% | Width: 342.836
NexCP Full - Coverage: 97.534% | Width: 1891.317
NexCP Jackknife+ aB - Coverage: 99.726% | Width: 4520.529
NexCP CV+ - Coverage: 98.356% | Width: 2763.968

              Strategy  Coverage        Width        RMSE          CWC
0          NexCP Split  0.904110   342.836279  308.009812  3743.662072
1           NexCP Full  0.975342  1891.317346  308.009812  1891.317346
2  NexCP Jackknife+ aB  0.997260  4520.529457  360.622581  4520.529457
3            NexCP CV+  0.983562  2763.967577  363.718517  2763.967577

In [42]:
conformal_predictions_online_super(
    model_class=GradientBoostingRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GradientBoosting",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/Gradient Boosting.xlsx",
    alpha=0.05,
)

===== ONLINE CP RESULTS =====
               Strategy  Coverage        Width        RMSE          CWC
0          Online Split  0.975342  1891.317346  308.009812  1891.317346
1            Online CV+  0.972603  1655.846152  308.009812  1655.846152
2  Online Jackknife+ aB  0.997260  4885.839528  371.204114  4885.839528
3                 SAOCP  0.920548   450.485431  308.009812   486.277424
4                SF-OGD  0.975342  1936.772928  308.009812  1936.772928
5                  FACI  0.904110   576.240197  308.009812   631.496106
6            MFCS Split  0.975342  1891.317346  308.009812  1891.317346
7             MFCS Full  0.961644  1912.294022  417.334724  1912.294022

               Strategy  Coverage        Width        RMSE          CWC
0          Online Split  0.975342  1891.317346  308.009812  1891.317346
1            Online CV+  0.972603  1655.846152  308.009812  1655.846152
2  Online Jackknife+ aB  0.997260  4885.839528  371.204114  4885.839528
3                 SAOCP  0.920548   450.485431  308.009812   486.277424
4                SF-OGD  0.975342  1936.772928  308.009812  1936.772928
5                  FACI  0.904110   576.240197  308.009812   631.496106
6            MFCS Split  0.975342  1891.317346  308.009812  1891.317346
7             MFCS Full  0.961644  1912.294022  417.334724  1912.294022

In [43]:
conformal_predictions_COP(
    model_class=GradientBoostingRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GradientBoosting",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/Gradient Boosting.xlsx",
    alpha=0.05,
)

===== CONFORMAL OPTIMISTIC PREDICTION (GradientBoosting) =====
Coverage : 97.534%
Avg Width: 1890.689
RMSE     : 308.010
Final q  : 945.197

  Strategy  Coverage        Width        RMSE  Alpha    LR  Scale
0      COP  0.975342  1890.689442  308.009812   0.05  0.05    0.5

In [44]:
conformal_predictions_EXTREME(
    model_class=GradientBoostingRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GradientBoosting",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/Gradient Boosting.xlsx",
    alpha=0.05,
    calib_size=0.3,
)

===== EXTREME CONFORMAL PREDICTION (GradientBoosting) =====
Coverage : 100.000%
Width    : 45589093273.658
RMSE     : 402.283
q_extreme: 45589093273.658
u        : 1118.029
#Exceed. : 163

In [45]:
conformal_predictions_AlphaNet(
    model_class=GradientBoostingRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="GradientBoosting",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/Gradient Boosting.xlsx",
    alpha=0.05,
)

  [Info] n_calib=548 | alpha_min=0.0118
  [Step 2/9] Training base GradientBoosting model...
  [Step 2/9] Done in 1s
  [Step 3/9] Precomputing 548 LOO score vectors...

    LOO precompute:   0%|          | 0/548 [00:00<?, ?it/s]

  [Step 3/9] Done in 2s
  [Step 4/9] Training AlphaNet: 4 runs × 50 epochs

    Run 1/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 1/4 | Epoch 0/50 | Loss: 63723.8010 | Size: 63723.5627 | α̃: 0.0118 | ⏱ 0.19s/epoch | ETA: 40s
  λ=20.0 | Run 1/4 | Epoch 10/50 | Loss: 63723.5189 | Size: 63723.2802 | α̃: 0.0118 | ⏱ 0.20s/epoch | ETA: 35s
  λ=20.0 | Run 1/4 | Epoch 20/50 | Loss: 63548.1753 | Size: 63547.9358 | α̃: 0.0118 | ⏱ 0.25s/epoch | ETA: 34s
  λ=20.0 | Run 1/4 | Epoch 30/50 | Loss: 63724.4297 | Size: 63724.1908 | α̃: 0.0118 | ⏱ 0.25s/epoch | ETA: 35s
  λ=20.0 | Run 1/4 | Epoch 40/50 | Loss: 63724.5538 | Size: 63724.3155 | α̃: 0.0118 | ⏱ 0.19s/epoch | ETA: 32s
  λ=20.0 | Run 1/4 | Epoch 49/50 | Loss: 63678.4696 | Size: 63678.2324 | α̃: 0.0118 | ⏱ 0.17s/epoch | ETA: 30s
  ✓ Run 1 complete | Final loss: 63678.4696

    Run 2/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 2/4 | Epoch 0/50 | Loss: 658.0835 | Size: 638.0835 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 30s
  λ=20.0 | Run 2/4 | Epoch 10/50 | Loss: 658.1742 | Size: 638.1742 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 27s
  λ=20.0 | Run 2/4 | Epoch 20/50 | Loss: 658.1930 | Size: 638.1930 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 25s
  λ=20.0 | Run 2/4 | Epoch 30/50 | Loss: 658.1916 | Size: 638.1916 | α̃: 1.0000 | ⏱ 0.19s/epoch | ETA: 23s
  λ=20.0 | Run 2/4 | Epoch 40/50 | Loss: 658.1941 | Size: 638.1941 | α̃: 1.0000 | ⏱ 0.24s/epoch | ETA: 21s
  λ=20.0 | Run 2/4 | Epoch 49/50 | Loss: 658.1941 | Size: 638.1941 | α̃: 1.0000 | ⏱ 0.30s/epoch | ETA: 20s
  ✓ Run 2 complete | Final loss: 658.1941

    Run 3/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 3/4 | Epoch 0/50 | Loss: 658.1563 | Size: 638.1563 | α̃: 1.0000 | ⏱ 0.23s/epoch | ETA: 20s
  λ=20.0 | Run 3/4 | Epoch 10/50 | Loss: 658.1859 | Size: 638.1859 | α̃: 1.0000 | ⏱ 0.19s/epoch | ETA: 18s
  λ=20.0 | Run 3/4 | Epoch 20/50 | Loss: 658.1653 | Size: 638.1653 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 15s
  λ=20.0 | Run 3/4 | Epoch 30/50 | Loss: 658.1958 | Size: 638.1958 | α̃: 1.0000 | ⏱ 0.17s/epoch | ETA: 13s
  λ=20.0 | Run 3/4 | Epoch 40/50 | Loss: 657.9091 | Size: 637.9091 | α̃: 1.0000 | ⏱ 0.17s/epoch | ETA: 11s
  λ=20.0 | Run 3/4 | Epoch 49/50 | Loss: 658.1880 | Size: 638.1880 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 10s
  ✓ Run 3 complete | Final loss: 658.1880

    Run 4/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 4/4 | Epoch 0/50 | Loss: 658.1730 | Size: 638.1730 | α̃: 1.0000 | ⏱ 0.19s/epoch | ETA: 9s
  λ=20.0 | Run 4/4 | Epoch 10/50 | Loss: 658.1877 | Size: 638.1877 | α̃: 1.0000 | ⏱ 0.26s/epoch | ETA: 8s
  λ=20.0 | Run 4/4 | Epoch 20/50 | Loss: 658.1899 | Size: 638.1899 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 6s
  λ=20.0 | Run 4/4 | Epoch 30/50 | Loss: 658.1904 | Size: 638.1904 | α̃: 1.0000 | ⏱ 0.17s/epoch | ETA: 4s
  λ=20.0 | Run 4/4 | Epoch 40/50 | Loss: 658.1957 | Size: 638.1957 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 2s
  λ=20.0 | Run 4/4 | Epoch 49/50 | Loss: 658.1858 | Size: 638.1858 | α̃: 1.0000 | ⏱ 0.19s/epoch | ETA: 0s
  ✓ Run 4 complete | Final loss: 658.1858
  [Step 4/9] Training done in 39s
  [Step 5/9] Computing conformal intervals on test set...

=======================================================
  ALPHANET CONFORMAL (GradientBoosting)
=======================================================
  Learned α̃     : 1.0000
  Half-width (r) : 319.0698
  Coverage       : 93.699%
  Avg Width      : 638.1397
  RMSE           : 439.0284
  Total time     : 42s
    ├─ Precompute: 2s
    └─ Training  : 39s
=======================================================
  [Step 8/9] Generating plots...
  [Step 9/9] Saving to Excel...
  [Step 9/9] Saved!

  ✅ AlphaNet Conformal complete in 42s

,Strategy,Coverage,Width,RMSE,Alpha_nominal,Alpha_learned,Lambda_reg,Total_time_sec
0,AlphaNet Conformal,0.936986,638.139659,439.028354,0.05,1.0,20.0,41.52

# **Conformal Predictions with CatBoost**

In [46]:
best_params = get_best_model_params(best_scores_autosampler, 'CatBoost')

In [47]:
conformal_predictions_NEXCP(
    model_class=CatBoostRegressor,
    best_params={**best_params, "verbose": False},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="CatBoost",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/CatBoost.xlsx",
    alpha=0.05,
)

===== NEXCP RESULTS =====
NexCP Split - Coverage: 90.137% | Width: 403.201
NexCP Full - Coverage: 97.808% | Width: 2322.019
NexCP Jackknife+ aB - Coverage: 99.452% | Width: 2805.545
NexCP CV+ - Coverage: 98.630% | Width: 3435.510

              Strategy  Coverage        Width        RMSE          CWC
0          NexCP Split  0.901370   403.201161  318.650026  4990.022051
1           NexCP Full  0.978082  2322.018806  318.650026  2322.018806
2  NexCP Jackknife+ aB  0.994521  2805.545278  326.105875  2805.545278
3            NexCP CV+  0.986301  3435.510450  345.271559  3435.510450

In [48]:
conformal_predictions_online_super(
    model_class=CatBoostRegressor,
    model_params={**best_params, "verbose": False},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="CatBoost",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/CatBoost.xlsx",
    alpha=0.05,
)

===== ONLINE CP RESULTS =====
               Strategy  Coverage        Width        RMSE          CWC
0          Online Split  0.978082  2322.018806  318.650026  2322.018806
1            Online CV+  0.975342  1918.016560  318.650026  1918.016560
2  Online Jackknife+ aB  0.994521  2801.143014  309.497407  2801.143014
3                 SAOCP  0.917808   533.741293  318.650026   577.610440
4                SF-OGD  0.978082  2367.520140  318.650026  2367.520140
5                  FACI  0.912329   730.803575  318.650026   794.874025
6            MFCS Split  0.978082  2322.018806  318.650026  2322.018806
7             MFCS Full  0.972603  1915.581218  335.922892  1915.581218

               Strategy  Coverage        Width        RMSE          CWC
0          Online Split  0.978082  2322.018806  318.650026  2322.018806
1            Online CV+  0.975342  1918.016560  318.650026  1918.016560
2  Online Jackknife+ aB  0.994521  2801.143014  309.497407  2801.143014
3                 SAOCP  0.917808   533.741293  318.650026   577.610440
4                SF-OGD  0.978082  2367.520140  318.650026  2367.520140
5                  FACI  0.912329   730.803575  318.650026   794.874025
6            MFCS Split  0.978082  2322.018806  318.650026  2322.018806
7             MFCS Full  0.972603  1915.581218  335.922892  1915.581218

In [49]:
conformal_predictions_COP(
    model_class=CatBoostRegressor,
    model_params={**best_params, "verbose": False},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="CatBoost",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/CatBoost.xlsx",
    alpha=0.05,
)

===== CONFORMAL OPTIMISTIC PREDICTION (CatBoost) =====
Coverage : 97.808%
Avg Width: 2321.356
RMSE     : 318.650
Final q  : 1160.498

  Strategy  Coverage        Width        RMSE  Alpha    LR  Scale
0      COP  0.978082  2321.355696  318.650026   0.05  0.05    0.5

In [50]:
conformal_predictions_EXTREME(
    model_class=CatBoostRegressor,
    model_params={**best_params, "verbose": False},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="CatBoost",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/CatBoost.xlsx",
    alpha=0.05,
    calib_size=0.3,
)

===== EXTREME CONFORMAL PREDICTION (CatBoost) =====
Coverage : 100.000%
Width    : 384387.410
RMSE     : 354.928
q_extreme: 384387.410
u        : 1653.807
#Exceed. : 88

In [51]:
conformal_predictions_AlphaNet(
    model_class=CatBoostRegressor,
    model_params={**best_params, "verbose": False},
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="CatBoost",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/CatBoost.xlsx",
    alpha=0.05,
)

  [Info] n_calib=548 | alpha_min=0.0118
  [Step 2/9] Training base CatBoost model...
  [Step 2/9] Done in 0s
  [Step 3/9] Precomputing 548 LOO score vectors...

    LOO precompute:   0%|          | 0/548 [00:00<?, ?it/s]

  [Step 3/9] Done in 2s
  [Step 4/9] Training AlphaNet: 4 runs × 50 epochs

    Run 1/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 1/4 | Epoch 0/50 | Loss: 63097.2984 | Size: 63097.0610 | α̃: 0.0118 | ⏱ 0.26s/epoch | ETA: 54s
  λ=20.0 | Run 1/4 | Epoch 10/50 | Loss: 63094.6621 | Size: 63094.4236 | α̃: 0.0118 | ⏱ 0.18s/epoch | ETA: 46s
  λ=20.0 | Run 1/4 | Epoch 20/50 | Loss: 63053.7708 | Size: 63053.5323 | α̃: 0.0118 | ⏱ 0.22s/epoch | ETA: 39s
  λ=20.0 | Run 1/4 | Epoch 30/50 | Loss: 63098.4247 | Size: 63098.1860 | α̃: 0.0118 | ⏱ 0.18s/epoch | ETA: 35s
  λ=20.0 | Run 1/4 | Epoch 40/50 | Loss: 63098.4210 | Size: 63098.1825 | α̃: 0.0118 | ⏱ 0.18s/epoch | ETA: 32s
  λ=20.0 | Run 1/4 | Epoch 49/50 | Loss: 63070.2834 | Size: 63070.0449 | α̃: 0.0118 | ⏱ 0.18s/epoch | ETA: 29s
  ✓ Run 1 complete | Final loss: 63070.2834

    Run 2/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 2/4 | Epoch 0/50 | Loss: 651.9024 | Size: 631.9024 | α̃: 1.0000 | ⏱ 0.19s/epoch | ETA: 29s
  λ=20.0 | Run 2/4 | Epoch 10/50 | Loss: 651.9140 | Size: 631.9140 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 27s
  λ=20.0 | Run 2/4 | Epoch 20/50 | Loss: 651.9160 | Size: 631.9160 | α̃: 1.0000 | ⏱ 0.24s/epoch | ETA: 26s
  λ=20.0 | Run 2/4 | Epoch 30/50 | Loss: 651.9239 | Size: 631.9239 | α̃: 1.0000 | ⏱ 0.17s/epoch | ETA: 24s
  λ=20.0 | Run 2/4 | Epoch 40/50 | Loss: 651.9213 | Size: 631.9213 | α̃: 1.0000 | ⏱ 0.19s/epoch | ETA: 22s
  λ=20.0 | Run 2/4 | Epoch 49/50 | Loss: 651.9216 | Size: 631.9216 | α̃: 1.0000 | ⏱ 0.17s/epoch | ETA: 20s
  ✓ Run 2 complete | Final loss: 651.9216

    Run 3/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 3/4 | Epoch 0/50 | Loss: 651.8864 | Size: 631.8864 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 20s
  λ=20.0 | Run 3/4 | Epoch 10/50 | Loss: 651.9213 | Size: 631.9213 | α̃: 1.0000 | ⏱ 0.17s/epoch | ETA: 17s
  λ=20.0 | Run 3/4 | Epoch 20/50 | Loss: 651.9063 | Size: 631.9063 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 15s
  λ=20.0 | Run 3/4 | Epoch 30/50 | Loss: 651.9245 | Size: 631.9245 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 13s
  λ=20.0 | Run 3/4 | Epoch 40/50 | Loss: 651.6051 | Size: 631.6051 | α̃: 1.0000 | ⏱ 0.23s/epoch | ETA: 12s
  λ=20.0 | Run 3/4 | Epoch 49/50 | Loss: 651.8628 | Size: 631.8628 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 10s
  ✓ Run 3 complete | Final loss: 651.8628

    Run 4/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 4/4 | Epoch 0/50 | Loss: 651.8728 | Size: 631.8728 | α̃: 1.0000 | ⏱ 0.19s/epoch | ETA: 10s
  λ=20.0 | Run 4/4 | Epoch 10/50 | Loss: 651.8244 | Size: 631.8244 | α̃: 1.0000 | ⏱ 0.17s/epoch | ETA: 8s
  λ=20.0 | Run 4/4 | Epoch 20/50 | Loss: 651.9225 | Size: 631.9225 | α̃: 1.0000 | ⏱ 0.19s/epoch | ETA: 6s
  λ=20.0 | Run 4/4 | Epoch 30/50 | Loss: 651.8949 | Size: 631.8949 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 4s
  λ=20.0 | Run 4/4 | Epoch 40/50 | Loss: 651.9256 | Size: 631.9256 | α̃: 1.0000 | ⏱ 0.17s/epoch | ETA: 2s
  λ=20.0 | Run 4/4 | Epoch 49/50 | Loss: 651.8487 | Size: 631.8487 | α̃: 1.0000 | ⏱ 0.26s/epoch | ETA: 0s
  ✓ Run 4 complete | Final loss: 651.8487
  [Step 4/9] Training done in 39s
  [Step 5/9] Computing conformal intervals on test set...

=======================================================
  ALPHANET CONFORMAL (CatBoost)
=======================================================
  Learned α̃     : 1.0000
  Half-width (r) : 315.9351
  Coverage       : 90.959%
  Avg Width      : 631.8703
  RMSE           : 417.9207
  Total time     : 41s
    ├─ Precompute: 2s
    └─ Training  : 39s
=======================================================
  [Step 8/9] Generating plots...
  [Step 9/9] Saving to Excel...
  [Step 9/9] Saved!

  ✅ AlphaNet Conformal complete in 41s

,Strategy,Coverage,Width,RMSE,Alpha_nominal,Alpha_learned,Lambda_reg,Total_time_sec
0,AlphaNet Conformal,0.909589,631.8703,417.920733,0.05,1.0,20.0,41.05

# **Conformal Predictions with HistGradientBoosting**

In [52]:
best_params = get_best_model_params(best_scores_autosampler, 'HGBR')

In [53]:
conformal_predictions_NEXCP(
    model_class=HistGradientBoostingRegressor,
    best_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="HGBR",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/HGBM.xlsx",
    alpha=0.05,
)

===== NEXCP RESULTS =====
NexCP Split - Coverage: 90.685% | Width: 368.674
NexCP Full - Coverage: 96.986% | Width: 1908.645
NexCP Jackknife+ aB - Coverage: 99.726% | Width: 4074.878
NexCP CV+ - Coverage: 98.904% | Width: 3957.616

              Strategy  Coverage        Width        RMSE          CWC
0          NexCP Split  0.906849   368.673813  311.769342  3557.622337
1           NexCP Full  0.969863  1908.645042  311.769342  1908.645042
2  NexCP Jackknife+ aB  0.997260  4074.878183  349.770090  4074.878183
3            NexCP CV+  0.989041  3957.616328  371.836137  3957.616328

In [54]:
conformal_predictions_online_super(
    model_class=HistGradientBoostingRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="HGBR",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/HGBM.xlsx",
    alpha=0.05,
)

===== ONLINE CP RESULTS =====
               Strategy  Coverage        Width        RMSE          CWC
0          Online Split  0.969863  1908.645042  311.769342  1908.645042
1            Online CV+  0.969863  1762.715954  311.769342  1762.715954
2  Online Jackknife+ aB  0.997260  3707.518105  331.040137  3707.518105
3                 SAOCP  0.923288   597.594852  311.769342   643.437745
4                SF-OGD  0.972603  1953.713059  311.769342  1953.713059
5                  FACI  0.890411   652.584086  311.769342   724.100151
6            MFCS Split  0.969863  1908.645042  311.769342  1908.645042
7             MFCS Full  0.961644  1954.526647  467.281839  1954.526647

               Strategy  Coverage        Width        RMSE          CWC
0          Online Split  0.969863  1908.645042  311.769342  1908.645042
1            Online CV+  0.969863  1762.715954  311.769342  1762.715954
2  Online Jackknife+ aB  0.997260  3707.518105  331.040137  3707.518105
3                 SAOCP  0.923288   597.594852  311.769342   643.437745
4                SF-OGD  0.972603  1953.713059  311.769342  1953.713059
5                  FACI  0.890411   652.584086  311.769342   724.100151
6            MFCS Split  0.969863  1908.645042  311.769342  1908.645042
7             MFCS Full  0.961644  1954.526647  467.281839  1954.526647

In [55]:
conformal_predictions_COP(
    model_class=HistGradientBoostingRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="HGBR",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/HGBM.xlsx",
    alpha=0.05,
)

===== CONFORMAL OPTIMISTIC PREDICTION (HGBR) =====
Coverage : 96.986%
Avg Width: 1908.140
RMSE     : 311.769
Final q  : 953.961

  Strategy  Coverage        Width        RMSE  Alpha    LR  Scale
0      COP  0.969863  1908.139804  311.769342   0.05  0.05    0.5

In [56]:
conformal_predictions_EXTREME(
    model_class=HistGradientBoostingRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="HGBR",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/HGBM.xlsx",
    alpha=0.05,
    calib_size=0.3,
)

===== EXTREME CONFORMAL PREDICTION (HGBR) =====
Coverage : 100.000%
Width    : 233488.926
RMSE     : 328.523
q_extreme: 233488.926
u        : 2604.861
#Exceed. : 73

In [57]:
conformal_predictions_AlphaNet(
    model_class=HistGradientBoostingRegressor,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="HGBR",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/HGBM.xlsx",
    alpha=0.05,
)

  [Info] n_calib=548 | alpha_min=0.0118
  [Step 2/9] Training base HGBR model...
  [Step 2/9] Done in 0s
  [Step 3/9] Precomputing 548 LOO score vectors...

    LOO precompute:   0%|          | 0/548 [00:00<?, ?it/s]

  [Step 3/9] Done in 1s
  [Step 4/9] Training AlphaNet: 4 runs × 50 epochs

    Run 1/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 1/4 | Epoch 0/50 | Loss: 63230.2980 | Size: 63230.0610 | α̃: 0.0118 | ⏱ 0.21s/epoch | ETA: 44s
  λ=20.0 | Run 1/4 | Epoch 10/50 | Loss: 63227.0085 | Size: 63226.7706 | α̃: 0.0118 | ⏱ 0.18s/epoch | ETA: 35s
  λ=20.0 | Run 1/4 | Epoch 20/50 | Loss: 63112.2904 | Size: 63112.0512 | α̃: 0.0118 | ⏱ 0.20s/epoch | ETA: 33s
  λ=20.0 | Run 1/4 | Epoch 30/50 | Loss: 63230.4566 | Size: 63230.2179 | α̃: 0.0118 | ⏱ 0.17s/epoch | ETA: 31s
  λ=20.0 | Run 1/4 | Epoch 40/50 | Loss: 63230.2066 | Size: 63229.9679 | α̃: 0.0118 | ⏱ 0.19s/epoch | ETA: 29s
  λ=20.0 | Run 1/4 | Epoch 49/50 | Loss: 63194.2856 | Size: 63194.0477 | α̃: 0.0118 | ⏱ 0.23s/epoch | ETA: 28s
  ✓ Run 1 complete | Final loss: 63194.2856

    Run 2/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 2/4 | Epoch 0/50 | Loss: 653.1941 | Size: 633.1941 | α̃: 1.0000 | ⏱ 0.26s/epoch | ETA: 28s
  λ=20.0 | Run 2/4 | Epoch 10/50 | Loss: 653.2453 | Size: 633.2453 | α̃: 1.0000 | ⏱ 0.29s/epoch | ETA: 27s
  λ=20.0 | Run 2/4 | Epoch 20/50 | Loss: 653.2245 | Size: 633.2245 | α̃: 1.0000 | ⏱ 0.19s/epoch | ETA: 25s
  λ=20.0 | Run 2/4 | Epoch 30/50 | Loss: 653.2462 | Size: 633.2462 | α̃: 1.0000 | ⏱ 0.19s/epoch | ETA: 23s
  λ=20.0 | Run 2/4 | Epoch 40/50 | Loss: 653.2221 | Size: 633.2221 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 21s
  λ=20.0 | Run 2/4 | Epoch 49/50 | Loss: 653.2458 | Size: 633.2458 | α̃: 1.0000 | ⏱ 0.17s/epoch | ETA: 19s
  ✓ Run 2 complete | Final loss: 653.2458

    Run 3/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 3/4 | Epoch 0/50 | Loss: 653.2213 | Size: 633.2213 | α̃: 1.0000 | ⏱ 0.19s/epoch | ETA: 19s
  λ=20.0 | Run 3/4 | Epoch 10/50 | Loss: 653.2482 | Size: 633.2482 | α̃: 1.0000 | ⏱ 0.17s/epoch | ETA: 17s
  λ=20.0 | Run 3/4 | Epoch 20/50 | Loss: 653.2253 | Size: 633.2253 | α̃: 1.0000 | ⏱ 0.23s/epoch | ETA: 15s
  λ=20.0 | Run 3/4 | Epoch 30/50 | Loss: 653.2457 | Size: 633.2457 | α̃: 1.0000 | ⏱ 0.19s/epoch | ETA: 14s
  λ=20.0 | Run 3/4 | Epoch 40/50 | Loss: 653.1375 | Size: 633.1375 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 12s
  λ=20.0 | Run 3/4 | Epoch 49/50 | Loss: 653.1932 | Size: 633.1932 | α̃: 1.0000 | ⏱ 0.17s/epoch | ETA: 10s
  ✓ Run 3 complete | Final loss: 653.1932

    Run 4/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 4/4 | Epoch 0/50 | Loss: 653.2056 | Size: 633.2056 | α̃: 1.0000 | ⏱ 0.20s/epoch | ETA: 10s
  λ=20.0 | Run 4/4 | Epoch 10/50 | Loss: 653.1281 | Size: 633.1281 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 8s
  λ=20.0 | Run 4/4 | Epoch 20/50 | Loss: 653.2440 | Size: 633.2440 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 6s
  λ=20.0 | Run 4/4 | Epoch 30/50 | Loss: 653.2178 | Size: 633.2178 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 4s
  λ=20.0 | Run 4/4 | Epoch 40/50 | Loss: 653.2465 | Size: 633.2465 | α̃: 1.0000 | ⏱ 0.25s/epoch | ETA: 2s
  λ=20.0 | Run 4/4 | Epoch 49/50 | Loss: 653.1684 | Size: 633.1684 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 0s
  ✓ Run 4 complete | Final loss: 653.1684
  [Step 4/9] Training done in 39s
  [Step 5/9] Computing conformal intervals on test set...

=======================================================
  ALPHANET CONFORMAL (HGBR)
=======================================================
  Learned α̃     : 1.0000
  Half-width (r) : 316.6019
  Coverage       : 89.863%
  Avg Width      : 633.2039
  RMSE           : 448.2493
  Total time     : 40s
    ├─ Precompute: 1s
    └─ Training  : 39s
=======================================================
  [Step 8/9] Generating plots...
  [Step 9/9] Saving to Excel...
  [Step 9/9] Saved!

  ✅ AlphaNet Conformal complete in 40s

,Strategy,Coverage,Width,RMSE,Alpha_nominal,Alpha_learned,Lambda_reg,Total_time_sec
0,AlphaNet Conformal,0.89863,633.203857,448.249279,0.05,1.0,20.0,40.01

# **Conformal Predictions with PGBM**

In [58]:
class PGBMWrapper(BaseEstimator, RegressorMixin):
    def __init__(self, **params):
        self.params = params
        self.model = None

    def fit(self, X, y):
        X_ = X.to_numpy() if hasattr(X, "to_numpy") else np.array(X)
        y_ = y.to_numpy() if hasattr(y, "to_numpy") else np.array(y)
        self.model = PGBM()
        self.model.train(
            train_set=(X_, y_),
            objective=mseloss_objective,
            metric=rmseloss_metric,
            params=self.params
        )
        return self

    def predict(self, X):
        X_ = X.to_numpy() if hasattr(X, "to_numpy") else np.array(X)
        return self.model.predict(X_).numpy()

In [59]:
# Assuming best_params is obtained correctly
best_params = get_best_model_params(best_scores_autosampler, 'PGBM')

# Remove any conflicting parameters from best_params
incompatible_keys = ['Dist', 'Score']
for key in incompatible_keys:
    best_params.pop(key, None)

# Initialize PGBM model
pgbm_model = PGBM()
def mseloss_objective(yhat, y, sample_weight=None):
    # Ensure that yhat and y are PyTorch tensors
    if not torch.is_tensor(yhat):
        yhat = torch.from_numpy(np.array(yhat)).float()
    if not torch.is_tensor(y):
        y = torch.from_numpy(np.array(y)).float()
    gradient = yhat - y
    hessian = torch.ones_like(yhat)
    return gradient, hessian

def rmseloss_metric(yhat, y, sample_weight=None):
    # Ensure that yhat and y are PyTorch tensors
    if not torch.is_tensor(yhat):
        yhat = torch.from_numpy(np.array(yhat)).float()
    if not torch.is_tensor(y):
        y = torch.from_numpy(np.array(y)).float()
    loss = torch.sqrt(torch.mean((yhat - y) ** 2))
    return loss

X_train = np.array(X_train)
y_train = np.array(y_train)
X_test = np.array(X_test)
y_test = np.array(y_test)

# Fit the model
pgbm_model.train((X_train, y_train), objective=mseloss_objective, metric=rmseloss_metric, params=best_params)

# Predict the distribution
pred_dist = pgbm_model.predict_dist(X_test)

# Define the quantiles you want to predict
quantiles = [0.05, 0.1, 0.15, 0.2, 0.3,
             0.4, 0.5, 0.6, 0.7, 0.8,
             0.85, 0.9, 0.95]

# DataFrame to store predictions
predictions_PGBM_df = pd.DataFrame()

# Calculate and store quantiles
for q in quantiles:
    predictions_PGBM_df[q] = np.quantile(pred_dist, q, axis=0)

# Add actual Y_Label to the DataFrame
predictions_PGBM_df['Actual'] = y_test.ravel()

# Print the DataFrame with predictions for each quantile
print(predictions_PGBM_df.head())

Training on CPU
Estimator 0/100, Train metric: 4785.5781
Estimator 1/100, Train metric: 4716.0503
Estimator 2/100, Train metric: 4644.9238
Estimator 3/100, Train metric: 4567.3071
Estimator 4/100, Train metric: 4485.7036
Estimator 5/100, Train metric: 4414.1963
Estimator 6/100, Train metric: 4342.2041
Estimator 7/100, Train metric: 4294.3203
Estimator 8/100, Train metric: 4232.3247
Estimator 9/100, Train metric: 4175.2485
Estimator 10/100, Train metric: 4117.8438
Estimator 11/100, Train metric: 4074.5427
Estimator 12/100, Train metric: 4027.6052
Estimator 13/100, Train metric: 3969.5894
Estimator 14/100, Train metric: 3934.0879
Estimator 15/100, Train metric: 3884.0276
Estimator 16/100, Train metric: 3849.3979
Estimator 17/100, Train metric: 3796.5886
Estimator 18/100, Train metric: 3756.7878
Estimator 19/100, Train metric: 3707.1123
Estimator 20/100, Train metric: 3662.5784
Estimator 21/100, Train metric: 3627.9343
Estimator 22/100, Train metric: 3589.0693
Estimator 23/100, Train metric: 3559.3635
Estimator 24/100, Train metric: 3519.8503
Estimator 25/100, Train metric: 3486.7107
Estimator 26/100, Train metric: 3455.1050
Estimator 27/100, Train metric: 3425.0452
Estimator 28/100, Train metric: 3410.2742
Estimator 29/100, Train metric: 3380.3259
Estimator 30/100, Train metric: 3368.2126
Estimator 31/100, Train metric: 3338.4089
Estimator 32/100, Train metric: 3314.2478
Estimator 33/100, Train metric: 3298.9172
Estimator 34/100, Train metric: 3274.0374
Estimator 35/100, Train metric: 3259.7502
Estimator 36/100, Train metric: 3242.4282
Estimator 37/100, Train metric: 3222.9932
Estimator 38/100, Train metric: 3209.1711
Estimator 39/100, Train metric: 3196.1951
Estimator 40/100, Train metric: 3181.8035
Estimator 41/100, Train metric: 3170.4497
Estimator 42/100, Train metric: 3156.1653
Estimator 43/100, Train metric: 3139.1514
Estimator 44/100, Train metric: 3124.4719
Estimator 45/100, Train metric: 3112.9504
Estimator 46/100, Train metric: 3102.4482
Estimator 47/100, Train metric: 3091.2197
Estimator 48/100, Train metric: 3077.9343
Estimator 49/100, Train metric: 3065.4868
Estimator 50/100, Train metric: 3069.4087
Estimator 51/100, Train metric: 3057.7764
Estimator 52/100, Train metric: 3047.5630
Estimator 53/100, Train metric: 3035.9792
Estimator 54/100, Train metric: 3026.7917
Estimator 55/100, Train metric: 3020.9639
Estimator 56/100, Train metric: 3010.0757
Estimator 57/100, Train metric: 3005.9148
Estimator 58/100, Train metric: 3001.2415
Estimator 59/100, Train metric: 2995.9473
Estimator 60/100, Train metric: 2985.3713
Estimator 61/100, Train metric: 2980.9819
Estimator 62/100, Train metric: 2975.9624
Estimator 63/100, Train metric: 2971.2502
Estimator 64/100, Train metric: 2966.4805
Estimator 65/100, Train metric: 2960.4290
Estimator 66/100, Train metric: 2957.1323
Estimator 67/100, Train metric: 2950.0166
Estimator 68/100, Train metric: 2945.8262
Estimator 69/100, Train metric: 2941.5364
Estimator 70/100, Train metric: 2939.0271
Estimator 71/100, Train metric: 2934.4133
Estimator 72/100, Train metric: 2930.0994
Estimator 73/100, Train metric: 2926.9014
Estimator 74/100, Train metric: 2922.0410
Estimator 75/100, Train metric: 2919.2212
Estimator 76/100, Train metric: 2915.2844
Estimator 77/100, Train metric: 2913.6797
Estimator 78/100, Train metric: 2912.4202
Estimator 79/100, Train metric: 2908.8772
Estimator 80/100, Train metric: 2904.2393
Estimator 81/100, Train metric: 2900.8198
Estimator 82/100, Train metric: 2898.2141
Estimator 83/100, Train metric: 2896.2488
Estimator 84/100, Train metric: 2894.7161
Estimator 85/100, Train metric: 2891.2788
Estimator 86/100, Train metric: 2889.5957
Estimator 87/100, Train metric: 2888.5396
Estimator 88/100, Train metric: 2885.8940
Estimator 89/100, Train metric: 2882.8940
Estimator 90/100, Train metric: 2881.8862
Estimator 91/100, Train metric: 2878.5588
Estimator 92/100, Train metric: 2875.9741
Estimator 93/100, Train metric: 2872.4604
Estimator 94/100, Train metric: 2870.9814
Estimator 95/100, Train metric: 2870.4788
Estimator 96/100, Train metric: 2871.1038
Estimator 97/100, Train metric: 2867.2288
Estimator 98/100, Train metric: 2864.3069
Estimator 99/100, Train metric: 2864.2512
        0.05        0.1       0.15        0.2        0.3        0.4  \
0 -11.880088   5.282206  19.288183  20.765208  30.486157  36.138600
1  -0.871786  10.023221  16.516031  26.245701  34.353270  38.412539
2  -6.825849   3.800864   6.901764   9.096442  14.767761  21.597373
3  -8.133529   0.837296   6.450811   9.729606  21.486102  24.836896
4  -1.240310   1.394684   4.437029   9.588537  15.336718  20.759000

         0.5        0.6        0.7        0.8       0.85        0.9  \
0  39.924643  47.292494  55.580267  63.609167  69.393591  74.706477
1  42.427830  48.833459  52.852695  61.330706  64.149328  70.740315
2  25.660300  30.576552  34.818350  41.099275  47.219924  53.406319
3  30.259842  34.184840  40.101193  43.074809  45.520107  49.157681
4  25.685087  30.898521  36.639318  49.995277  55.612261  61.198606

        0.95  Actual
0  83.161513    44.0
1  83.091062    29.0
2  63.603879    23.0
3  69.474574    26.0
4  75.656467    30.0

In [60]:
class validate:
    @staticmethod
    def coverage(int_pred, y_test):
        return {strat_name: np.mean((y_test >= int_pred[strat_name][:, 0]) & (y_test <= int_pred[strat_name][:, 1])) for strat_name in int_pred}
    @staticmethod
    def width(int_pred): # Corrected: Removed y_test argument as it's not defined and not used
        return {strat_name: np.mean(int_pred[strat_name][:, 1] - int_pred[strat_name][:, 0]) for strat_name in int_pred}
    @staticmethod
    def rmse(y_pred, y_test):
        return {strat_name: np.sqrt(mean_squared_error(y_test, y_pred[strat_name])) for strat_name in y_pred}
    @staticmethod
    def cwc(int_pred, y_test, miscoverage):
        widths = validate.width(int_pred)
        coverages = validate.coverage(int_pred, y_test)
        return {strat_name: widths[strat_name] * (1 + (coverages[strat_name] < (1 - miscoverage)) * (1 - coverages[strat_name])) for strat_name in int_pred}

    @staticmethod
    def cond_coverage(int_pred, y_test, num_bins=10):
        cond_coverages = {}
        for strat_name in int_pred:
            widths = int_pred[strat_name][:, 1] - int_pred[strat_name][:, 0]
            bin_edges = np.histogram_bin_edges(widths, bins=num_bins)
            digitized_widths = np.digitize(widths, bin_edges)
            strategy_cond_coverage = []
            for bin_num in range(1, num_bins + 1):
                indices_in_bin = np.where(digitized_widths == bin_num)[0]
                if len(indices_in_bin) > 0:
                    bin_coverage = np.mean((y_test[indices_in_bin] >= int_pred[strat_name][indices_in_bin, 0]) & (y_test[indices_in_bin] <= int_pred[strat_name][indices_in_bin, 1]))
                    strategy_cond_coverage.append(bin_coverage)
                else:
                    strategy_cond_coverage.append(np.nan) # or handle empty bins as needed
            cond_coverages[strat_name] = strategy_cond_coverage
        return cond_coverages


class visualize:
    @staticmethod
    def coverage(int_pred, y_test):
        return {strat_name: np.mean((y_test >= int_pred[strat_name][:, 0]) & (y_test.to_numpy() <= int_pred[strat_name][:, 1])) for strat_name in int_pred}
    @staticmethod
    def width(int_pred):
        return {strat_name: np.mean(int_pred[strat_name][:, 1] - int_pred[strat_name][:, 0]) for strat_name in int_pred}
    @staticmethod
    def rmse(y_pred, y_test):
        return {strat_name: np.sqrt(mean_squared_error(y_test, y_pred[strat_name])) for strat_name in y_pred}
    @staticmethod
    def cwc(int_pred, y_test, miscoverage):
        widths = visualize.width(int_pred)
        coverages = visualize.coverage(int_pred, y_test)
        return {strat_name: widths[strat_name] * (1 + (coverages[strat_name] < (1 - miscoverage)) * (1 - coverages[strat_name])) for strat_name in int_pred}
    @staticmethod
    def goodness(y_true, y_pred, y_pred_low, y_pred_up, coverage, width, rmse, cwc, ax=None, title="Goodness Plot"):
        if ax is None:
            fig, ax = plt.subplots()
        n_samples = len(y_true)
        y_true_np = y_true.ravel() # Ensure y_true is numpy array and flattened

        # Determine points inside and outside the interval
        inside_interval = (y_true_np >= y_pred_low) & (y_true_np <= y_pred_up)
        outside_interval = ~inside_interval

        # Plot points inside the interval in green
        ax.scatter(y_true_np[inside_interval], y_pred[inside_interval], color='green', s=10, label='Inside Interval')
        # Plot points outside the interval in orange
        ax.scatter(y_true_np[outside_interval], y_pred[outside_interval], color='orange', s=10, label='Outside Interval')

        # Plot all ground truth values as blue crosses
        ax.scatter(y_true_np, y_true_np, color='blue', marker='x', s=30, linewidths=0.7, label='Ground Truth Values')


        ax.vlines(y_true_np, y_pred_low, y_pred_up, color='gray', alpha=0.5, label='Prediction Intervals')
        ax.plot([min(y_true_np), max(y_true_np)], [min(y_true_np), max(y_true_np)], linestyle='--', color='blue', label='Ideal Prediction Line') # Changed label for clarity
        ax.set_xlabel('Ground Truth')
        ax.set_ylabel('Predictions')
        ax.set_title(f'{title}\nCoverage: {coverage*100:.2f}%, Width: {width:.2f}, RMSE: {rmse:.2f}, CWC: {cwc:.2f}')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax

    @staticmethod
    def width_size_occurrence(int_pred, train_intervals, num_bins=10, ax=None, x_lim=None, title="Width Size Occurrence"):
        if ax is None:
            fig, ax = plt.subplots()

        # Calculate interval widths for test and train sets
        widths_test = np.abs(int_pred[:, 1] - int_pred[:, 0])
        widths_train = np.abs(train_intervals[:, 1] - train_intervals[:, 0])

        # Plot histograms for both train and test widths
        ax.hist(widths_test, bins=num_bins, alpha=0.6, label='Test Interval Widths', color='red')
        ax.hist(widths_train, bins=num_bins, alpha=0.4, label='Train Interval Widths', color='blue')


        if x_lim is not None:
            ax.set_xlim(x_lim)
        ax.set_xlabel('Interval Width')
        ax.set_ylabel('Occurrence (Frequency)')
        ax.set_title(f'{title} - Interval Width Occurrence')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax

    @staticmethod
    def coverage_by_width(y_test, int_pred, miscoverage, cond_coverages, num_bins=10, ax=None, title="Coverage vs Width"):
        if ax is None:
            fig, ax = plt.subplots()

        widths = int_pred[:, 1] - int_pred[:, 0]
        bin_edges = np.histogram_bin_edges(widths, bins=num_bins)
        bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2
        bin_width = bin_edges[1] - bin_edges[0]

        ax.bar(bin_centers, cond_coverages, width=bin_width, color='blue', alpha=0.7, edgecolor='black', linewidth=0.8, label='Conditional Coverage')
        ax.axhline(1 - miscoverage, color='red', linestyle='--', label=f'Nominal Coverage ({(1 - miscoverage)*100:.0f}%)')

        ax.set_xlabel('Interval Width')
        ax.set_ylabel('Conditional Coverage')
        ax.set_title(f'{title} - Coverage vs Interval Width')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax

In [61]:

def to_numpy_1d(y):
    return y.to_numpy().ravel() if hasattr(y, "to_numpy") else np.asarray(y).ravel()


def weighted_quantile(values, weights, q):
    sorter = np.argsort(values)
    values, weights = values[sorter], weights[sorter]
    cdf = np.cumsum(weights) / np.sum(weights)
    return np.interp(q, cdf, values)



# ============================================================
# NexCP for PGBM (Excel-safe, NexCP-style, NO RETURNS)
# ============================================================

def conformal_predictions_NEXCP_PGBM(
    model_class,
    best_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name="PGBM",
    excel_file_path=None,
    alpha=0.05,
    decay=0.99,
    n_folds=5,
    n_bootstrap=50,
    seed=123,
):

    warnings.filterwarnings("ignore")
    np.random.seed(seed)

    # ========================================================
    # Data conversion (PGBM-specific)
    # ========================================================
    Xtr = X_train.to_numpy() if hasattr(X_train, "to_numpy") else np.asarray(X_train)
    Xte = X_test.to_numpy() if hasattr(X_test, "to_numpy") else np.asarray(X_test)
    ytr = to_numpy_1d(y_train)
    yte = to_numpy_1d(y_test)

    STRATEGIES = {
        "NexCP-Split": "NexCP Split",
        "NexCP-Full": "NexCP Full",
        "NexCP-J+aB": "NexCP Jackknife+ aB",
        "NexCP-CV+": "NexCP CV+",
    }

    y_pred, int_pred = {}, {}

    # ========================================================
    # Fit base model
    # ========================================================
    base_model = model_class(**best_params)
    base_model.fit(Xtr, ytr)

    yhat_tr = base_model.predict(Xtr)
    yhat_te = base_model.predict(Xte)
    residuals = np.abs(ytr - yhat_tr)

    # ========================================================
    # NexCP – Split (Exponentially Weighted)
    # ========================================================
    weights = decay ** np.arange(len(residuals) - 1, -1, -1)
    q = weighted_quantile(residuals, weights, 1 - alpha)

    y_pred["NexCP-Split"] = yhat_te
    int_pred["NexCP-Split"] = np.c_[yhat_te - q, yhat_te + q]

    # ========================================================
    # NexCP – Full
    # ========================================================
    q = np.quantile(residuals, 1 - alpha)
    y_pred["NexCP-Full"] = yhat_te
    int_pred["NexCP-Full"] = np.c_[yhat_te - q, yhat_te + q]

    # ========================================================
    # NexCP – Jackknife+ aB
    # ========================================================
    rng = np.random.default_rng(seed)
    lowers, uppers, preds = [], [], []

    for _ in range(n_bootstrap):
        idx = rng.choice(len(Xtr), len(Xtr), replace=True)
        m = model_class(**best_params)
        m.fit(Xtr[idx], ytr[idx])

        q = np.quantile(np.abs(ytr[idx] - m.predict(Xtr[idx])), 1 - alpha)
        p = m.predict(Xte)

        preds.append(p)
        lowers.append(p - q)
        uppers.append(p + q)

    y_pred["NexCP-J+aB"] = np.mean(preds, axis=0)
    int_pred["NexCP-J+aB"] = np.c_[np.min(lowers, axis=0), np.max(uppers, axis=0)]

    # ========================================================
    # NexCP – CV+
    # ========================================================
    kf = KFold(n_splits=n_folds, shuffle=True, random_state=seed)
    lowers, uppers, preds = [], [], []

    for tr_idx, cal_idx in kf.split(Xtr):
        m = model_class(**best_params)
        m.fit(Xtr[tr_idx], ytr[tr_idx])

        q = np.quantile(np.abs(ytr[cal_idx] - m.predict(Xtr[cal_idx])), 1 - alpha)
        p = m.predict(Xte)

        preds.append(p)
        lowers.append(p - q)
        uppers.append(p + q)

    y_pred["NexCP-CV+"] = np.mean(preds, axis=0)
    int_pred["NexCP-CV+"] = np.c_[np.mean(lowers, axis=0), np.mean(uppers, axis=0)]

    # ========================================================
    # Metrics + Summary
    # ========================================================
    summary_rows = []
    values_dict = {}

    print("\n===== NEXCP (PGBM) RESULTS =====")

    for s in STRATEGIES:
        ymin, ymax = int_pred[s].T
        yhat = y_pred[s]

        coverage = np.mean((yte >= ymin) & (yte <= ymax))
        width = np.mean(ymax - ymin)
        rmse = np.sqrt(mean_squared_error(yte, yhat))

        print(f"{STRATEGIES[s]} - Coverage: {coverage*100:.3f}% | Width: {width:.3f}")

        summary_rows.append({
            "Strategy": STRATEGIES[s],
            "Coverage": coverage,
            "Width": width,
            "RMSE": rmse,
        })

        values_dict[f"{s}_true"] = yte
        values_dict[f"{s}_pred"] = yhat
        values_dict[f"{s}_lower"] = ymin
        values_dict[f"{s}_upper"] = ymax

    summary_df = pd.DataFrame(summary_rows)
    values_df = pd.DataFrame(values_dict)

    # ========================================================
    # Plotting (SAVE ONLY — NO SHOW)
    # ========================================================
    idx = np.arange(len(yte))
    plot_buffers = {}

    for s in STRATEGIES:
        fig, ax = plt.subplots(figsize=(10, 4))

        ax.scatter(idx, yte, s=10, color="blue", alpha=0.7, label="True")
        ax.fill_between(idx, int_pred[s][:, 0], int_pred[s][:, 1],
                        color="gray", alpha=0.5, label="Prediction interval")
        ax.plot(idx, y_pred[s], color="red", lw=1, label="Predicted mean")

        ax.set_title(f"{STRATEGIES[s]} ({model_name})")
        ax.set_xlabel("Sample Number")
        ax.set_ylabel("Y_Label")
        ax.legend(loc="upper left")

        plt.tight_layout()

        buf = io.BytesIO()
        fig.savefig(buf, format="png")
        buf.seek(0)
        plot_buffers[s] = buf

        plt.close(fig)

    # ========================================================
    # Excel Export (append-safe)
    # ========================================================
    if excel_file_path:
        wb = load_workbook(excel_file_path)

        # ---- Summary sheet ----
        sheet_name = "NEXCP_PGBM_Summary"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        # ---- Plot sheets ----
        for s, buf in plot_buffers.items():
            img = Image(buf)
            sheet_name = f"NEXCP_PGBM_Plot_{s}"
            base = sheet_name
            i = 1
            while sheet_name in wb.sheetnames:
                sheet_name = f"{base}_{i}"
                i += 1
            ws = wb.create_sheet(sheet_name)
            ws.add_image(img, "A1")

        # ---- Values sheet ----
        sheet_name = "NEXCP_PGBM_Values"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        wb.save(excel_file_path)


conformal_predictions_NEXCP_PGBM(
    model_class=PGBMWrapper,
    best_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="PGBM",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/PGBM.xlsx",
    alpha=0.05,
)

Streaming output truncated to the last 5000 lines.
Estimator 55/100, Train metric: 3119.9250
Estimator 56/100, Train metric: 3111.4404
Estimator 57/100, Train metric: 3103.6418
Estimator 58/100, Train metric: 3095.5708
Estimator 59/100, Train metric: 3091.1743
Estimator 60/100, Train metric: 3083.4084
Estimator 61/100, Train metric: 3076.4680
Estimator 62/100, Train metric: 3069.5762
Estimator 63/100, Train metric: 3065.5994
Estimator 64/100, Train metric: 3062.3738
Estimator 65/100, Train metric: 3054.5718
Estimator 66/100, Train metric: 3049.0022
Estimator 67/100, Train metric: 3044.8518
Estimator 68/100, Train metric: 3047.0432
Estimator 69/100, Train metric: 3043.1541
Estimator 70/100, Train metric: 3038.0457
Estimator 71/100, Train metric: 3032.0979
Estimator 72/100, Train metric: 3027.8933
Estimator 73/100, Train metric: 3028.8535
Estimator 74/100, Train metric: 3026.1772
Estimator 75/100, Train metric: 3018.9314
Estimator 76/100, Train metric: 3009.4648
Estimator 77/100, Train metric: 3005.1077
Estimator 78/100, Train metric: 2996.9834
Estimator 79/100, Train metric: 2993.6509
Estimator 80/100, Train metric: 2990.5728
Estimator 81/100, Train metric: 2984.5894
Estimator 82/100, Train metric: 2981.5015
Estimator 83/100, Train metric: 2979.1631
Estimator 84/100, Train metric: 2971.5110
Estimator 85/100, Train metric: 2966.2646
Estimator 86/100, Train metric: 2964.7522
Estimator 87/100, Train metric: 2957.6409
Estimator 88/100, Train metric: 2952.8074
Estimator 89/100, Train metric: 2956.2590
Estimator 90/100, Train metric: 2950.3621
Estimator 91/100, Train metric: 2943.2175
Estimator 92/100, Train metric: 2938.0317
Estimator 93/100, Train metric: 2939.9304
Estimator 94/100, Train metric: 2930.1125
Estimator 95/100, Train metric: 2927.6553
Estimator 96/100, Train metric: 2921.6543
Estimator 97/100, Train metric: 2913.5581
Estimator 98/100, Train metric: 2911.9468
Estimator 99/100, Train metric: 2907.4814
Training on CPU
Estimator 0/100, Train metric: 3688.3740
Estimator 1/100, Train metric: 3626.7385
Estimator 2/100, Train metric: 3565.1284
Estimator 3/100, Train metric: 3500.3159
Estimator 4/100, Train metric: 3456.6204
Estimator 5/100, Train metric: 3409.2427
Estimator 6/100, Train metric: 3371.9221
Estimator 7/100, Train metric: 3334.0151
Estimator 8/100, Train metric: 3293.3870
Estimator 9/100, Train metric: 3240.2126
Estimator 10/100, Train metric: 3188.7937
Estimator 11/100, Train metric: 3139.8010
Estimator 12/100, Train metric: 3096.0898
Estimator 13/100, Train metric: 3055.7559
Estimator 14/100, Train metric: 3020.6294
Estimator 15/100, Train metric: 2988.7568
Estimator 16/100, Train metric: 2957.5437
Estimator 17/100, Train metric: 2928.6978
Estimator 18/100, Train metric: 2903.5100
Estimator 19/100, Train metric: 2870.2966
Estimator 20/100, Train metric: 2839.4944
Estimator 21/100, Train metric: 2814.1111
Estimator 22/100, Train metric: 2785.0818
Estimator 23/100, Train metric: 2758.4268
Estimator 24/100, Train metric: 2735.0378
Estimator 25/100, Train metric: 2712.2424
Estimator 26/100, Train metric: 2692.8521
Estimator 27/100, Train metric: 2674.6929
Estimator 28/100, Train metric: 2654.2173
Estimator 29/100, Train metric: 2629.7473
Estimator 30/100, Train metric: 2609.9500
Estimator 31/100, Train metric: 2595.2051
Estimator 32/100, Train metric: 2577.8569
Estimator 33/100, Train metric: 2560.0098
Estimator 34/100, Train metric: 2545.1494
Estimator 35/100, Train metric: 2528.8062
Estimator 36/100, Train metric: 2516.1416
Estimator 37/100, Train metric: 2502.3257
Estimator 38/100, Train metric: 2492.8008
Estimator 39/100, Train metric: 2487.6555
Estimator 40/100, Train metric: 2482.2043
Estimator 41/100, Train metric: 2469.7798
Estimator 42/100, Train metric: 2467.6677
Estimator 43/100, Train metric: 2456.6726
Estimator 44/100, Train metric: 2451.9783
Estimator 45/100, Train metric: 2439.2500
Estimator 46/100, Train metric: 2429.5098
Estimator 47/100, Train metric: 2419.8301
Estimator 48/100, Train metric: 2412.5798
Estimator 49/100, Train metric: 2403.7395
Estimator 50/100, Train metric: 2399.6057
Estimator 51/100, Train metric: 2396.1951
Estimator 52/100, Train metric: 2389.9329
Estimator 53/100, Train metric: 2380.8687
Estimator 54/100, Train metric: 2373.7720
Estimator 55/100, Train metric: 2369.8918
Estimator 56/100, Train metric: 2362.5090
Estimator 57/100, Train metric: 2358.1123
Estimator 58/100, Train metric: 2357.1570
Estimator 59/100, Train metric: 2347.9431
Estimator 60/100, Train metric: 2342.4219
Estimator 61/100, Train metric: 2334.3425
Estimator 62/100, Train metric: 2331.7361
Estimator 63/100, Train metric: 2329.4648
Estimator 64/100, Train metric: 2324.3274
Estimator 65/100, Train metric: 2317.4172
Estimator 66/100, Train metric: 2314.2144
Estimator 67/100, Train metric: 2309.1672
Estimator 68/100, Train metric: 2304.3545
Estimator 69/100, Train metric: 2300.2996
Estimator 70/100, Train metric: 2295.4268
Estimator 71/100, Train metric: 2294.1858
Estimator 72/100, Train metric: 2287.8525
Estimator 73/100, Train metric: 2284.0605
Estimator 74/100, Train metric: 2281.8054
Estimator 75/100, Train metric: 2279.2207
Estimator 76/100, Train metric: 2276.8149
Estimator 77/100, Train metric: 2274.1931
Estimator 78/100, Train metric: 2271.2136
Estimator 79/100, Train metric: 2268.3828
Estimator 80/100, Train metric: 2266.2087
Estimator 81/100, Train metric: 2264.4375
Estimator 82/100, Train metric: 2256.5544
Estimator 83/100, Train metric: 2250.0579
Estimator 84/100, Train metric: 2250.3379
Estimator 85/100, Train metric: 2250.5315
Estimator 86/100, Train metric: 2243.6404
Estimator 87/100, Train metric: 2236.0186
Estimator 88/100, Train metric: 2236.7627
Estimator 89/100, Train metric: 2233.4104
Estimator 90/100, Train metric: 2231.2432
Estimator 91/100, Train metric: 2228.8987
Estimator 92/100, Train metric: 2226.2944
Estimator 93/100, Train metric: 2219.9463
Estimator 94/100, Train metric: 2217.6575
Estimator 95/100, Train metric: 2215.4224
Estimator 96/100, Train metric: 2212.9224
Estimator 97/100, Train metric: 2207.5442
Estimator 98/100, Train metric: 2206.2434
Estimator 99/100, Train metric: 2204.3286
Training on CPU
Estimator 0/100, Train metric: 5023.2075
Estimator 1/100, Train metric: 4935.2300
Estimator 2/100, Train metric: 4861.0698
Estimator 3/100, Train metric: 4781.7129
Estimator 4/100, Train metric: 4712.4878
Estimator 5/100, Train metric: 4654.7568
Estimator 6/100, Train metric: 4583.1401
Estimator 7/100, Train metric: 4511.1104
Estimator 8/100, Train metric: 4471.7759
Estimator 9/100, Train metric: 4439.2466
Estimator 10/100, Train metric: 4380.3672
Estimator 11/100, Train metric: 4359.5767
Estimator 12/100, Train metric: 4300.4453
Estimator 13/100, Train metric: 4261.0771
Estimator 14/100, Train metric: 4211.7832
Estimator 15/100, Train metric: 4167.4629
Estimator 16/100, Train metric: 4140.7349
Estimator 17/100, Train metric: 4093.9622
Estimator 18/100, Train metric: 4044.7727
Estimator 19/100, Train metric: 4004.4092
Estimator 20/100, Train metric: 3968.9465
Estimator 21/100, Train metric: 3943.7195
Estimator 22/100, Train metric: 3930.1211
Estimator 23/100, Train metric: 3897.0840
Estimator 24/100, Train metric: 3861.8618
Estimator 25/100, Train metric: 3851.0989
Estimator 26/100, Train metric: 3837.8984
Estimator 27/100, Train metric: 3809.1389
Estimator 28/100, Train metric: 3795.7019
Estimator 29/100, Train metric: 3773.0312
Estimator 30/100, Train metric: 3743.2732
Estimator 31/100, Train metric: 3723.8152
Estimator 32/100, Train metric: 3704.9832
Estimator 33/100, Train metric: 3678.3557
Estimator 34/100, Train metric: 3664.6345
Estimator 35/100, Train metric: 3646.7998
Estimator 36/100, Train metric: 3624.6897
Estimator 37/100, Train metric: 3602.9956
Estimator 38/100, Train metric: 3582.3740
Estimator 39/100, Train metric: 3570.5166
Estimator 40/100, Train metric: 3555.5537
Estimator 41/100, Train metric: 3550.9011
Estimator 42/100, Train metric: 3543.4961
Estimator 43/100, Train metric: 3538.4004
Estimator 44/100, Train metric: 3527.4707
Estimator 45/100, Train metric: 3523.9707
Estimator 46/100, Train metric: 3515.6558
Estimator 47/100, Train metric: 3505.2290
Estimator 48/100, Train metric: 3510.6279
Estimator 49/100, Train metric: 3501.2451
Estimator 50/100, Train metric: 3494.1736
Estimator 51/100, Train metric: 3487.0996
Estimator 52/100, Train metric: 3480.1394
Estimator 53/100, Train metric: 3468.0337
Estimator 54/100, Train metric: 3457.7175
Estimator 55/100, Train metric: 3455.8948
Estimator 56/100, Train metric: 3453.5420
Estimator 57/100, Train metric: 3446.3179
Estimator 58/100, Train metric: 3436.6304
Estimator 59/100, Train metric: 3425.8022
Estimator 60/100, Train metric: 3420.3872
Estimator 61/100, Train metric: 3416.0112
Estimator 62/100, Train metric: 3414.2983
Estimator 63/100, Train metric: 3407.1133
Estimator 64/100, Train metric: 3401.5166
Estimator 65/100, Train metric: 3398.2214
Estimator 66/100, Train metric: 3391.6313
Estimator 67/100, Train metric: 3388.8528
Estimator 68/100, Train metric: 3383.2861
Estimator 69/100, Train metric: 3376.1775
Estimator 70/100, Train metric: 3368.5256
Estimator 71/100, Train metric: 3364.2427
Estimator 72/100, Train metric: 3359.3408
Estimator 73/100, Train metric: 3355.9380
Estimator 74/100, Train metric: 3347.9417
Estimator 75/100, Train metric: 3344.2820
Estimator 76/100, Train metric: 3336.4028
Estimator 77/100, Train metric: 3332.9814
Estimator 78/100, Train metric: 3331.1035
Estimator 79/100, Train metric: 3326.9229
Estimator 80/100, Train metric: 3322.4832
Estimator 81/100, Train metric: 3319.4629
Estimator 82/100, Train metric: 3315.3240
Estimator 83/100, Train metric: 3312.6023
Estimator 84/100, Train metric: 3308.0383
Estimator 85/100, Train metric: 3304.9194
Estimator 86/100, Train metric: 3302.1826
Estimator 87/100, Train metric: 3295.5896
Estimator 88/100, Train metric: 3286.0671
Estimator 89/100, Train metric: 3279.5947
Estimator 90/100, Train metric: 3267.6943
Estimator 91/100, Train metric: 3264.4126
Estimator 92/100, Train metric: 3255.2463
Estimator 93/100, Train metric: 3252.5913
Estimator 94/100, Train metric: 3248.6025
Estimator 95/100, Train metric: 3246.4348
Estimator 96/100, Train metric: 3243.5435
Estimator 97/100, Train metric: 3237.9019
Estimator 98/100, Train metric: 3226.6196
Estimator 99/100, Train metric: 3220.7771
Training on CPU
Estimator 0/100, Train metric: 3445.3477
Estimator 1/100, Train metric: 3358.8904
Estimator 2/100, Train metric: 3279.9526
Estimator 3/100, Train metric: 3197.1348
Estimator 4/100, Train metric: 3124.7026
Estimator 5/100, Train metric: 3054.2283
Estimator 6/100, Train metric: 2988.4836
Estimator 7/100, Train metric: 2918.2510
Estimator 8/100, Train metric: 2852.3640
Estimator 9/100, Train metric: 2791.6680
Estimator 10/100, Train metric: 2730.5645
Estimator 11/100, Train metric: 2684.1091
Estimator 12/100, Train metric: 2625.4155
Estimator 13/100, Train metric: 2578.9128
Estimator 14/100, Train metric: 2544.7183
Estimator 15/100, Train metric: 2498.7007
Estimator 16/100, Train metric: 2454.0193
Estimator 17/100, Train metric: 2404.4541
Estimator 18/100, Train metric: 2361.3962
Estimator 19/100, Train metric: 2314.8870
Estimator 20/100, Train metric: 2276.8899
Estimator 21/100, Train metric: 2240.5481
Estimator 22/100, Train metric: 2207.2080
Estimator 23/100, Train metric: 2170.0598
Estimator 24/100, Train metric: 2138.5483
Estimator 25/100, Train metric: 2109.4556
Estimator 26/100, Train metric: 2076.5754
Estimator 27/100, Train metric: 2042.8177
Estimator 28/100, Train metric: 2017.7761
Estimator 29/100, Train metric: 1991.0453
Estimator 30/100, Train metric: 1960.8936
Estimator 31/100, Train metric: 1935.1741
Estimator 32/100, Train metric: 1920.4294
Estimator 33/100, Train metric: 1896.4294
Estimator 34/100, Train metric: 1873.3309
Estimator 35/100, Train metric: 1851.2507
Estimator 36/100, Train metric: 1829.4674
Estimator 37/100, Train metric: 1813.7656
Estimator 38/100, Train metric: 1797.6130
Estimator 39/100, Train metric: 1775.9136
Estimator 40/100, Train metric: 1758.0264
Estimator 41/100, Train metric: 1741.8899
Estimator 42/100, Train metric: 1724.9580
Estimator 43/100, Train metric: 1710.4447
Estimator 44/100, Train metric: 1694.0916
Estimator 45/100, Train metric: 1680.3661
Estimator 46/100, Train metric: 1670.0924
Estimator 47/100, Train metric: 1662.7692
Estimator 48/100, Train metric: 1650.2944
Estimator 49/100, Train metric: 1638.6040
Estimator 50/100, Train metric: 1629.4521
Estimator 51/100, Train metric: 1619.5231
Estimator 52/100, Train metric: 1609.9492
Estimator 53/100, Train metric: 1602.8743
Estimator 54/100, Train metric: 1593.3655
Estimator 55/100, Train metric: 1583.1804
Estimator 56/100, Train metric: 1576.3086
Estimator 57/100, Train metric: 1566.7157
Estimator 58/100, Train metric: 1562.3651
Estimator 59/100, Train metric: 1555.2355
Estimator 60/100, Train metric: 1546.9629
Estimator 61/100, Train metric: 1536.4408
Estimator 62/100, Train metric: 1531.8756
Estimator 63/100, Train metric: 1521.7721
Estimator 64/100, Train metric: 1517.0870
Estimator 65/100, Train metric: 1515.4048
Estimator 66/100, Train metric: 1509.0347
Estimator 67/100, Train metric: 1502.3914
Estimator 68/100, Train metric: 1497.5681
Estimator 69/100, Train metric: 1493.7141
Estimator 70/100, Train metric: 1487.8761
Estimator 71/100, Train metric: 1484.5349
Estimator 72/100, Train metric: 1480.9987
Estimator 73/100, Train metric: 1478.3987
Estimator 74/100, Train metric: 1476.4568
Estimator 75/100, Train metric: 1469.8336
Estimator 76/100, Train metric: 1462.7859
Estimator 77/100, Train metric: 1457.7114
Estimator 78/100, Train metric: 1452.3585
Estimator 79/100, Train metric: 1445.4978
Estimator 80/100, Train metric: 1441.7437
Estimator 81/100, Train metric: 1435.5977
Estimator 82/100, Train metric: 1432.6139
Estimator 83/100, Train metric: 1428.1104
Estimator 84/100, Train metric: 1425.6309
Estimator 85/100, Train metric: 1422.3254
Estimator 86/100, Train metric: 1420.8418
Estimator 87/100, Train metric: 1417.0265
Estimator 88/100, Train metric: 1413.9584
Estimator 89/100, Train metric: 1411.3086
Estimator 90/100, Train metric: 1407.7161
Estimator 91/100, Train metric: 1405.5426
Estimator 92/100, Train metric: 1402.1517
Estimator 93/100, Train metric: 1399.7772
Estimator 94/100, Train metric: 1398.0017
Estimator 95/100, Train metric: 1396.5588
Estimator 96/100, Train metric: 1394.9485
Estimator 97/100, Train metric: 1392.0503
Estimator 98/100, Train metric: 1387.9907
Estimator 99/100, Train metric: 1384.8403
Training on CPU
Estimator 0/100, Train metric: 4505.8145
Estimator 1/100, Train metric: 4426.6680
Estimator 2/100, Train metric: 4363.1045
Estimator 3/100, Train metric: 4285.3857
Estimator 4/100, Train metric: 4239.5610
Estimator 5/100, Train metric: 4174.0654
Estimator 6/100, Train metric: 4121.6133
Estimator 7/100, Train metric: 4056.7979
Estimator 8/100, Train metric: 3996.7112
Estimator 9/100, Train metric: 3955.9080
Estimator 10/100, Train metric: 3900.7964
Estimator 11/100, Train metric: 3860.4448
Estimator 12/100, Train metric: 3811.8701
Estimator 13/100, Train metric: 3783.1602
Estimator 14/100, Train metric: 3755.8848
Estimator 15/100, Train metric: 3709.6758
Estimator 16/100, Train metric: 3665.9705
Estimator 17/100, Train metric: 3622.2278
Estimator 18/100, Train metric: 3603.8105
Estimator 19/100, Train metric: 3564.3962
Estimator 20/100, Train metric: 3530.0393
Estimator 21/100, Train metric: 3492.9651
Estimator 22/100, Train metric: 3457.1001
Estimator 23/100, Train metric: 3424.7437
Estimator 24/100, Train metric: 3404.6501
Estimator 25/100, Train metric: 3382.4421
Estimator 26/100, Train metric: 3353.6062
Estimator 27/100, Train metric: 3332.0730
Estimator 28/100, Train metric: 3306.2024
Estimator 29/100, Train metric: 3283.8333
Estimator 30/100, Train metric: 3275.8579
Estimator 31/100, Train metric: 3252.7214
Estimator 32/100, Train metric: 3237.4963
Estimator 33/100, Train metric: 3223.5181
Estimator 34/100, Train metric: 3210.1086
Estimator 35/100, Train metric: 3192.5198
Estimator 36/100, Train metric: 3182.8425
Estimator 37/100, Train metric: 3172.3774
Estimator 38/100, Train metric: 3161.7959
Estimator 39/100, Train metric: 3147.4390
Estimator 40/100, Train metric: 3136.0750
Estimator 41/100, Train metric: 3120.3501
Estimator 42/100, Train metric: 3114.7002
Estimator 43/100, Train metric: 3115.1765
Estimator 44/100, Train metric: 3108.5247
Estimator 45/100, Train metric: 3101.5225
Estimator 46/100, Train metric: 3095.0608
Estimator 47/100, Train metric: 3082.0833
Estimator 48/100, Train metric: 3073.7712
Estimator 49/100, Train metric: 3061.6772
Estimator 50/100, Train metric: 3056.5627
Estimator 51/100, Train metric: 3047.5776
Estimator 52/100, Train metric: 3038.8477
Estimator 53/100, Train metric: 3027.5923
Estimator 54/100, Train metric: 3030.4653
Estimator 55/100, Train metric: 3021.1514
Estimator 56/100, Train metric: 3013.0200
Estimator 57/100, Train metric: 3006.5122
Estimator 58/100, Train metric: 3002.4407
Estimator 59/100, Train metric: 2993.7021
Estimator 60/100, Train metric: 2988.3396
Estimator 61/100, Train metric: 2985.1777
Estimator 62/100, Train metric: 2979.3347
Estimator 63/100, Train metric: 2972.3254
Estimator 64/100, Train metric: 2967.9502
Estimator 65/100, Train metric: 2959.4958
Estimator 66/100, Train metric: 2954.0796
Estimator 67/100, Train metric: 2949.8748
Estimator 68/100, Train metric: 2944.0830
Estimator 69/100, Train metric: 2928.2205
Estimator 70/100, Train metric: 2924.1768
Estimator 71/100, Train metric: 2909.2051
Estimator 72/100, Train metric: 2901.2427
Estimator 73/100, Train metric: 2894.0957
Estimator 74/100, Train metric: 2888.6133
Estimator 75/100, Train metric: 2886.0061
Estimator 76/100, Train metric: 2883.6038
Estimator 77/100, Train metric: 2877.6492
Estimator 78/100, Train metric: 2873.9255
Estimator 79/100, Train metric: 2867.4412
Estimator 80/100, Train metric: 2864.1538
Estimator 81/100, Train metric: 2861.2388
Estimator 82/100, Train metric: 2853.8564
Estimator 83/100, Train metric: 2842.4465
Estimator 84/100, Train metric: 2838.8367
Estimator 85/100, Train metric: 2835.9316
Estimator 86/100, Train metric: 2828.4597
Estimator 87/100, Train metric: 2821.0830
Estimator 88/100, Train metric: 2813.5723
Estimator 89/100, Train metric: 2810.7988
Estimator 90/100, Train metric: 2799.8560
Estimator 91/100, Train metric: 2796.9592
Estimator 92/100, Train metric: 2793.4536
Estimator 93/100, Train metric: 2787.0798
Estimator 94/100, Train metric: 2780.2268
Estimator 95/100, Train metric: 2774.1428
Estimator 96/100, Train metric: 2770.5095
Estimator 97/100, Train metric: 2763.1221
Estimator 98/100, Train metric: 2751.8777
Estimator 99/100, Train metric: 2748.5444
Training on CPU
Estimator 0/100, Train metric: 4549.6118
Estimator 1/100, Train metric: 4451.5718
Estimator 2/100, Train metric: 4350.7388
Estimator 3/100, Train metric: 4262.0288
Estimator 4/100, Train metric: 4167.4980
Estimator 5/100, Train metric: 4109.7866
Estimator 6/100, Train metric: 4031.9346
Estimator 7/100, Train metric: 3945.2090
Estimator 8/100, Train metric: 3863.2917
Estimator 9/100, Train metric: 3795.4226
Estimator 10/100, Train metric: 3723.1191
Estimator 11/100, Train metric: 3665.8452
Estimator 12/100, Train metric: 3615.3481
Estimator 13/100, Train metric: 3554.1567
Estimator 14/100, Train metric: 3489.0723
Estimator 15/100, Train metric: 3434.5176
Estimator 16/100, Train metric: 3371.8484
Estimator 17/100, Train metric: 3314.3262
Estimator 18/100, Train metric: 3266.1965
Estimator 19/100, Train metric: 3231.2668
Estimator 20/100, Train metric: 3180.0273
Estimator 21/100, Train metric: 3135.9172
Estimator 22/100, Train metric: 3090.0027
Estimator 23/100, Train metric: 3045.7039
Estimator 24/100, Train metric: 2995.2473
Estimator 25/100, Train metric: 2960.6436
Estimator 26/100, Train metric: 2932.8047
Estimator 27/100, Train metric: 2897.3240
Estimator 28/100, Train metric: 2862.8086

In [62]:
def conformal_predictions_online_super_PGBM(
    model_class,
    model_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name="PGBM",
    excel_file_path=None,
    alpha=0.05,
    strategies="all",
    window_min=50,
    window_max=500,
    window_grid=(25, 50, 100, 200, 400),
    n_bootstrap=30,
    seed=123,
):

    warnings.filterwarnings("ignore")
    np.random.seed(seed)

    STRATEGIES = {
        "Online-Split": "Online Split",
        "Online-CV+": "Online CV+",
        "Online-J+aB": "Online Jackknife+ aB",
        "SAOCP": "SAOCP",
        "SF-OGD": "SF-OGD",
        "FACI": "FACI",
        "MFCS-Split": "MFCS Split",
        "MFCS-Full": "MFCS Full",
    }

    if strategies == "all":
        strategies = list(STRATEGIES.keys())

    # --------------------------------------------------------
    # Safe NumPy conversion (PGBM-specific)
    # --------------------------------------------------------
    Xtr = X_train.to_numpy() if hasattr(X_train, "to_numpy") else np.asarray(X_train)
    Xte = X_test.to_numpy() if hasattr(X_test, "to_numpy") else np.asarray(X_test)
    ytr = to_numpy_1d(y_train)
    yte = to_numpy_1d(y_test)

    # --------------------------------------------------------
    # Base model (trained once)
    # --------------------------------------------------------
    base_model = model_class(**model_params)
    base_model.fit(Xtr, ytr)

    yhat_train = base_model.predict(Xtr)

    # --------------------------------------------------------
    # Streaming predictions
    # --------------------------------------------------------
    X_all = np.vstack([Xtr, Xte])
    y_all = np.concatenate([ytr, yte])

    n_train = len(Xtr)
    T = len(y_all)

    y_hat_all = np.zeros(T)
    y_hat_all[:n_train] = yhat_train

    for t in range(n_train, T):
        y_hat_all[t] = base_model.predict(X_all[t:t + 1])[0]

    residuals = np.abs(y_all - y_hat_all)

    y_pred, int_pred = {}, {}

    # ========================================================
    # Online Split
    # ========================================================
    if "Online-Split" in strategies:
        q = np.quantile(residuals[:n_train], 1 - alpha)
        y_pred["Online-Split"] = y_hat_all[n_train:]
        int_pred["Online-Split"] = np.c_[y_pred["Online-Split"] - q,
                                          y_pred["Online-Split"] + q]

    # ========================================================
    # Online CV+
    # ========================================================
    if "Online-CV+" in strategies:
        lower, upper = [], []
        for t in range(n_train, T):
            q = np.quantile(residuals[:t], 1 - alpha)
            lower.append(y_hat_all[t] - q)
            upper.append(y_hat_all[t] + q)
        y_pred["Online-CV+"] = y_hat_all[n_train:]
        int_pred["Online-CV+"] = np.c_[lower, upper]

    # ========================================================
    # Online Jackknife+ aB
    # ========================================================
    if "Online-J+aB" in strategies:
        lowers, uppers, preds = [], [], []
        for _ in range(n_bootstrap):
            idx = np.random.choice(n_train, n_train, replace=True)
            m = model_class(**model_params)
            m.fit(Xtr[idx], ytr[idx])

            q = np.quantile(np.abs(ytr[idx] - m.predict(Xtr[idx])), 1 - alpha)
            p = m.predict(Xte)

            preds.append(p)
            lowers.append(p - q)
            uppers.append(p + q)

        y_pred["Online-J+aB"] = np.mean(preds, axis=0)
        int_pred["Online-J+aB"] = np.c_[np.min(lowers, axis=0),
                                        np.max(uppers, axis=0)]

    # ========================================================
    # SAOCP
    # ========================================================
    if "SAOCP" in strategies:
        lower, upper = [], []
        for t in range(n_train, T):
            w = min(max(window_min, t // 2), window_max)
            start = max(0, t - w)
            q = np.quantile(residuals[start:t], 1 - alpha)
            lower.append(y_hat_all[t] - q)
            upper.append(y_hat_all[t] + q)
        y_pred["SAOCP"] = y_hat_all[n_train:]
        int_pred["SAOCP"] = np.c_[lower, upper]

    # ========================================================
    # SF-OGD
    # ========================================================
    if "SF-OGD" in strategies:
        q_t = np.quantile(residuals[:n_train], 1 - alpha)
        lower, upper = [], []
        for t in range(n_train, T):
            grad = alpha - (residuals[t] <= q_t)
            eta = 1.0 / np.sqrt(t - n_train + 1)
            q_t = max(0.0, q_t - eta * grad)
            lower.append(y_hat_all[t] - q_t)
            upper.append(y_hat_all[t] + q_t)
        y_pred["SF-OGD"] = y_hat_all[n_train:]
        int_pred["SF-OGD"] = np.c_[lower, upper]

    # ========================================================
    # FACI
    # ========================================================
    if "FACI" in strategies:
        windows = list(window_grid)
        losses = np.zeros(len(windows))
        lower, upper = [], []
        for t in range(n_train, T):
            r_t = residuals[t]
            qs = []
            for i, w in enumerate(windows):
                start = max(0, t - w)
                q = np.quantile(residuals[start:t], 1 - alpha)
                qs.append(q)
                losses[i] += alpha * q + (r_t - q) * (r_t > q)
            q_star = qs[np.argmin(losses)]
            lower.append(y_hat_all[t] - q_star)
            upper.append(y_hat_all[t] + q_star)
        y_pred["FACI"] = y_hat_all[n_train:]
        int_pred["FACI"] = np.c_[lower, upper]

    # ========================================================
    # MFCS-Split ✅ (ADDED)
    # ========================================================
    if "MFCS-Split" in strategies:
        q = np.quantile(residuals[:n_train], 1 - alpha)
        y_pred["MFCS-Split"] = y_hat_all[n_train:]
        int_pred["MFCS-Split"] = np.c_[y_pred["MFCS-Split"] - q,
                                       y_pred["MFCS-Split"] + q]

    # ========================================================
    # MFCS-Full
    # ========================================================
    if "MFCS-Full" in strategies:
        lower, upper, preds = [], [], []
        for t in range(n_train, T):
            m = model_class(**model_params)
            m.fit(X_all[:t], y_all[:t])
            yhat = m.predict(X_all[t:t + 1])[0]
            q = np.quantile(np.abs(y_all[:t] - m.predict(X_all[:t])), 1 - alpha)
            preds.append(yhat)
            lower.append(yhat - q)
            upper.append(yhat + q)
        y_pred["MFCS-Full"] = np.array(preds)
        int_pred["MFCS-Full"] = np.c_[lower, upper]

    # ========================================================
    # Metrics + Summary
    # ========================================================
    summary_rows = []
    values_dict = {}

    print("\n===== ONLINE CP (PGBM) RESULTS =====")

    for s in y_pred:
        ymin, ymax = int_pred[s].T
        yhat = y_pred[s]

        coverage = np.mean((yte >= ymin) & (yte <= ymax))
        width = np.mean(ymax - ymin)
        rmse = np.sqrt(mean_squared_error(yte, yhat))

        print(f"{STRATEGIES[s]} - Coverage: {coverage*100:.3f}% | Width: {width:.3f}")

        summary_rows.append({
            "Strategy": STRATEGIES[s],
            "Coverage": coverage,
            "Width": width,
            "RMSE": rmse,
        })

        values_dict[f"{s}_true"] = yte
        values_dict[f"{s}_pred"] = yhat
        values_dict[f"{s}_lower"] = ymin
        values_dict[f"{s}_upper"] = ymax

    summary_df = pd.DataFrame(summary_rows)
    values_df = pd.DataFrame(values_dict)

    # ========================================================
    # Plotting (SAVE ONLY — NO SHOW)
    # ========================================================
    idx = np.arange(len(yte))
    plot_buffers = {}

    for s in y_pred:
        fig, ax = plt.subplots(figsize=(10, 4))

        ax.scatter(idx, yte, s=10, color="blue", alpha=0.7, label="True")
        ax.fill_between(idx, int_pred[s][:, 0], int_pred[s][:, 1],
                        color="gray", alpha=0.5, label="Prediction interval")
        ax.plot(idx, y_pred[s], color="red", lw=1, label="Predicted mean")

        ax.set_title(f"{STRATEGIES[s]} ({model_name})")
        ax.set_xlabel("Sample Number")
        ax.set_ylabel("Y_Label")
        ax.legend(loc="upper left")

        plt.tight_layout()

        buf = io.BytesIO()
        fig.savefig(buf, format="png")
        buf.seek(0)
        plot_buffers[s] = buf

        plt.close(fig)

    # ========================================================
    # Excel Export (append-safe)
    # ========================================================
    if excel_file_path:
        wb = load_workbook(excel_file_path)

        # ---- Summary ----
        sheet_name = "ONLINECP_PGBM_Summary"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        # ---- Plots ----
        for s, buf in plot_buffers.items():
            img = Image(buf)
            sheet_name = f"ONLINECP_PGBM_Plot_{s}"
            base = sheet_name
            i = 1
            while sheet_name in wb.sheetnames:
                sheet_name = f"{base}_{i}"
                i += 1
            ws = wb.create_sheet(sheet_name)
            ws.add_image(img, "A1")

        # ---- Values ----
        sheet_name = "ONLINECP_PGBM_Values"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        wb.save(excel_file_path)


conformal_predictions_online_super_PGBM(
    model_class=PGBMWrapper,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="PGBM",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/PGBM.xlsx",
    alpha=0.05,
    strategies="all",
)

Streaming output truncated to the last 5000 lines.
Estimator 59/100, Train metric: 2772.8879
Estimator 60/100, Train metric: 2766.6277
Estimator 61/100, Train metric: 2762.8674
Estimator 62/100, Train metric: 2758.8340
Estimator 63/100, Train metric: 2754.9219
Estimator 64/100, Train metric: 2748.6436
Estimator 65/100, Train metric: 2741.9651
Estimator 66/100, Train metric: 2739.0376
Estimator 67/100, Train metric: 2733.5178
Estimator 68/100, Train metric: 2733.2905
Estimator 69/100, Train metric: 2732.7996
Estimator 70/100, Train metric: 2730.2754
Estimator 71/100, Train metric: 2726.4751
Estimator 72/100, Train metric: 2726.7756
Estimator 73/100, Train metric: 2722.3394
Estimator 74/100, Train metric: 2720.0278
Estimator 75/100, Train metric: 2718.6001
Estimator 76/100, Train metric: 2715.8457
Estimator 77/100, Train metric: 2709.8245
Estimator 78/100, Train metric: 2712.2092
Estimator 79/100, Train metric: 2710.1379
Estimator 80/100, Train metric: 2708.1750
Estimator 81/100, Train metric: 2707.3938
Estimator 82/100, Train metric: 2705.3738
Estimator 83/100, Train metric: 2703.2454
Estimator 84/100, Train metric: 2702.2744
Estimator 85/100, Train metric: 2701.9324
Estimator 86/100, Train metric: 2700.2671
Estimator 87/100, Train metric: 2695.1858
Estimator 88/100, Train metric: 2692.2756
Estimator 89/100, Train metric: 2687.8171
Estimator 90/100, Train metric: 2682.9246
Estimator 91/100, Train metric: 2680.9104
Estimator 92/100, Train metric: 2678.8281
Estimator 93/100, Train metric: 2676.5547
Estimator 94/100, Train metric: 2675.5566
Estimator 95/100, Train metric: 2673.5413
Estimator 96/100, Train metric: 2669.6814
Estimator 97/100, Train metric: 2666.5867
Estimator 98/100, Train metric: 2664.5940
Estimator 99/100, Train metric: 2662.0713
Training on CPU
Estimator 0/100, Train metric: 4263.0723
Estimator 1/100, Train metric: 4184.7529
Estimator 2/100, Train metric: 4120.7163
Estimator 3/100, Train metric: 4057.3230
Estimator 4/100, Train metric: 3977.9390
Estimator 5/100, Train metric: 3910.1292
Estimator 6/100, Train metric: 3856.1394
Estimator 7/100, Train metric: 3785.5706
Estimator 8/100, Train metric: 3726.7825
Estimator 9/100, Train metric: 3678.1218
Estimator 10/100, Train metric: 3631.2891
Estimator 11/100, Train metric: 3576.8877
Estimator 12/100, Train metric: 3530.5974
Estimator 13/100, Train metric: 3496.2107
Estimator 14/100, Train metric: 3448.4475
Estimator 15/100, Train metric: 3412.1892
Estimator 16/100, Train metric: 3370.4736
Estimator 17/100, Train metric: 3335.3870
Estimator 18/100, Train metric: 3295.7761
Estimator 19/100, Train metric: 3269.5771
Estimator 20/100, Train metric: 3229.5559
Estimator 21/100, Train metric: 3193.1326
Estimator 22/100, Train metric: 3165.4355
Estimator 23/100, Train metric: 3140.3879
Estimator 24/100, Train metric: 3111.5796
Estimator 25/100, Train metric: 3089.8547
Estimator 26/100, Train metric: 3065.1675
Estimator 27/100, Train metric: 3050.8411
Estimator 28/100, Train metric: 3017.5291
Estimator 29/100, Train metric: 2994.2471
Estimator 30/100, Train metric: 2980.1985
Estimator 31/100, Train metric: 2970.0278
Estimator 32/100, Train metric: 2950.9463
Estimator 33/100, Train metric: 2931.6240
Estimator 34/100, Train metric: 2918.0701
Estimator 35/100, Train metric: 2903.9365
Estimator 36/100, Train metric: 2897.4902
Estimator 37/100, Train metric: 2886.6133
Estimator 38/100, Train metric: 2877.1885
Estimator 39/100, Train metric: 2867.3389
Estimator 40/100, Train metric: 2857.1382
Estimator 41/100, Train metric: 2847.9841
Estimator 42/100, Train metric: 2843.0146
Estimator 43/100, Train metric: 2834.8713
Estimator 44/100, Train metric: 2828.8052
Estimator 45/100, Train metric: 2820.0510
Estimator 46/100, Train metric: 2813.7280
Estimator 47/100, Train metric: 2806.2437
Estimator 48/100, Train metric: 2800.0544
Estimator 49/100, Train metric: 2790.1458
Estimator 50/100, Train metric: 2783.6506
Estimator 51/100, Train metric: 2781.8533
Estimator 52/100, Train metric: 2776.4187
Estimator 53/100, Train metric: 2771.2104
Estimator 54/100, Train metric: 2767.8582
Estimator 55/100, Train metric: 2767.8020
Estimator 56/100, Train metric: 2762.6328
Estimator 57/100, Train metric: 2756.4385
Estimator 58/100, Train metric: 2752.2681
Estimator 59/100, Train metric: 2751.5198
Estimator 60/100, Train metric: 2747.3586
Estimator 61/100, Train metric: 2742.6550
Estimator 62/100, Train metric: 2736.9292
Estimator 63/100, Train metric: 2733.2979
Estimator 64/100, Train metric: 2729.5090
Estimator 65/100, Train metric: 2723.6174
Estimator 66/100, Train metric: 2717.7568
Estimator 67/100, Train metric: 2713.8196
Estimator 68/100, Train metric: 2711.9531
Estimator 69/100, Train metric: 2708.9878
Estimator 70/100, Train metric: 2706.6240
Estimator 71/100, Train metric: 2704.0771
Estimator 72/100, Train metric: 2701.3899
Estimator 73/100, Train metric: 2698.5078
Estimator 74/100, Train metric: 2695.0161
Estimator 75/100, Train metric: 2692.7205
Estimator 76/100, Train metric: 2690.4087
Estimator 77/100, Train metric: 2688.5083
Estimator 78/100, Train metric: 2685.1321
Estimator 79/100, Train metric: 2683.7476
Estimator 80/100, Train metric: 2680.5247
Estimator 81/100, Train metric: 2678.5437
Estimator 82/100, Train metric: 2676.0515
Estimator 83/100, Train metric: 2676.6040
Estimator 84/100, Train metric: 2675.6030
Estimator 85/100, Train metric: 2674.2236
Estimator 86/100, Train metric: 2672.5994
Estimator 87/100, Train metric: 2671.1997
Estimator 88/100, Train metric: 2670.3115
Estimator 89/100, Train metric: 2669.5134
Estimator 90/100, Train metric: 2667.8806
Estimator 91/100, Train metric: 2666.2925
Estimator 92/100, Train metric: 2663.5623
Estimator 93/100, Train metric: 2661.8499
Estimator 94/100, Train metric: 2660.9580
Estimator 95/100, Train metric: 2659.3826
Estimator 96/100, Train metric: 2657.8186
Estimator 97/100, Train metric: 2653.7051
Estimator 98/100, Train metric: 2650.9705
Estimator 99/100, Train metric: 2650.0520
Training on CPU
Estimator 0/100, Train metric: 4261.6167
Estimator 1/100, Train metric: 4174.5977
Estimator 2/100, Train metric: 4094.8840
Estimator 3/100, Train metric: 4027.4048
Estimator 4/100, Train metric: 3957.4109
Estimator 5/100, Train metric: 3901.0469
Estimator 6/100, Train metric: 3844.5476
Estimator 7/100, Train metric: 3801.5828
Estimator 8/100, Train metric: 3740.3875
Estimator 9/100, Train metric: 3682.4465
Estimator 10/100, Train metric: 3655.6511
Estimator 11/100, Train metric: 3599.7756
Estimator 12/100, Train metric: 3563.6045
Estimator 13/100, Train metric: 3521.0181
Estimator 14/100, Train metric: 3480.4968
Estimator 15/100, Train metric: 3441.6404
Estimator 16/100, Train metric: 3401.6050
Estimator 17/100, Train metric: 3356.1123
Estimator 18/100, Train metric: 3316.8159
Estimator 19/100, Train metric: 3276.4375
Estimator 20/100, Train metric: 3244.1035
Estimator 21/100, Train metric: 3214.0276
Estimator 22/100, Train metric: 3181.4780
Estimator 23/100, Train metric: 3163.6816
Estimator 24/100, Train metric: 3145.6663
Estimator 25/100, Train metric: 3125.6611
Estimator 26/100, Train metric: 3100.7151
Estimator 27/100, Train metric: 3082.7214
Estimator 28/100, Train metric: 3065.7280
Estimator 29/100, Train metric: 3047.6047
Estimator 30/100, Train metric: 3025.6753
Estimator 31/100, Train metric: 3013.1294
Estimator 32/100, Train metric: 2994.1379
Estimator 33/100, Train metric: 2985.6045
Estimator 34/100, Train metric: 2971.0784
Estimator 35/100, Train metric: 2959.0835
Estimator 36/100, Train metric: 2947.9436
Estimator 37/100, Train metric: 2930.6152
Estimator 38/100, Train metric: 2913.4248
Estimator 39/100, Train metric: 2903.2800
Estimator 40/100, Train metric: 2897.9739
Estimator 41/100, Train metric: 2884.1074
Estimator 42/100, Train metric: 2878.4678
Estimator 43/100, Train metric: 2876.3445
Estimator 44/100, Train metric: 2864.8230
Estimator 45/100, Train metric: 2853.5171
Estimator 46/100, Train metric: 2848.1328
Estimator 47/100, Train metric: 2838.9446
Estimator 48/100, Train metric: 2827.5793
Estimator 49/100, Train metric: 2823.8762
Estimator 50/100, Train metric: 2816.6575
Estimator 51/100, Train metric: 2808.8108
Estimator 52/100, Train metric: 2799.9875
Estimator 53/100, Train metric: 2793.5447
Estimator 54/100, Train metric: 2790.4946
Estimator 55/100, Train metric: 2784.3472
Estimator 56/100, Train metric: 2777.6821
Estimator 57/100, Train metric: 2774.3308
Estimator 58/100, Train metric: 2768.7852
Estimator 59/100, Train metric: 2764.4429
Estimator 60/100, Train metric: 2758.9424
Estimator 61/100, Train metric: 2754.4778
Estimator 62/100, Train metric: 2751.2659
Estimator 63/100, Train metric: 2750.6174
Estimator 64/100, Train metric: 2744.6382
Estimator 65/100, Train metric: 2738.3062
Estimator 66/100, Train metric: 2734.3440
Estimator 67/100, Train metric: 2730.6797
Estimator 68/100, Train metric: 2728.0115
Estimator 69/100, Train metric: 2724.2673
Estimator 70/100, Train metric: 2722.2917
Estimator 71/100, Train metric: 2718.0286
Estimator 72/100, Train metric: 2713.6631
Estimator 73/100, Train metric: 2712.3708
Estimator 74/100, Train metric: 2709.3772
Estimator 75/100, Train metric: 2705.4272
Estimator 76/100, Train metric: 2703.2434
Estimator 77/100, Train metric: 2700.7468
Estimator 78/100, Train metric: 2698.3896
Estimator 79/100, Train metric: 2693.5015
Estimator 80/100, Train metric: 2690.4250
Estimator 81/100, Train metric: 2688.1909
Estimator 82/100, Train metric: 2685.6641
Estimator 83/100, Train metric: 2683.2598
Estimator 84/100, Train metric: 2679.4741
Estimator 85/100, Train metric: 2676.3452
Estimator 86/100, Train metric: 2674.4910
Estimator 87/100, Train metric: 2671.3647
Estimator 88/100, Train metric: 2669.9526
Estimator 89/100, Train metric: 2668.2690
Estimator 90/100, Train metric: 2667.1648
Estimator 91/100, Train metric: 2665.7981
Estimator 92/100, Train metric: 2665.3481
Estimator 93/100, Train metric: 2662.1741
Estimator 94/100, Train metric: 2660.7603
Estimator 95/100, Train metric: 2659.8181
Estimator 96/100, Train metric: 2657.5996
Estimator 97/100, Train metric: 2656.7090
Estimator 98/100, Train metric: 2655.3716
Estimator 99/100, Train metric: 2653.6262
Training on CPU
Estimator 0/100, Train metric: 4260.1572
Estimator 1/100, Train metric: 4177.0034
Estimator 2/100, Train metric: 4113.8730
Estimator 3/100, Train metric: 4039.4346
Estimator 4/100, Train metric: 3965.5886
Estimator 5/100, Train metric: 3904.9053
Estimator 6/100, Train metric: 3851.8408
Estimator 7/100, Train metric: 3788.7537
Estimator 8/100, Train metric: 3740.8284
Estimator 9/100, Train metric: 3698.0247
Estimator 10/100, Train metric: 3640.4060
Estimator 11/100, Train metric: 3594.3521
Estimator 12/100, Train metric: 3543.1521
Estimator 13/100, Train metric: 3502.0940
Estimator 14/100, Train metric: 3459.3984
Estimator 15/100, Train metric: 3412.6665
Estimator 16/100, Train metric: 3368.1306
Estimator 17/100, Train metric: 3340.5400
Estimator 18/100, Train metric: 3308.1077
Estimator 19/100, Train metric: 3274.6028
Estimator 20/100, Train metric: 3243.5588
Estimator 21/100, Train metric: 3208.2036
Estimator 22/100, Train metric: 3178.9463
Estimator 23/100, Train metric: 3146.5911
Estimator 24/100, Train metric: 3118.5747
Estimator 25/100, Train metric: 3100.9124
Estimator 26/100, Train metric: 3082.8037
Estimator 27/100, Train metric: 3059.6860
Estimator 28/100, Train metric: 3044.0371
Estimator 29/100, Train metric: 3027.0713
Estimator 30/100, Train metric: 3020.0662
Estimator 31/100, Train metric: 3000.5327
Estimator 32/100, Train metric: 2983.1680
Estimator 33/100, Train metric: 2970.6909
Estimator 34/100, Train metric: 2955.6201
Estimator 35/100, Train metric: 2944.7920
Estimator 36/100, Train metric: 2929.1965
Estimator 37/100, Train metric: 2917.4521
Estimator 38/100, Train metric: 2907.7341
Estimator 39/100, Train metric: 2898.6494
Estimator 40/100, Train metric: 2886.2219
Estimator 41/100, Train metric: 2884.5437
Estimator 42/100, Train metric: 2871.3879
Estimator 43/100, Train metric: 2859.3611
Estimator 44/100, Train metric: 2847.1638
Estimator 45/100, Train metric: 2834.2961
Estimator 46/100, Train metric: 2826.0886
Estimator 47/100, Train metric: 2818.6606
Estimator 48/100, Train metric: 2812.3994
Estimator 49/100, Train metric: 2808.8237
Estimator 50/100, Train metric: 2802.3174
Estimator 51/100, Train metric: 2797.0417
Estimator 52/100, Train metric: 2787.8118
Estimator 53/100, Train metric: 2784.8682
Estimator 54/100, Train metric: 2774.7485
Estimator 55/100, Train metric: 2767.5579
Estimator 56/100, Train metric: 2764.9021
Estimator 57/100, Train metric: 2758.5039
Estimator 58/100, Train metric: 2755.2063
Estimator 59/100, Train metric: 2747.9802
Estimator 60/100, Train metric: 2743.7998
Estimator 61/100, Train metric: 2739.8591
Estimator 62/100, Train metric: 2732.8435
Estimator 63/100, Train metric: 2730.4248
Estimator 64/100, Train metric: 2729.2581
Estimator 65/100, Train metric: 2723.9688
Estimator 66/100, Train metric: 2720.9827
Estimator 67/100, Train metric: 2716.1616
Estimator 68/100, Train metric: 2714.2095
Estimator 69/100, Train metric: 2710.0540
Estimator 70/100, Train metric: 2707.6814
Estimator 71/100, Train metric: 2705.5693
Estimator 72/100, Train metric: 2705.5999
Estimator 73/100, Train metric: 2703.4453
Estimator 74/100, Train metric: 2700.0649
Estimator 75/100, Train metric: 2697.3623
Estimator 76/100, Train metric: 2695.3796
Estimator 77/100, Train metric: 2692.2031
Estimator 78/100, Train metric: 2690.7673
Estimator 79/100, Train metric: 2689.9365
Estimator 80/100, Train metric: 2688.7231
Estimator 81/100, Train metric: 2687.7144
Estimator 82/100, Train metric: 2688.4658
Estimator 83/100, Train metric: 2689.4868
Estimator 84/100, Train metric: 2687.6238
Estimator 85/100, Train metric: 2684.0017
Estimator 86/100, Train metric: 2682.1399
Estimator 87/100, Train metric: 2678.8611
Estimator 88/100, Train metric: 2674.5068
Estimator 89/100, Train metric: 2674.8582
Estimator 90/100, Train metric: 2672.0291
Estimator 91/100, Train metric: 2670.0229
Estimator 92/100, Train metric: 2668.0747
Estimator 93/100, Train metric: 2665.1313
Estimator 94/100, Train metric: 2663.7251
Estimator 95/100, Train metric: 2662.3313
Estimator 96/100, Train metric: 2659.7168
Estimator 97/100, Train metric: 2656.2188
Estimator 98/100, Train metric: 2653.9558
Estimator 99/100, Train metric: 2653.1233
Training on CPU
Estimator 0/100, Train metric: 4258.7046
Estimator 1/100, Train metric: 4181.4697
Estimator 2/100, Train metric: 4106.1821
Estimator 3/100, Train metric: 4036.0869
Estimator 4/100, Train metric: 3964.5730
Estimator 5/100, Train metric: 3900.1357
Estimator 6/100, Train metric: 3834.5977
Estimator 7/100, Train metric: 3777.0718
Estimator 8/100, Train metric: 3711.1641
Estimator 9/100, Train metric: 3670.1484
Estimator 10/100, Train metric: 3622.7561
Estimator 11/100, Train metric: 3567.2542
Estimator 12/100, Train metric: 3519.6750
Estimator 13/100, Train metric: 3472.9321
Estimator 14/100, Train metric: 3423.7375
Estimator 15/100, Train metric: 3386.3552
Estimator 16/100, Train metric: 3369.1985
Estimator 17/100, Train metric: 3331.6479
Estimator 18/100, Train metric: 3301.6699
Estimator 19/100, Train metric: 3268.9937
Estimator 20/100, Train metric: 3237.8943
Estimator 21/100, Train metric: 3213.6677
Estimator 22/100, Train metric: 3182.7058
Estimator 23/100, Train metric: 3153.5725
Estimator 24/100, Train metric: 3126.4375
Estimator 25/100, Train metric: 3104.5525
Estimator 26/100, Train metric: 3083.1138
Estimator 27/100, Train metric: 3067.7202
Estimator 28/100, Train metric: 3048.9636
Estimator 29/100, Train metric: 3027.8408
Estimator 30/100, Train metric: 3015.0562
Estimator 31/100, Train metric: 2992.6721
Estimator 32/100, Train metric: 2975.5681
Estimator 33/100, Train metric: 2962.2859
Estimator 34/100, Train metric: 2950.6873
Estimator 35/100, Train metric: 2936.7742
Estimator 36/100, Train metric: 2921.1802
Estimator 37/100, Train metric: 2918.6980
Estimator 38/100, Train metric: 2915.5823
Estimator 39/100, Train metric: 2903.2932
Estimator 40/100, Train metric: 2890.5791
Estimator 41/100, Train metric: 2882.4666
Estimator 42/100, Train metric: 2875.9092
Estimator 43/100, Train metric: 2866.1919
Estimator 44/100, Train metric: 2857.2122
Estimator 45/100, Train metric: 2852.5947
Estimator 46/100, Train metric: 2843.0283
Estimator 47/100, Train metric: 2842.1465
Estimator 48/100, Train metric: 2838.0874
Estimator 49/100, Train metric: 2830.9099
Estimator 50/100, Train metric: 2826.0222
Estimator 51/100, Train metric: 2821.5923
Estimator 52/100, Train metric: 2817.1621
Estimator 53/100, Train metric: 2809.5400
Estimator 54/100, Train metric: 2812.4473
Estimator 55/100, Train metric: 2806.0122
Estimator 56/100, Train metric: 2805.4170
Estimator 57/100, Train metric: 2801.9722
Estimator 58/100, Train metric: 2804.6360
Estimator 59/100, Train metric: 2798.8384
Estimator 60/100, Train metric: 2795.1426
Estimator 61/100, Train metric: 2792.5273
Estimator 62/100, Train metric: 2783.5286
Estimator 63/100, Train metric: 2774.7390
Estimator 64/100, Train metric: 2769.8711
Estimator 65/100, Train metric: 2765.5266
Estimator 66/100, Train metric: 2762.5588
Estimator 67/100, Train metric: 2758.5835
Estimator 68/100, Train metric: 2761.7429
Estimator 69/100, Train metric: 2758.9976
Estimator 70/100, Train metric: 2755.7405
Estimator 71/100, Train metric: 2752.9373
Estimator 72/100, Train metric: 2749.7683
Estimator 73/100, Train metric: 2745.2810
Estimator 74/100, Train metric: 2744.1709
Estimator 75/100, Train metric: 2744.0452
Estimator 76/100, Train metric: 2741.3508
Estimator 77/100, Train metric: 2735.9475
Estimator 78/100, Train metric: 2734.0540
Estimator 79/100, Train metric: 2729.7297
Estimator 80/100, Train metric: 2723.4004
Estimator 81/100, Train metric: 2718.1433
Estimator 82/100, Train metric: 2716.9548
Estimator 83/100, Train metric: 2713.0955
Estimator 84/100, Train metric: 2710.6763
Estimator 85/100, Train metric: 2707.1160
Estimator 86/100, Train metric: 2705.1099
Estimator 87/100, Train metric: 2701.0874
Estimator 88/100, Train metric: 2697.5627
Estimator 89/100, Train metric: 2693.5393
Estimator 90/100, Train metric: 2691.5945
Estimator 91/100, Train metric: 2689.7131
Estimator 92/100, Train metric: 2687.8264
Estimator 93/100, Train metric: 2684.1318
Estimator 94/100, Train metric: 2680.9790
Estimator 95/100, Train metric: 2678.2332
Estimator 96/100, Train metric: 2675.4448
Estimator 97/100, Train metric: 2671.5503
Estimator 98/100, Train metric: 2668.7036
Estimator 99/100, Train metric: 2667.4417
Training on CPU
Estimator 0/100, Train metric: 4257.7510
Estimator 1/100, Train metric: 4179.5435
Estimator 2/100, Train metric: 4096.5513
Estimator 3/100, Train metric: 4019.5967
Estimator 4/100, Train metric: 3958.9910
Estimator 5/100, Train metric: 3883.5740
Estimator 6/100, Train metric: 3815.4368
Estimator 7/100, Train metric: 3771.3289
Estimator 8/100, Train metric: 3713.3267
Estimator 9/100, Train metric: 3661.4995
Estimator 10/100, Train metric: 3623.5413
Estimator 11/100, Train metric: 3583.3752
Estimator 12/100, Train metric: 3534.2395
Estimator 13/100, Train metric: 3483.2380
Estimator 14/100, Train metric: 3437.8801
Estimator 15/100, Train metric: 3403.0459
Estimator 16/100, Train metric: 3369.6172
Estimator 17/100, Train metric: 3331.9534
Estimator 18/100, Train metric: 3295.8572
Estimator 19/100, Train metric: 3267.8381
Estimator 20/100, Train metric: 3236.3752
Estimator 21/100, Train metric: 3214.8625
Estimator 22/100, Train metric: 3187.2295
Estimator 23/100, Train metric: 3163.7075
Estimator 24/100, Train metric: 3133.0354
Estimator 25/100, Train metric: 3113.0405
Estimator 26/100, Train metric: 3093.4436
Estimator 27/100, Train metric: 3065.9807
Estimator 28/100, Train metric: 3042.7720
Estimator 29/100, Train metric: 3028.7200
Estimator 30/100, Train metric: 3007.6912
Estimator 31/100, Train metric: 2999.4470
Estimator 32/100, Train metric: 2995.0898

In [63]:
def conformal_predictions_COP_PGBM(
    model_class,
    model_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name="PGBM",
    excel_file_path=None,
    alpha=0.05,
    lr=0.05,
    T_burnin=50,
    scale=0.5,
    random_state=123,
):

    warnings.filterwarnings("ignore")
    np.random.seed(random_state)

    # =========================================================
    # Safe NumPy conversion (PGBM-specific)
    # =========================================================
    Xtr = X_train.to_numpy() if hasattr(X_train, "to_numpy") else np.asarray(X_train)
    Xte = X_test.to_numpy() if hasattr(X_test, "to_numpy") else np.asarray(X_test)
    ytr = to_numpy_1d(y_train)
    yte = to_numpy_1d(y_test)

    # =========================================================
    # Train base PGBM model
    # =========================================================
    model = model_class(**model_params)
    model.fit(Xtr, ytr)

    y_pred_test = model.predict(Xte).ravel()
    y_pred_train = model.predict(Xtr).ravel()

    # Absolute residuals (symmetric COP)
    scores_test = np.abs(yte - y_pred_test)
    scores_train = np.abs(ytr - y_pred_train)

    T_test = len(scores_test)

    # =========================================================
    # COP initialization
    # =========================================================
    init_q = np.quantile(scores_train, 1 - alpha)

    qs = np.zeros(T_test)
    qts = np.zeros(T_test)
    integrators = np.zeros(T_test)
    covereds = np.zeros(T_test)

    qs[0] = init_q
    qts[0] = init_q

    # =========================================================
    # Online COP loop
    # =========================================================
    for t in range(T_test - 1):

        covereds[t] = 1 if qs[t] >= scores_test[t] else 0

        # Standard COP gradient
        grad = alpha if covereds[t] else -(1 - alpha)

        # Distribution-informed (optimistic) gradient
        if t < T_burnin:
            grad_i = 0.0
        else:
            window_s = scores_test[t - T_burnin : t]
            target = qts[t] - lr * grad
            grad_i = np.mean(window_s <= target) - (1 - alpha)

        # Updates
        integrator = -scale * grad_i
        qts[t + 1] = qts[t] - lr * grad
        integrators[t + 1] = lr * integrator
        qs[t + 1] = max(0.0, qts[t + 1] + integrators[t + 1])

    covereds[-1] = 1 if qs[-1] >= scores_test[-1] else 0

    # =========================================================
    # Prediction intervals
    # =========================================================
    ymin = y_pred_test - qs
    ymax = y_pred_test + qs

    # =========================================================
    # Metrics
    # =========================================================
    rmse = np.sqrt(mean_squared_error(yte, y_pred_test))
    coverage = np.mean(covereds)
    avg_width = np.mean(ymax - ymin)

    print(f"\n===== COP (PGBM) =====")
    print(f"Coverage : {coverage*100:.3f}%")
    print(f"Width    : {avg_width:.3f}")
    print(f"RMSE     : {rmse:.3f}")
    print(f"Final q  : {qs[-1]:.3f}")

    # =========================================================
    # Tables
    # =========================================================
    summary_df = pd.DataFrame([{
        "Strategy": "COP",
        "Coverage": coverage,
        "Width": avg_width,
        "RMSE": rmse,
        "Alpha": alpha,
        "LR": lr,
        "Scale": scale,
    }])

    values_df = pd.DataFrame({
        "sample_index": np.arange(len(yte)),
        "y_true": yte,
        "y_pred": y_pred_test,
        "ymin": ymin,
        "ymax": ymax,
        "width": ymax - ymin,
        "is_covered": covereds.astype(int),
        "score": scores_test,
        "adaptive_q": qs,
    })

    # =========================================================
    # Plot (SAVE ONLY)
    # =========================================================
    idx = np.arange(len(yte))
    fig, ax = plt.subplots(figsize=(10, 4))

    ax.scatter(idx, yte, s=10, color="blue", alpha=0.7, label="True")
    ax.fill_between(idx, ymin, ymax, color="gray", alpha=0.5, label="COP Interval")
    ax.plot(idx, y_pred_test, color="red", lw=1, label="Predicted mean")


    ax.set_title(f"COP ({model_name})")
    ax.set_xlabel("Sample Number")
    ax.set_ylabel("Y_Label")
    ax.legend(loc="upper left")

    plt.tight_layout()
    buf = io.BytesIO()
    fig.savefig(buf, format="png")
    buf.seek(0)
    plt.close(fig)

    # =========================================================
    # Excel export (append-safe)
    # =========================================================
    if excel_file_path:
        wb = load_workbook(excel_file_path)

        # ---- Summary ----
        sheet_name = "COP_PGBM_Summary"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        # ---- Plot ----
        img = Image(buf)
        sheet_name = "COP_PGBM_Plot"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1
        ws = wb.create_sheet(sheet_name)
        ws.add_image(img, "A1")

        # ---- Values ----
        sheet_name = "COP_PGBM_Values"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        wb.save(excel_file_path)

    return summary_df

conformal_predictions_COP_PGBM(
    model_class=PGBMWrapper,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="PGBM",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/PGBM.xlsx",
    alpha=0.05,
)

Training on CPU
Estimator 0/100, Train metric: 4785.5781
Estimator 1/100, Train metric: 4716.0503
Estimator 2/100, Train metric: 4644.9238
Estimator 3/100, Train metric: 4567.3071
Estimator 4/100, Train metric: 4485.7036
Estimator 5/100, Train metric: 4414.1963
Estimator 6/100, Train metric: 4342.2041
Estimator 7/100, Train metric: 4294.3203
Estimator 8/100, Train metric: 4232.3247
Estimator 9/100, Train metric: 4175.2485
Estimator 10/100, Train metric: 4117.8438
Estimator 11/100, Train metric: 4074.5427
Estimator 12/100, Train metric: 4027.6052
Estimator 13/100, Train metric: 3969.5894
Estimator 14/100, Train metric: 3934.0879
Estimator 15/100, Train metric: 3884.0276
Estimator 16/100, Train metric: 3849.3979
Estimator 17/100, Train metric: 3796.5886
Estimator 18/100, Train metric: 3756.7878
Estimator 19/100, Train metric: 3707.1123
Estimator 20/100, Train metric: 3662.5784
Estimator 21/100, Train metric: 3627.9343
Estimator 22/100, Train metric: 3589.0693
Estimator 23/100, Train metric: 3559.3635
Estimator 24/100, Train metric: 3519.8503
Estimator 25/100, Train metric: 3486.7107
Estimator 26/100, Train metric: 3455.1050
Estimator 27/100, Train metric: 3425.0452
Estimator 28/100, Train metric: 3410.2742
Estimator 29/100, Train metric: 3380.3259
Estimator 30/100, Train metric: 3368.2126
Estimator 31/100, Train metric: 3338.4089
Estimator 32/100, Train metric: 3314.2478
Estimator 33/100, Train metric: 3298.9172
Estimator 34/100, Train metric: 3274.0374
Estimator 35/100, Train metric: 3259.7502
Estimator 36/100, Train metric: 3242.4282
Estimator 37/100, Train metric: 3222.9932
Estimator 38/100, Train metric: 3209.1711
Estimator 39/100, Train metric: 3196.1951
Estimator 40/100, Train metric: 3181.8035
Estimator 41/100, Train metric: 3170.4497
Estimator 42/100, Train metric: 3156.1653
Estimator 43/100, Train metric: 3139.1514
Estimator 44/100, Train metric: 3124.4719
Estimator 45/100, Train metric: 3112.9504
Estimator 46/100, Train metric: 3102.4482
Estimator 47/100, Train metric: 3091.2197
Estimator 48/100, Train metric: 3077.9343
Estimator 49/100, Train metric: 3065.4868
Estimator 50/100, Train metric: 3069.4087
Estimator 51/100, Train metric: 3057.7764
Estimator 52/100, Train metric: 3047.5630
Estimator 53/100, Train metric: 3035.9792
Estimator 54/100, Train metric: 3026.7917
Estimator 55/100, Train metric: 3020.9639
Estimator 56/100, Train metric: 3010.0757
Estimator 57/100, Train metric: 3005.9148
Estimator 58/100, Train metric: 3001.2415
Estimator 59/100, Train metric: 2995.9473
Estimator 60/100, Train metric: 2985.3713
Estimator 61/100, Train metric: 2980.9819
Estimator 62/100, Train metric: 2975.9624
Estimator 63/100, Train metric: 2971.2502
Estimator 64/100, Train metric: 2966.4805
Estimator 65/100, Train metric: 2960.4290
Estimator 66/100, Train metric: 2957.1323
Estimator 67/100, Train metric: 2950.0166
Estimator 68/100, Train metric: 2945.8262
Estimator 69/100, Train metric: 2941.5364
Estimator 70/100, Train metric: 2939.0271
Estimator 71/100, Train metric: 2934.4133
Estimator 72/100, Train metric: 2930.0994
Estimator 73/100, Train metric: 2926.9014
Estimator 74/100, Train metric: 2922.0410
Estimator 75/100, Train metric: 2919.2212
Estimator 76/100, Train metric: 2915.2844
Estimator 77/100, Train metric: 2913.6797
Estimator 78/100, Train metric: 2912.4202
Estimator 79/100, Train metric: 2908.8772
Estimator 80/100, Train metric: 2904.2393
Estimator 81/100, Train metric: 2900.8198
Estimator 82/100, Train metric: 2898.2141
Estimator 83/100, Train metric: 2896.2488
Estimator 84/100, Train metric: 2894.7161
Estimator 85/100, Train metric: 2891.2788
Estimator 86/100, Train metric: 2889.5957
Estimator 87/100, Train metric: 2888.5396
Estimator 88/100, Train metric: 2885.8940
Estimator 89/100, Train metric: 2882.8940
Estimator 90/100, Train metric: 2881.8862
Estimator 91/100, Train metric: 2878.5588
Estimator 92/100, Train metric: 2875.9741
Estimator 93/100, Train metric: 2872.4604
Estimator 94/100, Train metric: 2870.9814
Estimator 95/100, Train metric: 2870.4788
Estimator 96/100, Train metric: 2871.1038
Estimator 97/100, Train metric: 2867.2288
Estimator 98/100, Train metric: 2864.3069
Estimator 99/100, Train metric: 2864.2512

===== COP (PGBM) =====
Coverage : 98.356%
Width    : 2375.862
RMSE     : 294.573
Final q  : 1187.681

  Strategy  Coverage        Width        RMSE  Alpha    LR  Scale
0      COP  0.983562  2375.861746  294.573016   0.05  0.05    0.5

In [64]:
def conformal_predictions_EXTREME_PGBM(
    model_class,
    model_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name="PGBM",
    excel_file_path=None,
    alpha=0.05,
    calib_size=0.2,
    gpd_threshold_quantile=0.95,
    n_bootstrap=30,
    random_state=123,
):

    warnings.filterwarnings("ignore")
    np.random.seed(random_state)

    # --------------------------------------------------------
    # Safe NumPy conversion (PGBM-specific)
    # --------------------------------------------------------
    Xtr = X_train.to_numpy() if hasattr(X_train, "to_numpy") else np.asarray(X_train)
    Xte = X_test.to_numpy() if hasattr(X_test, "to_numpy") else np.asarray(X_test)
    ytr = to_numpy_1d(y_train)
    yte = to_numpy_1d(y_test)

    # --------------------------------------------------------
    # Train / calibration split
    # --------------------------------------------------------
    X_fit, X_cal, y_fit, y_cal = train_test_split(
        Xtr, ytr, test_size=calib_size, random_state=random_state, shuffle=True
    )

    # --------------------------------------------------------
    # Train model
    # --------------------------------------------------------
    model = model_class(**model_params)
    model.fit(X_fit, y_fit)

    y_pred_test = model.predict(Xte)
    y_pred_cal = model.predict(X_cal)

    # --------------------------------------------------------
    # Upper-tail nonconformity scores
    # --------------------------------------------------------
    scores = y_cal - y_pred_cal
    scores = scores[scores > 0]

    if len(scores) < 30:
        raise RuntimeError("Too few exceedances for EVT fitting.")

    # --------------------------------------------------------
    # Peaks-over-threshold
    # --------------------------------------------------------
    u = np.quantile(scores, gpd_threshold_quantile)
    excesses = scores[scores > u] - u

    # --------------------------------------------------------
    # Bootstrap EVT quantile
    # --------------------------------------------------------
    boot_q = []
    n_exc = len(excesses)
    n_scores = len(scores)

    for _ in range(n_bootstrap):
        res = np.random.choice(excesses, size=n_exc, replace=True)
        xi, _, sigma = genpareto.fit(res, floc=0)
        q = u + (sigma / xi) * ((n_scores / (n_scores * alpha)) ** xi - 1)
        boot_q.append(q)

    q_extreme = np.quantile(boot_q, 0.95)

    # --------------------------------------------------------
    # FINITE prediction intervals (for plotting & width)
    # --------------------------------------------------------
    ymin = y_pred_test - q_extreme
    ymax = y_pred_test + q_extreme

    # --------------------------------------------------------
    # Metrics (one-sided coverage)
    # --------------------------------------------------------
    rmse = np.sqrt(mean_squared_error(yte, y_pred_test))
    coverage = np.mean(yte <= ymax)
    width = q_extreme

    print(f"\n===== EXTREME CP (PGBM) =====")
    print(f"Coverage     : {coverage*100:.3f}%")
    print(f"Width        : {width:.3f}")
    print(f"RMSE         : {rmse:.3f}")
    print(f"q_extreme    : {q_extreme:.3f}")
    print(f"threshold_u  : {u:.3f}")
    print(f"#Exceedances : {len(scores)}")

    # --------------------------------------------------------
    # Summary table
    # --------------------------------------------------------
    summary_df = pd.DataFrame([{
        "Strategy": "EXTREME CP",
        "Coverage": coverage,
        "Width": width,
        "RMSE": rmse,
        "q_extreme": q_extreme,
        "threshold_u": u,
        "n_exceedances": len(scores),
    }])

    # --------------------------------------------------------
    # Values table
    # --------------------------------------------------------
    values_df = pd.DataFrame({
        "sample_index": np.arange(len(yte)),
        "y_true": yte,
        "y_pred": y_pred_test,
        "ymin": ymin,
        "ymax": ymax,
        "width": ymax - ymin,
        "is_covered": (yte <= ymax).astype(int),
        "residual": yte - y_pred_test,
    })

    # --------------------------------------------------------
    # Plot (SAVE ONLY — NO SHOW)
    # --------------------------------------------------------
    idx = np.arange(len(yte))
    fig, ax = plt.subplots(figsize=(10, 4))

    ax.scatter(idx, yte, s=10, color="blue", alpha=0.7, label="True")
    ax.fill_between(idx, ymin, ymax, alpha=0.4, label="Extreme PI")
    ax.plot(idx, y_pred_test, color="red", lw=1, label="Prediction")

    ax.set_title(f"Extreme CP ({model_name})")
    ax.set_xlabel("Sample Number")
    ax.set_ylabel("Y_Label")
    ax.legend(loc="upper left")

    plt.tight_layout()

    buf = io.BytesIO()
    fig.savefig(buf, format="png")
    buf.seek(0)
    plt.close(fig)

    # --------------------------------------------------------
    # Excel export (append-safe)
    # --------------------------------------------------------
    if excel_file_path:
        wb = load_workbook(excel_file_path)

        # ---- Summary ----
        sheet_name = "EXTREMECP_PGBM_Summary"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        # ---- Plot ----
        img = Image(buf)
        sheet_name = "EXTREMECP_PGBM_Plot"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        ws.add_image(img, "A1")

        # ---- Values ----
        sheet_name = "EXTREMECP_PGBM_Values"
        base = sheet_name
        i = 1
        while sheet_name in wb.sheetnames:
            sheet_name = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet_name)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        wb.save(excel_file_path)


conformal_predictions_EXTREME_PGBM(
    model_class=PGBMWrapper,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="PGBM",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/PGBM.xlsx",
    alpha=0.05,
    calib_size=0.3,
)

Training on CPU
Estimator 0/100, Train metric: 3687.8215
Estimator 1/100, Train metric: 3616.4719
Estimator 2/100, Train metric: 3548.6990
Estimator 3/100, Train metric: 3487.7852
Estimator 4/100, Train metric: 3425.4285
Estimator 5/100, Train metric: 3358.4795
Estimator 6/100, Train metric: 3289.9182
Estimator 7/100, Train metric: 3232.6841
Estimator 8/100, Train metric: 3179.0618
Estimator 9/100, Train metric: 3135.1797
Estimator 10/100, Train metric: 3085.3516
Estimator 11/100, Train metric: 3041.4097
Estimator 12/100, Train metric: 2997.4175
Estimator 13/100, Train metric: 2956.7327
Estimator 14/100, Train metric: 2906.3018
Estimator 15/100, Train metric: 2866.7585
Estimator 16/100, Train metric: 2830.5815
Estimator 17/100, Train metric: 2789.9539
Estimator 18/100, Train metric: 2762.1133
Estimator 19/100, Train metric: 2731.7229
Estimator 20/100, Train metric: 2694.6108
Estimator 21/100, Train metric: 2651.9536
Estimator 22/100, Train metric: 2617.9211
Estimator 23/100, Train metric: 2582.7930
Estimator 24/100, Train metric: 2548.9919
Estimator 25/100, Train metric: 2528.9045
Estimator 26/100, Train metric: 2505.1191
Estimator 27/100, Train metric: 2477.0527
Estimator 28/100, Train metric: 2447.2661
Estimator 29/100, Train metric: 2430.2773
Estimator 30/100, Train metric: 2413.9333
Estimator 31/100, Train metric: 2399.0010
Estimator 32/100, Train metric: 2382.8289
Estimator 33/100, Train metric: 2372.0083
Estimator 34/100, Train metric: 2351.2463
Estimator 35/100, Train metric: 2325.1851
Estimator 36/100, Train metric: 2308.5811
Estimator 37/100, Train metric: 2300.8452
Estimator 38/100, Train metric: 2278.0642
Estimator 39/100, Train metric: 2251.2200
Estimator 40/100, Train metric: 2243.6885
Estimator 41/100, Train metric: 2234.0303
Estimator 42/100, Train metric: 2222.9216
Estimator 43/100, Train metric: 2218.8677
Estimator 44/100, Train metric: 2212.0400
Estimator 45/100, Train metric: 2189.3438
Estimator 46/100, Train metric: 2170.0911
Estimator 47/100, Train metric: 2147.1069
Estimator 48/100, Train metric: 2132.0073
Estimator 49/100, Train metric: 2119.7322
Estimator 50/100, Train metric: 2107.7981
Estimator 51/100, Train metric: 2098.7275
Estimator 52/100, Train metric: 2094.4880
Estimator 53/100, Train metric: 2083.5190
Estimator 54/100, Train metric: 2070.9658
Estimator 55/100, Train metric: 2068.4963
Estimator 56/100, Train metric: 2063.4858
Estimator 57/100, Train metric: 2060.6421
Estimator 58/100, Train metric: 2050.5432
Estimator 59/100, Train metric: 2037.6720
Estimator 60/100, Train metric: 2031.0703
Estimator 61/100, Train metric: 2023.0581
Estimator 62/100, Train metric: 2010.4543
Estimator 63/100, Train metric: 2002.0449
Estimator 64/100, Train metric: 1987.7286
Estimator 65/100, Train metric: 1984.9203
Estimator 66/100, Train metric: 1973.4169
Estimator 67/100, Train metric: 1966.4258
Estimator 68/100, Train metric: 1960.8809
Estimator 69/100, Train metric: 1948.2924
Estimator 70/100, Train metric: 1944.8285
Estimator 71/100, Train metric: 1942.9121
Estimator 72/100, Train metric: 1939.2360
Estimator 73/100, Train metric: 1932.8347
Estimator 74/100, Train metric: 1927.9078
Estimator 75/100, Train metric: 1924.9440
Estimator 76/100, Train metric: 1913.4187
Estimator 77/100, Train metric: 1912.3434
Estimator 78/100, Train metric: 1905.1425
Estimator 79/100, Train metric: 1896.0498
Estimator 80/100, Train metric: 1892.6326
Estimator 81/100, Train metric: 1891.8459
Estimator 82/100, Train metric: 1888.5107
Estimator 83/100, Train metric: 1882.2283
Estimator 84/100, Train metric: 1876.3528
Estimator 85/100, Train metric: 1875.3792
Estimator 86/100, Train metric: 1870.1654
Estimator 87/100, Train metric: 1863.5359
Estimator 88/100, Train metric: 1864.7363
Estimator 89/100, Train metric: 1862.3054
Estimator 90/100, Train metric: 1860.8718
Estimator 91/100, Train metric: 1853.1632
Estimator 92/100, Train metric: 1845.0914
Estimator 93/100, Train metric: 1843.2394
Estimator 94/100, Train metric: 1841.3119
Estimator 95/100, Train metric: 1835.9607
Estimator 96/100, Train metric: 1832.8440
Estimator 97/100, Train metric: 1832.7157
Estimator 98/100, Train metric: 1831.7357
Estimator 99/100, Train metric: 1827.0924

===== EXTREME CP (PGBM) =====
Coverage     : 100.000%
Width        : 221527.738
RMSE         : 355.227
q_extreme    : 221527.738
threshold_u  : 2540.163
#Exceedances : 78

In [65]:
def conformal_predictions_AlphaNet_PGBM(
    model_class,
    model_params,
    X_train,
    y_train,
    X_test,
    y_test,
    model_name="PGBM",
    excel_file_path=None,
    alpha=0.05,
    lambda_reg=20.0,
    num_epochs=50,
    batch_size=32,
    lr_alpha=1e-3,
    calib_fraction=0.5,
    num_runs=4,
    random_state=123,
):
    warnings.filterwarnings("ignore")
    np.random.seed(random_state)
    torch.manual_seed(random_state)
    device = "cuda" if torch.cuda.is_available() else "cpu"

    t_start_total = time.time()

    # =========================================================
    # Data conversion (PGBM-specific)
    # =========================================================
    Xtr = X_train.to_numpy() if hasattr(X_train, "to_numpy") else np.asarray(X_train)
    Xte = X_test.to_numpy()  if hasattr(X_test,  "to_numpy") else np.asarray(X_test)
    ytr = to_numpy_1d(y_train)
    yte = to_numpy_1d(y_test)

    # =========================================================
    # 1. Split training data → fit + calibration
    # =========================================================
    n_total = len(Xtr)
    n_fit   = int(n_total * (1 - calib_fraction))
    perm    = np.random.permutation(n_total)

    fit_idx   = perm[:n_fit]
    calib_idx = perm[n_fit:]

    X_fit,   y_fit   = Xtr[fit_idx],   ytr[fit_idx]
    X_calib, y_calib = Xtr[calib_idx],  ytr[calib_idx]
    n_calib = len(X_calib)

    alpha_min = 1.0 / (n_calib + 1) + 0.01
    print(f"  [Info] n_calib={n_calib} | alpha_min={alpha_min:.4f}")

    # =========================================================
    # 2. Train base PGBM model
    # =========================================================
    print(f"  [Step 2/9] Training base {model_name} model...")
    t0 = time.time()
    base_model = model_class(**model_params)
    base_model.fit(X_fit, y_fit)
    print(f"  [Step 2/9] Done in {_fmt_time(time.time()-t0)}")

    def _safe_predict(m, X):
        p = m.predict(X)
        return p.ravel() if hasattr(p, "ravel") else np.asarray(p).ravel()

    # =========================================================
    # 3. PRECOMPUTE all LOO scores
    # =========================================================
    print(f"  [Step 3/9] Precomputing {n_calib} LOO score vectors...")
    t0 = time.time()

    precomputed_scores = []
    precomputed_sums   = []

    iterator = tqdm(range(n_calib), desc="    LOO precompute", leave=False) if HAS_TQDM else range(n_calib)

    for i in iterator:
        loo_X = np.delete(X_calib, i, axis=0)
        loo_y = np.delete(y_calib, i, axis=0)
        scores_loo = np.abs(_safe_predict(base_model, loo_X) - loo_y)

        scores_tensor = torch.tensor(scores_loo, dtype=torch.float32).to(device)
        precomputed_scores.append(scores_tensor)
        precomputed_sums.append(scores_loo.sum())

    elapsed_precompute = time.time() - t0
    print(f"  [Step 3/9] Done in {_fmt_time(elapsed_precompute)}")

    X_alpha = torch.tensor(
        np.array(precomputed_sums).reshape(-1, 1),
        dtype=torch.float32,
    ).to(device)

    # =========================================================
    # 4. Train AlphaNet
    # =========================================================
    print(f"  [Step 4/9] Training AlphaNet: {num_runs} runs × {num_epochs} epochs")

    best_net  = None
    best_loss = np.inf
    history   = {"losses": [], "sizes": [], "alphas": []}

    t0_train = time.time()

    for run in range(num_runs):
        np.random.seed(run)
        torch.manual_seed(run)

        alpha_net = AlphaNet(input_dim=1, alpha_min=alpha_min).to(device)
        optimizer = optim.Adam(alpha_net.parameters(), lr=lr_alpha)

        dataset = TensorDataset(X_alpha, torch.arange(n_calib))
        loader  = DataLoader(dataset, batch_size=batch_size, shuffle=True)

        run_losses, run_sizes, run_alphas = [], [], []

        epoch_iter = (
            tqdm(range(num_epochs), desc=f"    Run {run+1}/{num_runs}", leave=False)
            if HAS_TQDM else range(num_epochs)
        )

        for epoch in epoch_iter:
            t_epoch_start = time.time()
            epoch_loss = epoch_size = epoch_alpha = 0.0

            for x_batch, idx_batch in loader:
                x_batch = x_batch.to(device)
                alpha_pred = alpha_net(x_batch)

                batch_sizes = []
                for j, idx in enumerate(idx_batch):
                    scores_t = precomputed_scores[idx.item()]
                    size_j = _interval_size(scores_t, alpha_pred[j])
                    batch_sizes.append(size_j)

                batch_sizes = torch.stack(batch_sizes)
                loss = (batch_sizes + lambda_reg * alpha_pred).mean()

                optimizer.zero_grad()
                loss.backward()
                optimizer.step()

                epoch_loss  += loss.item()
                epoch_size  += batch_sizes.mean().item()
                epoch_alpha += alpha_pred.mean().item()

            n_batches = len(loader)
            run_losses.append(epoch_loss  / n_batches)
            run_sizes.append(epoch_size   / n_batches)
            run_alphas.append(epoch_alpha / n_batches)

            epoch_time = time.time() - t_epoch_start

            if epoch % 10 == 0 or epoch == num_epochs - 1:
                epochs_done  = (run * num_epochs) + epoch + 1
                epochs_total = num_runs * num_epochs
                elapsed_train = time.time() - t0_train
                eta = (elapsed_train / epochs_done) * (epochs_total - epochs_done)

                print(
                    f"  λ={lambda_reg} | Run {run+1}/{num_runs} | "
                    f"Epoch {epoch}/{num_epochs} | "
                    f"Loss: {run_losses[-1]:.4f} | "
                    f"Size: {run_sizes[-1]:.4f} | "
                    f"α̃: {run_alphas[-1]:.4f} | "
                    f"⏱ {epoch_time:.2f}s/epoch | "
                    f"ETA: {_fmt_time(eta)}"
                )

        if run_losses[-1] < best_loss:
            best_loss = run_losses[-1]
            best_net  = alpha_net

        history["losses"].append(run_losses)
        history["sizes"].append(run_sizes)
        history["alphas"].append(run_alphas)

        print(f"  ✓ Run {run+1} complete | Final loss: {run_losses[-1]:.4f}")

    train_time = time.time() - t0_train
    print(f"  [Step 4/9] Training done in {_fmt_time(train_time)}")

    alpha_net = best_net
    alpha_net.eval()

    # =========================================================
    # 5. Compute conformal intervals on TEST set
    # =========================================================
    print(f"  [Step 5/9] Computing conformal intervals...")
    scores_calib = np.abs(_safe_predict(base_model, X_calib) - y_calib)
    sum_scores   = scores_calib.sum()

    with torch.no_grad():
        feat_test = torch.tensor([sum_scores], dtype=torch.float32).to(device)
        alpha_val = alpha_net(feat_test).item()

    denom = alpha_val * (n_calib + 1) - 1
    if denom <= 0:
        q = np.quantile(scores_calib, 1 - alpha)
        half_width = q
        print(f"  [Warning] α̃ too small; fallback q={q:.4f}")
    else:
        half_width = sum_scores / denom

    y_pred_test = _safe_predict(base_model, Xte)
    ymin = y_pred_test - half_width
    ymax = y_pred_test + half_width

    # =========================================================
    # 6. Metrics
    # =========================================================
    is_covered = ((yte >= ymin) & (yte <= ymax)).astype(int)
    coverage   = is_covered.mean()
    avg_width  = np.mean(ymax - ymin)
    rmse       = np.sqrt(mean_squared_error(yte, y_pred_test))

    total_time = time.time() - t_start_total

    print(f"\n{'='*55}")
    print(f"  ALPHANET CONFORMAL ({model_name})")
    print(f"{'='*55}")
    print(f"  Learned α̃     : {alpha_val:.4f}")
    print(f"  Half-width (r) : {half_width:.4f}")
    print(f"  Coverage       : {coverage*100:.3f}%")
    print(f"  Avg Width      : {avg_width:.4f}")
    print(f"  RMSE           : {rmse:.4f}")
    print(f"  Total time     : {_fmt_time(total_time)}")
    print(f"    ├─ Precompute: {_fmt_time(elapsed_precompute)}")
    print(f"    └─ Training  : {_fmt_time(train_time)}")
    print(f"{'='*55}")

    # =========================================================
    # 7. Summary & Values
    # =========================================================
    summary_df = pd.DataFrame([{
        "Strategy":       "AlphaNet Conformal",
        "Coverage":       coverage,
        "Width":          avg_width,
        "RMSE":           rmse,
        "Alpha_nominal":  alpha,
        "Alpha_learned":  alpha_val,
        "Lambda_reg":     lambda_reg,
        "Total_time_sec": round(total_time, 2),
    }])

    values_df = pd.DataFrame({
        "sample_index": np.arange(len(yte)),
        "y_true":       yte,
        "y_pred":       y_pred_test,
        "ymin":         ymin,
        "ymax":         ymax,
        "width":        ymax - ymin,
        "is_covered":   is_covered,
    })

    # =========================================================
    # 8. Plotting (SAVE ONLY)
    # =========================================================
    print(f"  [Step 8/9] Generating plots...")
    idx_arr = np.arange(len(yte))

    fig_pi, ax_pi = plt.subplots(figsize=(10, 4))
    ax_pi.scatter(idx_arr, yte, color="blue", s=10, alpha=0.7, label="True")
    ax_pi.fill_between(idx_arr, ymin, ymax, color="gray", alpha=0.5,
                       label=f"AlphaNet Interval (α̃={alpha_val:.3f})")
    ax_pi.plot(idx_arr, y_pred_test, color="red", lw=1, label="Predicted mean")
    ax_pi.set_title(f"AlphaNet Conformal ({model_name})")
    ax_pi.set_xlabel("Sample Number")
    ax_pi.set_ylabel("Y_Label")
    ax_pi.legend(loc="upper left")
    plt.tight_layout()

    buf_pi = io.BytesIO()
    fig_pi.savefig(buf_pi, format="png")
    buf_pi.seek(0)
    plt.close(fig_pi)

    arr_losses = np.array(history["losses"])
    arr_sizes  = np.array(history["sizes"])
    arr_alphas = np.array(history["alphas"])
    epochs_arr = np.arange(1, num_epochs + 1)

    fig_tc, axs = plt.subplots(1, 3, figsize=(14, 4))
    for ax, data, ylabel, title in zip(
        axs,
        [arr_losses, arr_sizes, arr_alphas],
        ["Loss", "Mean Interval Size", r"Mean $\tilde{\alpha}$"],
        ["Training Loss", "Interval Size", r"Learned $\tilde{\alpha}$"],
    ):
        m = data.mean(axis=0)
        s = data.std(axis=0)
        ax.plot(epochs_arr, m, color="#0077bb")
        ax.fill_between(epochs_arr, m - s, m + s, color="#0077bb", alpha=0.25)
        ax.set_xlabel("Epoch")
        ax.set_ylabel(ylabel)
        ax.set_title(title)
        ax.grid(True, linewidth=0.5)
    plt.tight_layout()

    buf_tc = io.BytesIO()
    fig_tc.savefig(buf_tc, format="png")
    buf_tc.seek(0)
    plt.close(fig_tc)

    # =========================================================
    # 9. Excel Export
    # =========================================================
    if excel_file_path:
        print(f"  [Step 9/9] Saving to Excel...")
        try:
            wb = load_workbook(excel_file_path)
        except FileNotFoundError:
            from openpyxl import Workbook
            wb = Workbook()
            wb.remove(wb.active)

        def _unique_sheet(wb, name):
            base, i = name, 1
            while name in wb.sheetnames:
                name = f"{base}_{i}"; i += 1
            return name

        sn = _unique_sheet(wb, "AlphaNet_PGBM_Summary")
        ws = wb.create_sheet(sn)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        img_pi = Image(buf_pi)
        sn = _unique_sheet(wb, "AlphaNet_PGBM_Plot_PI")
        ws = wb.create_sheet(sn)
        ws.add_image(img_pi, "A1")

        img_tc = Image(buf_tc)
        sn = _unique_sheet(wb, "AlphaNet_PGBM_Plot_Train")
        ws = wb.create_sheet(sn)
        ws.add_image(img_tc, "A1")

        sn = _unique_sheet(wb, "AlphaNet_PGBM_Values")
        ws = wb.create_sheet(sn)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        wb.save(excel_file_path)
        print(f"  [Step 9/9] Saved!")

    print(f"\n  ✅ AlphaNet PGBM complete in {_fmt_time(total_time)}")
    return summary_df

In [66]:
conformal_predictions_AlphaNet_PGBM(
    model_class=PGBMWrapper,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="PGBM",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/PGBM.xlsx",
    alpha=0.05,
)

  [Info] n_calib=548 | alpha_min=0.0118
  [Step 2/9] Training base PGBM model...
Training on CPU
Estimator 0/100, Train metric: 6041.4238
Estimator 1/100, Train metric: 5959.3457
Estimator 2/100, Train metric: 5868.2876
Estimator 3/100, Train metric: 5783.3896
Estimator 4/100, Train metric: 5729.1250
Estimator 5/100, Train metric: 5635.6411
Estimator 6/100, Train metric: 5550.4604
Estimator 7/100, Train metric: 5484.8525
Estimator 8/100, Train metric: 5423.0454
Estimator 9/100, Train metric: 5354.6479
Estimator 10/100, Train metric: 5301.2847
Estimator 11/100, Train metric: 5251.4868
Estimator 12/100, Train metric: 5201.7231
Estimator 13/100, Train metric: 5144.1377
Estimator 14/100, Train metric: 5099.3354
Estimator 15/100, Train metric: 5060.2271
Estimator 16/100, Train metric: 5013.4468
Estimator 17/100, Train metric: 4971.7900
Estimator 18/100, Train metric: 4935.4165
Estimator 19/100, Train metric: 4887.6421
Estimator 20/100, Train metric: 4867.0566
Estimator 21/100, Train metric: 4833.9531
Estimator 22/100, Train metric: 4788.3120
Estimator 23/100, Train metric: 4754.7964
Estimator 24/100, Train metric: 4719.9028
Estimator 25/100, Train metric: 4678.2354
Estimator 26/100, Train metric: 4658.2388
Estimator 27/100, Train metric: 4625.8911
Estimator 28/100, Train metric: 4608.7183
Estimator 29/100, Train metric: 4583.8013
Estimator 30/100, Train metric: 4570.3179
Estimator 31/100, Train metric: 4559.3047
Estimator 32/100, Train metric: 4545.3569
Estimator 33/100, Train metric: 4523.2588
Estimator 34/100, Train metric: 4517.9053
Estimator 35/100, Train metric: 4497.6602
Estimator 36/100, Train metric: 4481.7876
Estimator 37/100, Train metric: 4474.3032
Estimator 38/100, Train metric: 4457.8984
Estimator 39/100, Train metric: 4445.1265
Estimator 40/100, Train metric: 4428.0171
Estimator 41/100, Train metric: 4426.0288
Estimator 42/100, Train metric: 4408.7812
Estimator 43/100, Train metric: 4390.1973
Estimator 44/100, Train metric: 4381.1406
Estimator 45/100, Train metric: 4365.9419
Estimator 46/100, Train metric: 4352.4141
Estimator 47/100, Train metric: 4342.9673
Estimator 48/100, Train metric: 4338.2568
Estimator 49/100, Train metric: 4318.1934
Estimator 50/100, Train metric: 4313.8589
Estimator 51/100, Train metric: 4303.3828
Estimator 52/100, Train metric: 4300.0947
Estimator 53/100, Train metric: 4290.8608
Estimator 54/100, Train metric: 4282.4868
Estimator 55/100, Train metric: 4274.2173
Estimator 56/100, Train metric: 4270.2007
Estimator 57/100, Train metric: 4267.0537
Estimator 58/100, Train metric: 4258.9321
Estimator 59/100, Train metric: 4255.1318
Estimator 60/100, Train metric: 4252.6323
Estimator 61/100, Train metric: 4247.1050
Estimator 62/100, Train metric: 4246.0659
Estimator 63/100, Train metric: 4242.2397
Estimator 64/100, Train metric: 4234.3125
Estimator 65/100, Train metric: 4230.1748
Estimator 66/100, Train metric: 4224.0337
Estimator 67/100, Train metric: 4219.0112
Estimator 68/100, Train metric: 4217.6392
Estimator 69/100, Train metric: 4215.5859
Estimator 70/100, Train metric: 4209.8965
Estimator 71/100, Train metric: 4204.4614
Estimator 72/100, Train metric: 4198.5420
Estimator 73/100, Train metric: 4195.0679
Estimator 74/100, Train metric: 4188.6372
Estimator 75/100, Train metric: 4184.0469
Estimator 76/100, Train metric: 4178.7310
Estimator 77/100, Train metric: 4171.4038
Estimator 78/100, Train metric: 4166.2661
Estimator 79/100, Train metric: 4161.1074
Estimator 80/100, Train metric: 4156.7466
Estimator 81/100, Train metric: 4155.1099
Estimator 82/100, Train metric: 4149.9302
Estimator 83/100, Train metric: 4145.6870
Estimator 84/100, Train metric: 4141.9321
Estimator 85/100, Train metric: 4142.0107
Estimator 86/100, Train metric: 4137.6016
Estimator 87/100, Train metric: 4133.9736
Estimator 88/100, Train metric: 4132.2939
Estimator 89/100, Train metric: 4131.7744
Estimator 90/100, Train metric: 4127.1519
Estimator 91/100, Train metric: 4122.5166
Estimator 92/100, Train metric: 4116.4897
Estimator 93/100, Train metric: 4114.3560
Estimator 94/100, Train metric: 4111.5918
Estimator 95/100, Train metric: 4108.8135
Estimator 96/100, Train metric: 4108.6436
Estimator 97/100, Train metric: 4103.6768
Estimator 98/100, Train metric: 4103.1885
Estimator 99/100, Train metric: 4099.6719
  [Step 2/9] Done in 1s
  [Step 3/9] Precomputing 548 LOO score vectors...

    LOO precompute:   0%|          | 0/548 [00:00<?, ?it/s]

  [Step 3/9] Done in 50s
  [Step 4/9] Training AlphaNet: 4 runs × 50 epochs

    Run 1/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 1/4 | Epoch 0/50 | Loss: 74983.3485 | Size: 74983.1141 | α̃: 0.0118 | ⏱ 0.28s/epoch | ETA: 1.0min
  λ=20.0 | Run 1/4 | Epoch 10/50 | Loss: 74982.3494 | Size: 74982.1150 | α̃: 0.0118 | ⏱ 0.18s/epoch | ETA: 46s
  λ=20.0 | Run 1/4 | Epoch 20/50 | Loss: 74858.9010 | Size: 74858.6667 | α̃: 0.0118 | ⏱ 0.18s/epoch | ETA: 38s
  λ=20.0 | Run 1/4 | Epoch 30/50 | Loss: 74985.2769 | Size: 74985.0425 | α̃: 0.0118 | ⏱ 0.18s/epoch | ETA: 34s
  λ=20.0 | Run 1/4 | Epoch 40/50 | Loss: 74985.2070 | Size: 74984.9727 | α̃: 0.0118 | ⏱ 0.18s/epoch | ETA: 31s
  λ=20.0 | Run 1/4 | Epoch 49/50 | Loss: 74950.8806 | Size: 74950.6463 | α̃: 0.0118 | ⏱ 0.19s/epoch | ETA: 29s
  ✓ Run 1 complete | Final loss: 74950.8806

    Run 2/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 2/4 | Epoch 0/50 | Loss: 770.9421 | Size: 750.9421 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 29s
  λ=20.0 | Run 2/4 | Epoch 10/50 | Loss: 770.9570 | Size: 750.9570 | α̃: 1.0000 | ⏱ 0.19s/epoch | ETA: 27s
  λ=20.0 | Run 2/4 | Epoch 20/50 | Loss: 770.9449 | Size: 750.9449 | α̃: 1.0000 | ⏱ 0.24s/epoch | ETA: 26s
  λ=20.0 | Run 2/4 | Epoch 30/50 | Loss: 770.9712 | Size: 750.9712 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 24s
  λ=20.0 | Run 2/4 | Epoch 40/50 | Loss: 770.9582 | Size: 750.9582 | α̃: 1.0000 | ⏱ 0.19s/epoch | ETA: 22s
  λ=20.0 | Run 2/4 | Epoch 49/50 | Loss: 770.9689 | Size: 750.9689 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 20s
  ✓ Run 2 complete | Final loss: 770.9689

    Run 3/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 3/4 | Epoch 0/50 | Loss: 770.9213 | Size: 750.9213 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 20s
  λ=20.0 | Run 3/4 | Epoch 10/50 | Loss: 770.9672 | Size: 750.9672 | α̃: 1.0000 | ⏱ 0.19s/epoch | ETA: 18s
  λ=20.0 | Run 3/4 | Epoch 20/50 | Loss: 770.9257 | Size: 750.9257 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 16s
  λ=20.0 | Run 3/4 | Epoch 30/50 | Loss: 770.9713 | Size: 750.9713 | α̃: 1.0000 | ⏱ 0.28s/epoch | ETA: 14s
  λ=20.0 | Run 3/4 | Epoch 40/50 | Loss: 770.7838 | Size: 750.7838 | α̃: 1.0000 | ⏱ 0.26s/epoch | ETA: 12s
  λ=20.0 | Run 3/4 | Epoch 49/50 | Loss: 770.9622 | Size: 750.9622 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 10s
  ✓ Run 3 complete | Final loss: 770.9622

    Run 4/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 4/4 | Epoch 0/50 | Loss: 770.9260 | Size: 750.9260 | α̃: 1.0000 | ⏱ 0.19s/epoch | ETA: 10s
  λ=20.0 | Run 4/4 | Epoch 10/50 | Loss: 770.9043 | Size: 750.9043 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 8s
  λ=20.0 | Run 4/4 | Epoch 20/50 | Loss: 770.9706 | Size: 750.9706 | α̃: 1.0000 | ⏱ 0.19s/epoch | ETA: 6s
  λ=20.0 | Run 4/4 | Epoch 30/50 | Loss: 770.9204 | Size: 750.9204 | α̃: 1.0000 | ⏱ 0.17s/epoch | ETA: 4s
  λ=20.0 | Run 4/4 | Epoch 40/50 | Loss: 770.9692 | Size: 750.9692 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 2s
  λ=20.0 | Run 4/4 | Epoch 49/50 | Loss: 770.9420 | Size: 750.9420 | α̃: 1.0000 | ⏱ 0.25s/epoch | ETA: 0s
  ✓ Run 4 complete | Final loss: 770.9420
  [Step 4/9] Training done in 39s
  [Step 5/9] Computing conformal intervals...

=======================================================
  ALPHANET CONFORMAL (PGBM)
=======================================================
  Learned α̃     : 1.0000
  Half-width (r) : 375.4535
  Coverage       : 90.685%
  Avg Width      : 750.9071
  RMSE           : 419.9263
  Total time     : 1.5min
    ├─ Precompute: 50s
    └─ Training  : 39s
=======================================================
  [Step 8/9] Generating plots...
  [Step 9/9] Saving to Excel...
  [Step 9/9] Saved!

  ✅ AlphaNet PGBM complete in 1.5min

,Strategy,Coverage,Width,RMSE,Alpha_nominal,Alpha_learned,Lambda_reg,Total_time_sec
0,AlphaNet Conformal,0.906849,750.907104,419.926269,0.05,1.0,20.0,90.26

# **Conformal Predictions with TabNet**

In [67]:
best_params = get_best_model_params(best_scores_autosampler, 'TabNet')
print(best_params)

{'n_d': 64, 'n_a': 64, 'n_steps': 10, 'gamma': 1.0, 'lambda_sparse': 0.001, 'optimizer_params': {'lr': 0.02}, 'mask_type': 'sparsemax', 'n_shared': 2, 'n_independent': 3, 'scheduler_params': {'step_size': 10, 'gamma': 0.9}, 'scheduler_fn': <class 'torch.optim.lr_scheduler.StepLR'>, 'seed': 42, 'verbose': 0}

In [68]:
class validate:
    @staticmethod
    def coverage(int_pred, y_test):
        y_arr = np.array(y_test)
        return {strat_name: np.mean((y_arr >= int_pred[strat_name][:, 0]) & (y_arr <= int_pred[strat_name][:, 1])) for strat_name in int_pred}
    @staticmethod
    def width(int_pred):
        return {strat_name: np.mean(int_pred[strat_name][:, 1] - int_pred[strat_name][:, 0]) for strat_name in int_pred}
    @staticmethod
    def rmse(y_pred, y_test):
        y_arr = np.array(y_test)
        return {strat_name: np.sqrt(mean_squared_error(y_arr, y_pred[strat_name])) for strat_name in y_pred}
    @staticmethod
    def cwc(int_pred, y_test, miscoverage):
        widths = validate.width(int_pred)
        coverages = validate.coverage(int_pred, y_test)
        return {strat_name: widths[strat_name] * (1 + (coverages[strat_name] < (1 - miscoverage)) * (1 - coverages[strat_name])) for strat_name in int_pred}
    @staticmethod
    def cond_coverage(int_pred, y_test, num_bins=10):
        y_arr = np.array(y_test)
        cond_coverages = {}
        for strat_name in int_pred:
            widths = int_pred[strat_name][:, 1] - int_pred[strat_name][:, 0]
            bin_edges = np.histogram_bin_edges(widths, bins=num_bins)
            digitized_widths = np.digitize(widths, bin_edges)
            strategy_cond_coverage = []
            for bin_num in range(1, num_bins + 1):
                indices_in_bin = np.where(digitized_widths == bin_num)[0]
                if len(indices_in_bin) > 0:
                    bin_coverage = np.mean((y_arr[indices_in_bin] >= int_pred[strat_name][indices_in_bin, 0]) &
                                           (y_arr[indices_in_bin] <= int_pred[strat_name][indices_in_bin, 1]))
                    strategy_cond_coverage.append(bin_coverage)
                else:
                    strategy_cond_coverage.append(np.nan)
            cond_coverages[strat_name] = strategy_cond_coverage
        return cond_coverages
class visualize:
    @staticmethod
    def goodness(y_true, y_pred, y_pred_low, y_pred_up, coverage, width, rmse, cwc, ax=None, title="Goodness Plot"):
        if ax is None:
            fig, ax = plt.subplots()
        y_true_np = np.array(y_true).ravel()
        inside_interval = (y_true_np >= y_pred_low) & (y_true_np <= y_pred_up)
        outside_interval = ~inside_interval
        ax.scatter(y_true_np[inside_interval], y_pred[inside_interval], color='green', s=10, label='Inside Interval')
        ax.scatter(y_true_np[outside_interval], y_pred[outside_interval], color='orange', s=10, label='Outside Interval')
        ax.scatter(y_true_np, y_true_np, color='blue', marker='x', s=30, linewidths=0.7, label='Ground Truth Values')
        ax.vlines(y_true_np, y_pred_low, y_pred_up, color='gray', alpha=0.5, label='Prediction Intervals')
        ax.plot([min(y_true_np), max(y_true_np)], [min(y_true_np), max(y_true_np)],
                 linestyle='--', color='blue', label='Ideal Prediction Line')
        ax.set_xlabel('Ground Truth')
        ax.set_ylabel('Predictions')
        ax.set_title(f'{title}\nCoverage: {coverage*100:.2f}%, Width: {width:.2f}, RMSE: {rmse:.2f}, CWC: {cwc:.2f}')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax

    @staticmethod
    def width_size_occurrence(int_pred, train_intervals, num_bins=10, ax=None, x_lim=None, title="Width Size Occurrence"):
        if ax is None:
            fig, ax = plt.subplots()
        widths_test = np.abs(int_pred[:, 1] - int_pred[:, 0])
        widths_train = np.abs(train_intervals[:, 1] - train_intervals[:, 0])
        ax.hist(widths_test, bins=num_bins, alpha=0.6, label='Test Interval Widths', color='red')
        ax.hist(widths_train, bins=num_bins, alpha=0.4, label='Train Interval Widths', color='blue')
        if x_lim is not None:
            ax.set_xlim(x_lim)
        ax.set_xlabel('Interval Width')
        ax.set_ylabel('Occurrence (Frequency)')
        ax.set_title(f'{title} - Interval Width Occurrence')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax

    @staticmethod
    def coverage_by_width(y_test, int_pred, miscoverage, cond_coverages, num_bins=10, ax=None, title="Coverage vs Width"):
        if ax is None:
            fig, ax = plt.subplots()
        widths = int_pred[:, 1] - int_pred[:, 0]
        bin_edges = np.histogram_bin_edges(widths, bins=num_bins)
        bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2
        bin_width = bin_edges[1] - bin_edges[0]
        ax.bar(bin_centers, cond_coverages, width=bin_width, color='blue', alpha=0.7, edgecolor='black', linewidth=0.8, label='Conditional Coverage')
        ax.axhline(1 - miscoverage, color='red', linestyle='--', label=f'Nominal Coverage ({(1 - miscoverage)*100:.0f}%)')
        ax.set_xlabel('Interval Width')
        ax.set_ylabel('Conditional Coverage')
        ax.set_title(f'{title} - Coverage vs Interval Width')
        ax.legend(loc='upper left', fontsize='small', bbox_to_anchor=(1.05, 1), borderaxespad=0.)
        return ax

class TabNetRegressorCP(TabNetRegressor):
    def fit(self, X, y, *args, **kwargs):
        y = np.asarray(y)
        if y.ndim == 1:
            y = y.reshape(-1, 1)
        return super().fit(X, y, *args, **kwargs)

    def predict(self, X, *args, **kwargs):
        return super().predict(X).flatten()

In [69]:
def conformal_predictions_NEXCP_tabnet(
    X_train,
    y_train,
    X_test,
    y_test,
    best_params,
    model_name="TabNet",
    excel_file_path=None,
    alpha=0.1,
    decay=0.99,
    n_folds=5,
    n_bootstrap=50,
):
    warnings.filterwarnings("ignore")

    SEED = 123
    rng = np.random.default_rng(SEED)
    np.random.seed(SEED)

    if "verbose" in best_params:
        best_params = dict(best_params)
        best_params.pop("verbose", None)

    model_class = TabNetRegressorCP

    strategies = {
        "NEXCP-Split": "NexCP Split",
        "NEXCP-Full": "NexCP Full",
        "NEXCP-J+aB": "NexCP Jackknife+ aB",
        "NEXCP-CV+": "NexCP CV+",
    }

    y_pred, int_pred = {}, {}

    y_train_np = np.asarray(y_train).ravel()
    y_test_np = np.asarray(y_test).ravel()

    # =========================
    # NexCP – Split (Weighted)
    # =========================
    model = model_class(**best_params)
    model.fit(X_train, y_train_np)

    yhat_train = model.predict(X_train)
    yhat_test = model.predict(X_test)

    residuals = np.abs(y_train_np - yhat_train)
    weights = decay ** np.arange(len(residuals) - 1, -1, -1)
    q = weighted_quantile(residuals, weights, 1 - alpha)

    y_pred["NEXCP-Split"] = yhat_test
    int_pred["NEXCP-Split"] = np.c_[yhat_test - q, yhat_test + q]

    # =========================
    # NexCP – Full
    # =========================
    model = model_class(**best_params)
    model.fit(X_train, y_train_np)

    yhat_train = model.predict(X_train)
    yhat_test = model.predict(X_test)

    q = np.quantile(np.abs(y_train_np - yhat_train), 1 - alpha)

    y_pred["NEXCP-Full"] = yhat_test
    int_pred["NEXCP-Full"] = np.c_[yhat_test - q, yhat_test + q]

    # =========================
    # NexCP – Jackknife+ aB
    # =========================
    lowers, uppers, preds = [], [], []

    for _ in range(n_bootstrap):
        idx = rng.choice(len(X_train), len(X_train), replace=True)

        model = model_class(**best_params)
        model.fit(X_train[idx], y_train_np[idx])

        yhat_boot_train = model.predict(X_train[idx])
        yhat_test = model.predict(X_test)

        q = np.quantile(
            np.abs(y_train_np[idx] - yhat_boot_train),
            1 - alpha,
        )

        lowers.append(yhat_test - q)
        uppers.append(yhat_test + q)
        preds.append(yhat_test)

    y_pred["NEXCP-J+aB"] = np.mean(preds, axis=0)
    int_pred["NEXCP-J+aB"] = np.c_[np.min(lowers, axis=0), np.max(uppers, axis=0)]

    # =========================
    # NexCP – CV+
    # =========================
    kf = KFold(n_splits=n_folds, shuffle=True, random_state=SEED)

    lowers, uppers, preds = [], [], []

    for tr, cal in kf.split(X_train):
        model = model_class(**best_params)
        model.fit(X_train[tr], y_train_np[tr])

        y_cal = model.predict(X_train[cal])
        q = np.quantile(np.abs(y_train_np[cal] - y_cal), 1 - alpha)

        yhat_test = model.predict(X_test)

        lowers.append(yhat_test - q)
        uppers.append(yhat_test + q)
        preds.append(yhat_test)

    y_pred["NEXCP-CV+"] = np.mean(preds, axis=0)
    int_pred["NEXCP-CV+"] = np.c_[np.mean(lowers, axis=0), np.mean(uppers, axis=0)]

    # =========================
    # Metrics
    # =========================
    def coverage(y, l, u):
        return np.mean((y >= l) & (y <= u))

    def width(l, u):
        return np.mean(u - l)

    def cwc(l, u, y, alpha):
        cov = coverage(y, l, u)
        w = width(l, u)
        penalty = np.exp(-50 * (cov - (1 - alpha)))
        return w * (1 + penalty if cov < (1 - alpha) else 1)

    summary = []

    print("\n===== NEXCP TABNET RESULTS =====")
    for s in strategies:
        cov = coverage(y_test_np, int_pred[s][:, 0], int_pred[s][:, 1])
        wid = width(int_pred[s][:, 0], int_pred[s][:, 1])
        rmse = np.sqrt(mean_squared_error(y_test_np, y_pred[s]))
        cwc_val = cwc(int_pred[s][:, 0], int_pred[s][:, 1], y_test_np, alpha)

        summary.append([strategies[s], cov, wid, rmse, cwc_val])
        print(f"{strategies[s]} | Coverage: {cov*100:.3f}% | Width: {wid:.3f}")

    summary_df = pd.DataFrame(
        summary,
        columns=["Strategy", "Coverage", "Width", "RMSE", "CWC"],
    )

    # =========================
    # Plot + Excel Export
    # =========================
    if excel_file_path:
        wb = load_workbook(excel_file_path)

        sheet = "NEXCP_TabNet_Summary"
        base = sheet
        i = 1
        while sheet in wb.sheetnames:
            sheet = f"{base}_{i}"
            i += 1

        ws = wb.create_sheet(sheet)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        for s in strategies:
            fig, ax = plt.subplots(figsize=(10, 4))
            idx = np.arange(len(y_test_np))

            ax.scatter(idx, y_test_np, s=10, alpha=0.7, label="True")
            ax.fill_between(idx, int_pred[s][:, 0], int_pred[s][:, 1], alpha=0.4)
            ax.plot(idx, y_pred[s], linewidth=1, label="Pred")

            ax.set_title(f"{strategies[s]} ({model_name})")
            ax.legend()

            buf = io.BytesIO()
            fig.savefig(buf, format="png")
            buf.seek(0)
            plt.close(fig)

            img = Image(buf)
            ps = f"NEXCP_TabNet_{s}"
            base = ps
            i = 1
            while ps in wb.sheetnames:
                ps = f"{base}_{i}"
                i += 1

            ws = wb.create_sheet(ps)
            ws.add_image(img, "A1")

        wb.save(excel_file_path)

    return summary_df


conformal_predictions_NEXCP_tabnet(
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    best_params=best_params,
    model_name="TabNet",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/TabNet.xlsx",
    alpha=0.1,
    decay=0.99,
    n_folds=5,
    n_bootstrap=50
)

Streaming output truncated to the last 5000 lines.
epoch 6  | loss: 24737630.0|  0:00:00s
epoch 7  | loss: 24616912.0|  0:00:00s
epoch 8  | loss: 24234620.0|  0:00:00s
epoch 9  | loss: 23123788.0|  0:00:00s
epoch 10 | loss: 24107864.0|  0:00:00s
epoch 11 | loss: 23997128.0|  0:00:00s
epoch 12 | loss: 23800820.0|  0:00:00s
epoch 13 | loss: 21404426.0|  0:00:00s
epoch 14 | loss: 23198462.0|  0:00:00s
epoch 15 | loss: 23228696.0|  0:00:00s
epoch 16 | loss: 22909776.0|  0:00:01s
epoch 17 | loss: 22746124.0|  0:00:01s
epoch 18 | loss: 22589604.0|  0:00:01s
epoch 19 | loss: 22392136.0|  0:00:01s
epoch 20 | loss: 21128914.0|  0:00:01s
epoch 21 | loss: 22075224.0|  0:00:01s
epoch 22 | loss: 15365097.0|  0:00:01s
epoch 23 | loss: 13373608.0|  0:00:01s
epoch 24 | loss: 21295048.0|  0:00:01s
epoch 25 | loss: 19518768.0|  0:00:01s
epoch 26 | loss: 14507076.0|  0:00:01s
epoch 27 | loss: 20381500.0|  0:00:01s
epoch 28 | loss: 19961134.0|  0:00:01s
epoch 29 | loss: 19592282.0|  0:00:01s
epoch 30 | loss: 19187658.0|  0:00:01s
epoch 31 | loss: 7507808.0|  0:00:01s
epoch 32 | loss: 17806142.0|  0:00:02s
epoch 33 | loss: 17796710.0|  0:00:02s
epoch 34 | loss: 18201500.0|  0:00:02s
epoch 35 | loss: 18051792.0|  0:00:02s
epoch 36 | loss: 17795692.0|  0:00:02s
epoch 37 | loss: 16331126.0|  0:00:02s
epoch 38 | loss: 16688404.0|  0:00:02s
epoch 39 | loss: 16567700.0|  0:00:02s
epoch 40 | loss: 15273136.0|  0:00:02s
epoch 41 | loss: 16000909.0|  0:00:02s
epoch 42 | loss: 15401683.0|  0:00:02s
epoch 43 | loss: 14559803.0|  0:00:02s
epoch 44 | loss: 14034984.0|  0:00:02s
epoch 45 | loss: 14541672.0|  0:00:02s
epoch 46 | loss: 13943258.0|  0:00:02s
epoch 47 | loss: 13717224.0|  0:00:03s
epoch 48 | loss: 11663618.0|  0:00:03s
epoch 49 | loss: 12936446.0|  0:00:03s
epoch 50 | loss: 7854332.0|  0:00:03s
epoch 51 | loss: 11593411.0|  0:00:03s
epoch 52 | loss: 11755376.0|  0:00:03s
epoch 53 | loss: 11411804.0|  0:00:03s
epoch 54 | loss: 10919994.0|  0:00:03s
epoch 55 | loss: 9765914.0|  0:00:03s
epoch 56 | loss: 10145042.0|  0:00:03s
epoch 57 | loss: 9690097.0|  0:00:03s
epoch 58 | loss: 9113286.0|  0:00:03s
epoch 59 | loss: 7540633.0|  0:00:04s
epoch 60 | loss: 8729151.0|  0:00:04s
epoch 61 | loss: 7649789.5|  0:00:04s
epoch 62 | loss: 3967959.25|  0:00:04s
epoch 63 | loss: 7647059.5|  0:00:04s
epoch 64 | loss: 7259015.5|  0:00:04s
epoch 65 | loss: 6260659.0|  0:00:04s
epoch 66 | loss: 4461467.5|  0:00:04s
epoch 67 | loss: 5232180.0|  0:00:04s
epoch 68 | loss: 3363285.5|  0:00:04s
epoch 69 | loss: 5210812.0|  0:00:04s
epoch 70 | loss: 4476014.5|  0:00:04s
epoch 71 | loss: 4676587.5|  0:00:05s
epoch 72 | loss: 4954859.0|  0:00:05s
epoch 73 | loss: 4090107.0|  0:00:05s
epoch 74 | loss: 4349964.0|  0:00:05s
epoch 75 | loss: 2591274.75|  0:00:05s
epoch 76 | loss: 1503065.25|  0:00:05s
epoch 77 | loss: 3663968.5|  0:00:05s
epoch 78 | loss: 3341424.5|  0:00:05s
epoch 79 | loss: 2482714.25|  0:00:05s
epoch 80 | loss: 2720932.0|  0:00:05s
epoch 81 | loss: 3451951.0|  0:00:05s
epoch 82 | loss: 1125372.625|  0:00:06s
epoch 83 | loss: 2584275.0|  0:00:06s
epoch 84 | loss: 2596370.0|  0:00:06s
epoch 85 | loss: 2333300.0|  0:00:06s
epoch 86 | loss: 2152578.25|  0:00:06s
epoch 87 | loss: 389562.5625|  0:00:06s
epoch 88 | loss: 1840726.75|  0:00:06s
epoch 89 | loss: 1431417.0|  0:00:06s
epoch 90 | loss: 1521963.875|  0:00:06s
epoch 91 | loss: 1397814.0|  0:00:06s
epoch 92 | loss: 1206253.375|  0:00:06s
epoch 93 | loss: 765476.375|  0:00:06s
epoch 94 | loss: 1101075.25|  0:00:06s
epoch 95 | loss: 894306.5|  0:00:06s
epoch 96 | loss: 817233.5|  0:00:06s
epoch 97 | loss: 699752.875|  0:00:06s
epoch 98 | loss: 373960.03125|  0:00:07s
epoch 99 | loss: 966130.25|  0:00:07s
epoch 0  | loss: 15268965.0|  0:00:00s
epoch 1  | loss: 15308954.0|  0:00:00s
epoch 2  | loss: 15017720.0|  0:00:00s
epoch 3  | loss: 14959600.0|  0:00:00s
epoch 4  | loss: 14968246.0|  0:00:00s
epoch 5  | loss: 14737692.0|  0:00:00s
epoch 6  | loss: 14660290.0|  0:00:00s
epoch 7  | loss: 13437578.0|  0:00:00s
epoch 8  | loss: 13984324.0|  0:00:00s
epoch 9  | loss: 14203240.0|  0:00:00s
epoch 10 | loss: 14085312.0|  0:00:00s
epoch 11 | loss: 14087440.0|  0:00:00s
epoch 12 | loss: 13546287.0|  0:00:00s
epoch 13 | loss: 13623579.0|  0:00:00s
epoch 14 | loss: 13362660.0|  0:00:00s
epoch 15 | loss: 11990584.0|  0:00:01s
epoch 16 | loss: 13048074.0|  0:00:01s
epoch 17 | loss: 12447056.0|  0:00:01s
epoch 18 | loss: 12512228.0|  0:00:01s
epoch 19 | loss: 11757842.0|  0:00:01s
epoch 20 | loss: 11116162.0|  0:00:01s
epoch 21 | loss: 12041596.0|  0:00:01s
epoch 22 | loss: 12086092.0|  0:00:01s
epoch 23 | loss: 11733740.0|  0:00:01s
epoch 24 | loss: 11736247.0|  0:00:01s
epoch 25 | loss: 11203536.0|  0:00:01s
epoch 26 | loss: 11182168.0|  0:00:01s
epoch 27 | loss: 9736473.0|  0:00:01s
epoch 28 | loss: 10719414.0|  0:00:01s
epoch 29 | loss: 10416181.0|  0:00:01s
epoch 30 | loss: 10200992.0|  0:00:01s
epoch 31 | loss: 9902267.0|  0:00:02s
epoch 32 | loss: 9116408.0|  0:00:02s
epoch 33 | loss: 8800052.0|  0:00:02s
epoch 34 | loss: 9314707.0|  0:00:02s
epoch 35 | loss: 9076023.0|  0:00:02s
epoch 36 | loss: 8894647.0|  0:00:02s
epoch 37 | loss: 8167780.0|  0:00:02s
epoch 38 | loss: 8420019.0|  0:00:02s
epoch 39 | loss: 7944647.0|  0:00:02s
epoch 40 | loss: 5845068.5|  0:00:02s
epoch 41 | loss: 7008603.0|  0:00:02s
epoch 42 | loss: 7399051.5|  0:00:02s
epoch 43 | loss: 5936786.0|  0:00:02s
epoch 44 | loss: 6704644.5|  0:00:02s
epoch 45 | loss: 6664991.5|  0:00:02s
epoch 46 | loss: 6279449.0|  0:00:02s
epoch 47 | loss: 6902246.0|  0:00:03s
epoch 48 | loss: 6595779.0|  0:00:03s
epoch 49 | loss: 6445611.0|  0:00:03s
epoch 50 | loss: 5376062.0|  0:00:03s
epoch 51 | loss: 6317651.5|  0:00:03s
epoch 52 | loss: 5930049.5|  0:00:03s
epoch 53 | loss: 5254322.5|  0:00:03s
epoch 54 | loss: 5495014.5|  0:00:03s
epoch 55 | loss: 5395668.0|  0:00:03s
epoch 56 | loss: 5225457.0|  0:00:03s
epoch 57 | loss: 945253.25|  0:00:03s
epoch 58 | loss: 4802143.5|  0:00:03s
epoch 59 | loss: 3548212.5|  0:00:03s
epoch 60 | loss: 4759499.0|  0:00:03s
epoch 61 | loss: 4542489.5|  0:00:03s
epoch 62 | loss: 4247439.0|  0:00:03s
epoch 63 | loss: 894912.5|  0:00:04s
epoch 64 | loss: 3897977.75|  0:00:04s
epoch 65 | loss: 3318621.5|  0:00:04s
epoch 66 | loss: 3703518.5|  0:00:04s
epoch 67 | loss: 3379808.5|  0:00:04s
epoch 68 | loss: 2920332.0|  0:00:04s
epoch 69 | loss: 3084335.5|  0:00:04s
epoch 70 | loss: 2787391.5|  0:00:04s
epoch 71 | loss: 2841590.5|  0:00:04s
epoch 72 | loss: 2359322.5|  0:00:04s
epoch 73 | loss: 2408558.5|  0:00:04s
epoch 74 | loss: 2471568.0|  0:00:04s
epoch 75 | loss: 2459987.5|  0:00:04s
epoch 76 | loss: 2224379.5|  0:00:04s
epoch 77 | loss: 1941282.625|  0:00:04s
epoch 78 | loss: 1930400.125|  0:00:04s
epoch 79 | loss: 562770.875|  0:00:04s
epoch 80 | loss: 1530121.625|  0:00:05s
epoch 81 | loss: 1252497.875|  0:00:05s
epoch 82 | loss: 1224167.25|  0:00:05s
epoch 83 | loss: 976322.0625|  0:00:05s
epoch 84 | loss: 1159708.625|  0:00:05s
epoch 85 | loss: 1010167.6875|  0:00:05s
epoch 86 | loss: 837876.375|  0:00:05s
epoch 87 | loss: 588858.8125|  0:00:05s
epoch 88 | loss: 723554.4375|  0:00:05s
epoch 89 | loss: 635740.125|  0:00:05s
epoch 90 | loss: 562668.875|  0:00:05s
epoch 91 | loss: 517114.125|  0:00:05s
epoch 92 | loss: 419878.75|  0:00:05s
epoch 93 | loss: 1180580.375|  0:00:05s
epoch 94 | loss: 414960.5625|  0:00:05s
epoch 95 | loss: 404905.03125|  0:00:05s
epoch 96 | loss: 384307.46875|  0:00:06s
epoch 97 | loss: 365543.5|  0:00:06s
epoch 98 | loss: 341748.40625|  0:00:06s
epoch 99 | loss: 1956228.125|  0:00:06s
epoch 0  | loss: 28833252.0|  0:00:00s
epoch 1  | loss: 28484944.0|  0:00:00s
epoch 2  | loss: 28429570.0|  0:00:00s
epoch 3  | loss: 27208280.0|  0:00:00s
epoch 4  | loss: 21407924.0|  0:00:00s
epoch 5  | loss: 28012840.0|  0:00:00s
epoch 6  | loss: 27821596.0|  0:00:00s
epoch 7  | loss: 27587890.0|  0:00:00s
epoch 8  | loss: 27459228.0|  0:00:00s
epoch 9  | loss: 27154524.0|  0:00:00s
epoch 10 | loss: 27117396.0|  0:00:00s
epoch 11 | loss: 26620630.0|  0:00:00s
epoch 12 | loss: 26578508.0|  0:00:00s
epoch 13 | loss: 26285756.0|  0:00:00s
epoch 14 | loss: 26273218.0|  0:00:00s
epoch 15 | loss: 24827814.0|  0:00:01s
epoch 16 | loss: 24656202.0|  0:00:01s
epoch 17 | loss: 24177740.0|  0:00:01s
epoch 18 | loss: 19002928.0|  0:00:01s
epoch 19 | loss: 25167936.0|  0:00:01s
epoch 20 | loss: 24794978.0|  0:00:01s
epoch 21 | loss: 24451930.0|  0:00:01s
epoch 22 | loss: 24022720.0|  0:00:01s
epoch 23 | loss: 22863930.0|  0:00:01s
epoch 24 | loss: 22471062.0|  0:00:01s
epoch 25 | loss: 15494585.0|  0:00:01s
epoch 26 | loss: 22792530.0|  0:00:01s
epoch 27 | loss: 21562456.0|  0:00:01s
epoch 28 | loss: 21583498.0|  0:00:01s
epoch 29 | loss: 22106978.0|  0:00:01s
epoch 30 | loss: 22153872.0|  0:00:01s
epoch 31 | loss: 21238942.0|  0:00:02s
epoch 32 | loss: 21367676.0|  0:00:02s
epoch 33 | loss: 15492798.0|  0:00:02s
epoch 34 | loss: 20451642.0|  0:00:02s
epoch 35 | loss: 20011406.0|  0:00:02s
epoch 36 | loss: 18832736.0|  0:00:02s
epoch 37 | loss: 19208962.0|  0:00:02s
epoch 38 | loss: 18837098.0|  0:00:02s
epoch 39 | loss: 18858700.0|  0:00:02s
epoch 40 | loss: 18887948.0|  0:00:02s
epoch 41 | loss: 17600022.0|  0:00:02s
epoch 42 | loss: 13213232.0|  0:00:02s
epoch 43 | loss: 17644560.0|  0:00:02s
epoch 44 | loss: 17497882.0|  0:00:02s
epoch 45 | loss: 11886951.0|  0:00:03s
epoch 46 | loss: 7046196.0|  0:00:03s
epoch 47 | loss: 11216606.0|  0:00:03s
epoch 48 | loss: 16037244.0|  0:00:03s
epoch 49 | loss: 14831564.0|  0:00:03s
epoch 50 | loss: 15183822.0|  0:00:03s
epoch 51 | loss: 14721100.0|  0:00:03s
epoch 52 | loss: 14419073.0|  0:00:03s
epoch 53 | loss: 13400680.0|  0:00:03s
epoch 54 | loss: 13791006.0|  0:00:03s
epoch 55 | loss: 13162526.0|  0:00:03s
epoch 56 | loss: 12769846.0|  0:00:03s
epoch 57 | loss: 7488862.0|  0:00:04s
epoch 58 | loss: 11437184.0|  0:00:04s
epoch 59 | loss: 10969380.0|  0:00:04s
epoch 60 | loss: 11353953.0|  0:00:04s
epoch 61 | loss: 10778680.0|  0:00:04s
epoch 62 | loss: 10299691.0|  0:00:04s
epoch 63 | loss: 9690898.0|  0:00:04s
epoch 64 | loss: 9697628.0|  0:00:04s
epoch 65 | loss: 9536090.0|  0:00:04s
epoch 66 | loss: 9194166.0|  0:00:04s
epoch 67 | loss: 5508894.5|  0:00:04s
epoch 68 | loss: 4986730.0|  0:00:04s
epoch 69 | loss: 4822032.5|  0:00:05s
epoch 70 | loss: 7495761.0|  0:00:05s
epoch 71 | loss: 7686572.0|  0:00:05s
epoch 72 | loss: 7302197.0|  0:00:05s
epoch 73 | loss: 6359638.5|  0:00:05s
epoch 74 | loss: 6678536.0|  0:00:05s
epoch 75 | loss: 5710321.0|  0:00:05s
epoch 76 | loss: 7107070.0|  0:00:05s
epoch 77 | loss: 5703209.0|  0:00:05s
epoch 78 | loss: 2421250.5|  0:00:05s
epoch 79 | loss: 5212374.0|  0:00:05s
epoch 80 | loss: 5063665.5|  0:00:05s
epoch 81 | loss: 4682217.0|  0:00:06s
epoch 82 | loss: 4297649.0|  0:00:06s
epoch 83 | loss: 4076333.0|  0:00:06s
epoch 84 | loss: 4189943.75|  0:00:06s
epoch 85 | loss: 4000843.0|  0:00:06s
epoch 86 | loss: 3730971.5|  0:00:06s
epoch 87 | loss: 3426261.0|  0:00:06s
epoch 88 | loss: 3237071.0|  0:00:06s
epoch 89 | loss: 1309493.0|  0:00:06s
epoch 90 | loss: 1157485.5|  0:00:06s
epoch 91 | loss: 2713681.25|  0:00:06s
epoch 92 | loss: 2519602.0|  0:00:06s
epoch 93 | loss: 2289667.5|  0:00:06s
epoch 94 | loss: 2112384.75|  0:00:06s
epoch 95 | loss: 2081012.0|  0:00:06s
epoch 96 | loss: 664235.375|  0:00:06s
epoch 97 | loss: 1598426.0|  0:00:07s
epoch 98 | loss: 695152.0|  0:00:07s
epoch 99 | loss: 761879.375|  0:00:07s
epoch 0  | loss: 13709194.0|  0:00:00s
epoch 1  | loss: 13011852.0|  0:00:00s
epoch 2  | loss: 14015448.0|  0:00:00s
epoch 3  | loss: 13781340.0|  0:00:00s
epoch 4  | loss: 13909796.0|  0:00:00s
epoch 5  | loss: 13562622.0|  0:00:00s
epoch 6  | loss: 13503408.0|  0:00:00s
epoch 7  | loss: 12201407.0|  0:00:00s
epoch 8  | loss: 13063706.0|  0:00:00s
epoch 9  | loss: 11045056.0|  0:00:00s
epoch 10 | loss: 11794258.0|  0:00:00s
epoch 11 | loss: 12947625.0|  0:00:00s
epoch 12 | loss: 12737009.0|  0:00:00s
epoch 13 | loss: 12575994.0|  0:00:00s
epoch 14 | loss: 11674442.0|  0:00:00s
epoch 15 | loss: 11267552.0|  0:00:01s
epoch 16 | loss: 11081419.0|  0:00:01s
epoch 17 | loss: 11794923.0|  0:00:01s
epoch 18 | loss: 11663543.0|  0:00:01s
epoch 19 | loss: 11160702.0|  0:00:01s
epoch 20 | loss: 10522784.0|  0:00:01s
epoch 21 | loss: 10230067.0|  0:00:01s
epoch 22 | loss: 10975816.0|  0:00:01s
epoch 23 | loss: 10320780.0|  0:00:01s
epoch 24 | loss: 10612456.0|  0:00:01s
epoch 25 | loss: 10105419.0|  0:00:01s
epoch 26 | loss: 10068351.0|  0:00:01s
epoch 27 | loss: 8408737.0|  0:00:01s
epoch 28 | loss: 9766783.0|  0:00:01s
epoch 29 | loss: 9293642.0|  0:00:01s
epoch 30 | loss: 9313545.0|  0:00:01s
epoch 31 | loss: 8844336.0|  0:00:02s
epoch 32 | loss: 7460923.0|  0:00:02s
epoch 33 | loss: 7961061.0|  0:00:02s
epoch 34 | loss: 7422844.5|  0:00:02s
epoch 35 | loss: 7218098.5|  0:00:02s
epoch 36 | loss: 6976724.0|  0:00:02s
epoch 37 | loss: 7218519.0|  0:00:02s
epoch 38 | loss: 6780515.5|  0:00:02s
epoch 39 | loss: 7001725.0|  0:00:02s
epoch 40 | loss: 6752460.0|  0:00:02s
epoch 41 | loss: 6708696.5|  0:00:02s
epoch 42 | loss: 5541426.0|  0:00:02s
epoch 43 | loss: 6450003.0|  0:00:02s
epoch 44 | loss: 5312670.0|  0:00:02s
epoch 45 | loss: 5193471.5|  0:00:02s
epoch 46 | loss: 5650427.0|  0:00:02s
epoch 47 | loss: 4654420.0|  0:00:03s
epoch 48 | loss: 4671093.0|  0:00:03s
epoch 49 | loss: 4649641.5|  0:00:03s
epoch 50 | loss: 4507102.5|  0:00:03s
epoch 51 | loss: 3461381.25|  0:00:03s
epoch 52 | loss: 4295424.5|  0:00:03s
epoch 53 | loss: 3545971.5|  0:00:03s
epoch 54 | loss: 3005963.0|  0:00:03s
epoch 55 | loss: 3607186.25|  0:00:03s
epoch 56 | loss: 3503464.75|  0:00:03s
epoch 57 | loss: 3133957.25|  0:00:03s
epoch 58 | loss: 2905942.0|  0:00:03s
epoch 59 | loss: 2995197.5|  0:00:03s
epoch 60 | loss: 2599874.25|  0:00:03s
epoch 61 | loss: 2301039.25|  0:00:03s
epoch 62 | loss: 1875145.0|  0:00:03s
epoch 63 | loss: 2222794.0|  0:00:04s
epoch 64 | loss: 1369205.25|  0:00:04s
epoch 65 | loss: 1371821.375|  0:00:04s
epoch 66 | loss: 1326091.625|  0:00:04s
epoch 67 | loss: 1267937.0|  0:00:04s
epoch 68 | loss: 1362845.875|  0:00:04s
epoch 69 | loss: 1414060.125|  0:00:04s
epoch 70 | loss: 1295536.875|  0:00:04s
epoch 71 | loss: 909876.875|  0:00:04s
epoch 72 | loss: 816528.4375|  0:00:04s
epoch 73 | loss: 965242.625|  0:00:04s
epoch 74 | loss: 954011.8125|  0:00:04s
epoch 75 | loss: 617816.8125|  0:00:04s
epoch 76 | loss: 745929.0625|  0:00:04s
epoch 77 | loss: 633016.625|  0:00:04s
epoch 78 | loss: 594376.375|  0:00:04s
epoch 79 | loss: 545071.0625|  0:00:05s
epoch 80 | loss: 486954.03125|  0:00:05s
epoch 81 | loss: 391998.5625|  0:00:05s
epoch 82 | loss: 428675.71875|  0:00:05s
epoch 83 | loss: 344841.46875|  0:00:05s
epoch 84 | loss: 319777.8125|  0:00:05s
epoch 85 | loss: 368577.75|  0:00:05s
epoch 86 | loss: 328583.125|  0:00:05s
epoch 87 | loss: 342174.8125|  0:00:05s
epoch 88 | loss: 327961.125|  0:00:05s
epoch 89 | loss: 304644.875|  0:00:05s
epoch 90 | loss: 318011.84375|  0:00:05s
epoch 91 | loss: 302721.6875|  0:00:05s
epoch 92 | loss: 383229.8125|  0:00:05s
epoch 93 | loss: 290396.8125|  0:00:05s
epoch 94 | loss: 513703.5625|  0:00:05s
epoch 95 | loss: 405359.8125|  0:00:05s
epoch 96 | loss: 414229.5|  0:00:06s
epoch 97 | loss: 426512.0|  0:00:06s
epoch 98 | loss: 338185.0625|  0:00:06s
epoch 99 | loss: 296639.8125|  0:00:06s
epoch 0  | loss: 22847250.0|  0:00:00s
epoch 1  | loss: 15676296.0|  0:00:00s
epoch 2  | loss: 22575518.0|  0:00:00s
epoch 3  | loss: 22517592.0|  0:00:00s
epoch 4  | loss: 21732144.0|  0:00:00s
epoch 5  | loss: 21697772.0|  0:00:00s
epoch 6  | loss: 22346276.0|  0:00:00s
epoch 7  | loss: 21813264.0|  0:00:00s
epoch 8  | loss: 20818960.0|  0:00:00s
epoch 9  | loss: 21376328.0|  0:00:00s
epoch 10 | loss: 19836696.0|  0:00:00s
epoch 11 | loss: 21477376.0|  0:00:00s
epoch 12 | loss: 21206932.0|  0:00:00s
epoch 13 | loss: 21222612.0|  0:00:00s
epoch 14 | loss: 20786748.0|  0:00:00s
epoch 15 | loss: 20976624.0|  0:00:01s
epoch 16 | loss: 19543546.0|  0:00:01s
epoch 17 | loss: 20593332.0|  0:00:01s
epoch 18 | loss: 20164606.0|  0:00:01s
epoch 19 | loss: 18970928.0|  0:00:01s
epoch 20 | loss: 19404344.0|  0:00:01s
epoch 21 | loss: 17526698.0|  0:00:01s
epoch 22 | loss: 18796256.0|  0:00:01s
epoch 23 | loss: 19087788.0|  0:00:01s
epoch 24 | loss: 12650682.0|  0:00:01s
epoch 25 | loss: 18750204.0|  0:00:01s
epoch 26 | loss: 18427436.0|  0:00:01s
epoch 27 | loss: 11715411.0|  0:00:01s
epoch 28 | loss: 17878716.0|  0:00:01s
epoch 29 | loss: 17706706.0|  0:00:01s
epoch 30 | loss: 17189080.0|  0:00:01s
epoch 31 | loss: 17161248.0|  0:00:02s
epoch 32 | loss: 16839336.0|  0:00:02s
epoch 33 | loss: 10764868.0|  0:00:02s
epoch 34 | loss: 10510016.0|  0:00:02s
epoch 35 | loss: 15513022.0|  0:00:02s
epoch 36 | loss: 15747349.0|  0:00:02s
epoch 37 | loss: 15549485.0|  0:00:02s
epoch 38 | loss: 14959753.0|  0:00:02s
epoch 39 | loss: 14671020.0|  0:00:02s
epoch 40 | loss: 12699253.0|  0:00:02s
epoch 41 | loss: 14297044.0|  0:00:02s
epoch 42 | loss: 13520168.0|  0:00:02s
epoch 43 | loss: 12586208.0|  0:00:03s
epoch 44 | loss: 12350012.0|  0:00:03s
epoch 45 | loss: 11755647.0|  0:00:03s
epoch 46 | loss: 13298748.0|  0:00:03s
epoch 47 | loss: 12791814.0|  0:00:03s
epoch 48 | loss: 12333508.0|  0:00:03s
epoch 49 | loss: 7066427.5|  0:00:03s
epoch 50 | loss: 11475772.0|  0:00:03s
epoch 51 | loss: 10959484.0|  0:00:03s
epoch 52 | loss: 10411168.0|  0:00:03s
epoch 53 | loss: 10391992.0|  0:00:03s
epoch 54 | loss: 9292953.0|  0:00:03s
epoch 55 | loss: 9609296.0|  0:00:04s
epoch 56 | loss: 9468161.0|  0:00:04s
epoch 57 | loss: 8901890.0|  0:00:04s
epoch 58 | loss: 8616203.0|  0:00:04s
epoch 59 | loss: 8376906.0|  0:00:04s
epoch 60 | loss: 7465425.5|  0:00:04s
epoch 61 | loss: 7835345.0|  0:00:04s
epoch 62 | loss: 7550828.0|  0:00:04s
epoch 63 | loss: 7142040.0|  0:00:04s
epoch 64 | loss: 6896901.0|  0:00:04s
epoch 65 | loss: 3367234.0|  0:00:04s
epoch 66 | loss: 7389913.0|  0:00:05s
epoch 67 | loss: 6973339.0|  0:00:05s
epoch 68 | loss: 6338644.0|  0:00:05s
epoch 69 | loss: 2867712.5|  0:00:05s
epoch 70 | loss: 4412766.0|  0:00:05s
epoch 71 | loss: 5184327.0|  0:00:05s
epoch 72 | loss: 8648280.0|  0:00:05s
epoch 73 | loss: 5085190.0|  0:00:05s
epoch 74 | loss: 4788615.0|  0:00:05s
epoch 75 | loss: 3904430.25|  0:00:05s
epoch 76 | loss: 4231624.5|  0:00:05s
epoch 77 | loss: 4188153.5|  0:00:05s
epoch 78 | loss: 4108766.0|  0:00:05s
epoch 79 | loss: 3826153.5|  0:00:05s
epoch 80 | loss: 2836025.5|  0:00:05s
epoch 81 | loss: 3268498.5|  0:00:06s
epoch 82 | loss: 3216845.5|  0:00:06s
epoch 83 | loss: 2911427.5|  0:00:06s
epoch 84 | loss: 2729253.0|  0:00:06s
epoch 85 | loss: 2542786.0|  0:00:06s
epoch 86 | loss: 2331972.0|  0:00:06s
epoch 87 | loss: 1924222.5|  0:00:06s
epoch 88 | loss: 1991821.0|  0:00:06s
epoch 89 | loss: 496455.78125|  0:00:06s
epoch 90 | loss: 570875.8125|  0:00:06s
epoch 91 | loss: 1938623.5|  0:00:06s
epoch 92 | loss: 1764679.125|  0:00:06s
epoch 93 | loss: 1478300.25|  0:00:06s
epoch 94 | loss: 1501734.625|  0:00:06s
epoch 95 | loss: 1358722.75|  0:00:06s
epoch 96 | loss: 1222290.75|  0:00:06s
epoch 97 | loss: 1117906.75|  0:00:07s
epoch 98 | loss: 966965.125|  0:00:07s
epoch 99 | loss: 898252.4375|  0:00:07s
epoch 0  | loss: 17227536.0|  0:00:00s
epoch 1  | loss: 15812028.0|  0:00:00s
epoch 2  | loss: 23890868.0|  0:00:00s
epoch 3  | loss: 23725918.0|  0:00:00s
epoch 4  | loss: 23605652.0|  0:00:00s
epoch 5  | loss: 23505272.0|  0:00:00s
epoch 6  | loss: 23364716.0|  0:00:00s
epoch 7  | loss: 21772544.0|  0:00:00s
epoch 8  | loss: 20800690.0|  0:00:00s
epoch 9  | loss: 21336946.0|  0:00:00s
epoch 10 | loss: 22385788.0|  0:00:00s
epoch 11 | loss: 22601824.0|  0:00:00s
epoch 12 | loss: 21634196.0|  0:00:00s
epoch 13 | loss: 15611922.0|  0:00:00s
epoch 14 | loss: 19745304.0|  0:00:00s
epoch 15 | loss: 21617384.0|  0:00:01s
epoch 16 | loss: 20422358.0|  0:00:01s
epoch 17 | loss: 21034298.0|  0:00:01s
epoch 18 | loss: 21010566.0|  0:00:01s
epoch 19 | loss: 21110132.0|  0:00:01s

              Strategy  Coverage        Width        RMSE          CWC
0          NexCP Split  0.890411   308.312286  472.287828   806.294938
1           NexCP Full  0.942466  1002.890930  472.287828  1002.890930
2  NexCP Jackknife+ aB  1.000000  4305.995117  407.896333  4305.995117
3            NexCP CV+  0.958904  1282.207642  343.883890  1282.207642

In [70]:
y_train = pd.Series(y_train)
y_test = pd.Series(y_test)

conformal_predictions_online_super(
    model_class=TabNetRegressorCP,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="TabNet",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/TabNet.xlsx",
    alpha=0.1,
    strategies="all",
    window_min=50,
    window_max=500,
    window_grid=(25, 50, 100, 200, 400),
    n_bootstrap=30
)

===== ONLINE CP RESULTS =====
               Strategy  Coverage        Width        RMSE          CWC
0          Online Split  0.942466  1002.891052  472.287872  1002.891052
1            Online CV+  0.939726   885.115655  472.287872   885.115655
2  Online Jackknife+ aB  1.000000  4111.352539  460.806717  4111.352539
3                 SAOCP  0.898630   358.873839  472.287872   395.252831
4                SF-OGD  0.942466  1044.343526  472.287872  1044.343526
5                  FACI  0.808219   728.373302  472.287872   868.061332
6            MFCS Split  0.942466  1002.891052  472.287872  1002.891052
7             MFCS Full  0.928767  1197.445094  566.319969  1197.445094

               Strategy  Coverage        Width        RMSE          CWC
0          Online Split  0.942466  1002.891052  472.287872  1002.891052
1            Online CV+  0.939726   885.115655  472.287872   885.115655
2  Online Jackknife+ aB  1.000000  4111.352539  460.806717  4111.352539
3                 SAOCP  0.898630   358.873839  472.287872   395.252831
4                SF-OGD  0.942466  1044.343526  472.287872  1044.343526
5                  FACI  0.808219   728.373302  472.287872   868.061332
6            MFCS Split  0.942466  1002.891052  472.287872  1002.891052
7             MFCS Full  0.928767  1197.445094  566.319969  1197.445094

In [71]:
conformal_predictions_COP(
    model_class=TabNetRegressorCP,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="TabNet",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/TabNet.xlsx",
    alpha=0.1,
    lr=0.05,
    T_burnin=50,
    scale=0.5
)

===== CONFORMAL OPTIMISTIC PREDICTION (TabNet) =====
Coverage : 94.247%
Avg Width: 1001.922
RMSE     : 472.288
Final q  : 500.673

  Strategy  Coverage        Width        RMSE  Alpha    LR  Scale
0      COP  0.942466  1001.921997  472.287828    0.1  0.05    0.5

In [72]:
conformal_predictions_EXTREME(
    model_class=TabNetRegressorCP,
    model_params=best_params,
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    model_name="TabNet",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/TabNet.xlsx",
    alpha=0.05,
    calib_size=0.4,
    gpd_threshold_quantile=0.95,
    n_bootstrap=30
)

===== EXTREME CONFORMAL PREDICTION (TabNet) =====
Coverage : 100.000%
Width    : 93287.745
RMSE     : 284.730
q_extreme: 93287.745
u        : 2171.028
#Exceed. : 208

In [73]:
def conformal_predictions_AlphaNet_tabnet(
    X_train,
    y_train,
    X_test,
    y_test,
    best_params,
    model_name="TabNet",
    excel_file_path=None,
    alpha=0.05,
    lambda_reg=20.0,
    num_epochs=50,
    batch_size=32,
    lr_alpha=1e-3,
    calib_fraction=0.5,
    num_runs=4,
    random_state=123,
):
    """
    Learned-α Conformal Prediction via AlphaNet — TabNet-specific variant.

    Handles:
    - TabNetRegressorCP wrapper (y reshape, predict flatten)
    - Removes 'verbose' from best_params if present
    - Precomputed LOO scores for speed
    - Progress tracking with tqdm + ETA
    """

    warnings.filterwarnings("ignore")
    np.random.seed(random_state)
    torch.manual_seed(random_state)
    device = "cuda" if torch.cuda.is_available() else "cpu"

    t_start_total = time.time()

    # =========================================================
    # TabNet-specific: clean params & set model class
    # =========================================================
    tabnet_params = dict(best_params)
    tabnet_params.pop("verbose", None)           # TabNet doesn't use verbose here
    model_class = TabNetRegressorCP

    # =========================================================
    # Data conversion
    # =========================================================
    Xtr = X_train.to_numpy() if hasattr(X_train, "to_numpy") else np.asarray(X_train)
    Xte = X_test.to_numpy()  if hasattr(X_test,  "to_numpy") else np.asarray(X_test)
    ytr = to_numpy_1d(y_train)
    yte = to_numpy_1d(y_test)

    # =========================================================
    # 1. Split training data → fit + calibration
    # =========================================================
    n_total = len(Xtr)
    n_fit   = int(n_total * (1 - calib_fraction))
    perm    = np.random.permutation(n_total)

    fit_idx   = perm[:n_fit]
    calib_idx = perm[n_fit:]

    X_fit,   y_fit   = Xtr[fit_idx],   ytr[fit_idx]
    X_calib, y_calib = Xtr[calib_idx],  ytr[calib_idx]
    n_calib = len(X_calib)

    # alpha_min: must satisfy α̃·(n+1) − 1 > 0  →  α̃ > 1/(n+1)
    alpha_min = 1.0 / (n_calib + 1) + 0.01
    print(f"  [Info] n_calib={n_calib} | alpha_min={alpha_min:.4f}")

    # =========================================================
    # 2. Train base TabNet model
    # =========================================================
    print(f"  [Step 2/9] Training base {model_name} model...")
    t0 = time.time()
    base_model = model_class(**tabnet_params)
    base_model.fit(X_fit, y_fit)
    print(f"  [Step 2/9] Done in {_fmt_time(time.time()-t0)}")

    # =========================================================
    # 3. PRECOMPUTE all LOO scores (KEY SPEEDUP)
    # =========================================================
    print(f"  [Step 3/9] Precomputing {n_calib} LOO score vectors...")
    t0 = time.time()

    precomputed_scores = []
    precomputed_sums   = []

    iterator = (
        tqdm(range(n_calib), desc="    LOO precompute", leave=False)
        if HAS_TQDM else range(n_calib)
    )

    for i in iterator:
        loo_X = np.delete(X_calib, i, axis=0)
        loo_y = np.delete(y_calib, i, axis=0)
        preds_loo = base_model.predict(loo_X).ravel()
        scores_loo = np.abs(preds_loo - loo_y)

        scores_tensor = torch.tensor(scores_loo, dtype=torch.float32).to(device)
        precomputed_scores.append(scores_tensor)
        precomputed_sums.append(scores_loo.sum())

    elapsed_precompute = time.time() - t0
    print(f"  [Step 3/9] Done in {_fmt_time(elapsed_precompute)}")

    # Build feature matrix (sum of LOO scores per sample)
    X_alpha = torch.tensor(
        np.array(precomputed_sums).reshape(-1, 1),
        dtype=torch.float32,
    ).to(device)

    # =========================================================
    # 4. Train AlphaNet (multiple runs, keep best)
    # =========================================================
    print(f"  [Step 4/9] Training AlphaNet: {num_runs} runs × {num_epochs} epochs")

    best_net  = None
    best_loss = np.inf
    history   = {"losses": [], "sizes": [], "alphas": []}

    t0_train = time.time()

    for run in range(num_runs):
        np.random.seed(run)
        torch.manual_seed(run)

        alpha_net = AlphaNet(input_dim=1, alpha_min=alpha_min).to(device)
        optimizer = optim.Adam(alpha_net.parameters(), lr=lr_alpha)

        dataset = TensorDataset(X_alpha, torch.arange(n_calib))
        loader  = DataLoader(dataset, batch_size=batch_size, shuffle=True)

        run_losses, run_sizes, run_alphas = [], [], []

        epoch_iter = (
            tqdm(range(num_epochs), desc=f"    Run {run+1}/{num_runs}", leave=False)
            if HAS_TQDM else range(num_epochs)
        )

        for epoch in epoch_iter:
            t_epoch_start = time.time()
            epoch_loss = epoch_size = epoch_alpha = 0.0

            for x_batch, idx_batch in loader:
                x_batch = x_batch.to(device)
                alpha_pred = alpha_net(x_batch)

                batch_sizes = []
                for j, idx in enumerate(idx_batch):
                    # USE PRECOMPUTED scores — no predict() call here
                    scores_t = precomputed_scores[idx.item()]
                    size_j = _interval_size(scores_t, alpha_pred[j])
                    batch_sizes.append(size_j)

                batch_sizes = torch.stack(batch_sizes)
                loss = (batch_sizes + lambda_reg * alpha_pred).mean()

                optimizer.zero_grad()
                loss.backward()
                optimizer.step()

                epoch_loss  += loss.item()
                epoch_size  += batch_sizes.mean().item()
                epoch_alpha += alpha_pred.mean().item()

            n_batches = len(loader)
            run_losses.append(epoch_loss  / n_batches)
            run_sizes.append(epoch_size   / n_batches)
            run_alphas.append(epoch_alpha / n_batches)

            epoch_time = time.time() - t_epoch_start

            if epoch % 10 == 0 or epoch == num_epochs - 1:
                epochs_done  = (run * num_epochs) + epoch + 1
                epochs_total = num_runs * num_epochs
                elapsed_train = time.time() - t0_train
                eta = (elapsed_train / epochs_done) * (epochs_total - epochs_done)

                print(
                    f"  λ={lambda_reg} | Run {run+1}/{num_runs} | "
                    f"Epoch {epoch}/{num_epochs} | "
                    f"Loss: {run_losses[-1]:.4f} | "
                    f"Size: {run_sizes[-1]:.4f} | "
                    f"α̃: {run_alphas[-1]:.4f} | "
                    f"⏱ {epoch_time:.2f}s/epoch | "
                    f"ETA: {_fmt_time(eta)}"
                )

        if run_losses[-1] < best_loss:
            best_loss = run_losses[-1]
            best_net  = alpha_net

        history["losses"].append(run_losses)
        history["sizes"].append(run_sizes)
        history["alphas"].append(run_alphas)

        print(f"  ✓ Run {run+1} complete | Final loss: {run_losses[-1]:.4f}")

    train_time = time.time() - t0_train
    print(f"  [Step 4/9] Training done in {_fmt_time(train_time)}")

    alpha_net = best_net
    alpha_net.eval()

    # =========================================================
    # 5. Compute conformal intervals on TEST set
    # =========================================================
    print(f"  [Step 5/9] Computing conformal intervals...")

    calib_preds = base_model.predict(X_calib).ravel()
    scores_calib = np.abs(calib_preds - y_calib)
    sum_scores   = scores_calib.sum()

    with torch.no_grad():
        feat_test = torch.tensor([sum_scores], dtype=torch.float32).to(device)
        alpha_val = alpha_net(feat_test).item()

    denom = alpha_val * (n_calib + 1) - 1
    if denom <= 0:
        q = np.quantile(scores_calib, 1 - alpha)
        half_width = q
        print(f"  [Warning] α̃ too small (denom={denom:.4f}); fallback q={q:.4f}")
    else:
        half_width = sum_scores / denom

    y_pred_test = base_model.predict(Xte).ravel()
    ymin = y_pred_test - half_width
    ymax = y_pred_test + half_width

    # =========================================================
    # 6. Metrics
    # =========================================================
    is_covered = ((yte >= ymin) & (yte <= ymax)).astype(int)
    coverage   = is_covered.mean()
    avg_width  = np.mean(ymax - ymin)
    rmse       = np.sqrt(mean_squared_error(yte, y_pred_test))

    total_time = time.time() - t_start_total

    print(f"\n{'='*55}")
    print(f"  ALPHANET CONFORMAL ({model_name})")
    print(f"{'='*55}")
    print(f"  Learned α̃     : {alpha_val:.4f}")
    print(f"  Half-width (r) : {half_width:.4f}")
    print(f"  Coverage       : {coverage*100:.3f}%")
    print(f"  Avg Width      : {avg_width:.4f}")
    print(f"  RMSE           : {rmse:.4f}")
    print(f"  Total time     : {_fmt_time(total_time)}")
    print(f"    ├─ Precompute: {_fmt_time(elapsed_precompute)}")
    print(f"    └─ Training  : {_fmt_time(train_time)}")
    print(f"{'='*55}")

    # =========================================================
    # 7. Summary & Values
    # =========================================================
    summary_df = pd.DataFrame([{
        "Strategy":       "AlphaNet Conformal",
        "Coverage":       coverage,
        "Width":          avg_width,
        "RMSE":           rmse,
        "Alpha_nominal":  alpha,
        "Alpha_learned":  alpha_val,
        "Lambda_reg":     lambda_reg,
        "Total_time_sec": round(total_time, 2),
    }])

    values_df = pd.DataFrame({
        "sample_index": np.arange(len(yte)),
        "y_true":       yte,
        "y_pred":       y_pred_test,
        "ymin":         ymin,
        "ymax":         ymax,
        "width":        ymax - ymin,
        "is_covered":   is_covered,
    })

    # =========================================================
    # 8. Plotting (SAVE ONLY — NO SHOW)
    # =========================================================
    print(f"  [Step 8/9] Generating plots...")
    idx_arr = np.arange(len(yte))

    # --- Prediction-interval plot ---
    fig_pi, ax_pi = plt.subplots(figsize=(10, 4))
    ax_pi.scatter(idx_arr, yte, color="blue", s=10, alpha=0.7, label="True")
    ax_pi.fill_between(idx_arr, ymin, ymax, color="gray", alpha=0.5,
                       label=f"AlphaNet Interval (α̃={alpha_val:.3f})")
    ax_pi.plot(idx_arr, y_pred_test, color="red", lw=1, label="Predicted mean")
    ax_pi.set_title(f"AlphaNet Conformal ({model_name})")
    ax_pi.set_xlabel("Sample Number")
    ax_pi.set_ylabel("Y_Label")
    ax_pi.legend(loc="upper left")
    plt.tight_layout()

    buf_pi = io.BytesIO()
    fig_pi.savefig(buf_pi, format="png")
    buf_pi.seek(0)
    plt.close(fig_pi)

    # --- Training-curves plot ---
    arr_losses = np.array(history["losses"])
    arr_sizes  = np.array(history["sizes"])
    arr_alphas = np.array(history["alphas"])
    epochs_arr = np.arange(1, num_epochs + 1)

    fig_tc, axs = plt.subplots(1, 3, figsize=(14, 4))
    for ax, data, ylabel, title in zip(
        axs,
        [arr_losses, arr_sizes, arr_alphas],
        ["Loss", "Mean Interval Size", r"Mean $\tilde{\alpha}$"],
        ["Training Loss", "Interval Size", r"Learned $\tilde{\alpha}$"],
    ):
        m = data.mean(axis=0)
        s = data.std(axis=0)
        ax.plot(epochs_arr, m, color="#0077bb")
        ax.fill_between(epochs_arr, m - s, m + s, color="#0077bb", alpha=0.25)
        ax.set_xlabel("Epoch")
        ax.set_ylabel(ylabel)
        ax.set_title(title)
        ax.grid(True, linewidth=0.5)
    plt.tight_layout()

    buf_tc = io.BytesIO()
    fig_tc.savefig(buf_tc, format="png")
    buf_tc.seek(0)
    plt.close(fig_tc)

    # =========================================================
    # 9. Excel Export (append-safe)
    # =========================================================
    if excel_file_path:
        print(f"  [Step 9/9] Saving to Excel...")
        try:
            wb = load_workbook(excel_file_path)
        except FileNotFoundError:
            from openpyxl import Workbook
            wb = Workbook()
            wb.remove(wb.active)

        def _unique_sheet(wb, name):
            base, i = name, 1
            while name in wb.sheetnames:
                name = f"{base}_{i}"; i += 1
            return name

        # ---- Summary ----
        sn = _unique_sheet(wb, "AlphaNet_TabNet_Summary")
        ws = wb.create_sheet(sn)
        for r, row in enumerate(dataframe_to_rows(summary_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        # ---- PI Plot ----
        img_pi = Image(buf_pi)
        sn = _unique_sheet(wb, "AlphaNet_TabNet_Plot_PI")
        ws = wb.create_sheet(sn)
        ws.add_image(img_pi, "A1")

        # ---- Training Curves Plot ----
        img_tc = Image(buf_tc)
        sn = _unique_sheet(wb, "AlphaNet_TabNet_Plot_Train")
        ws = wb.create_sheet(sn)
        ws.add_image(img_tc, "A1")

        # ---- Values ----
        sn = _unique_sheet(wb, "AlphaNet_TabNet_Values")
        ws = wb.create_sheet(sn)
        for r, row in enumerate(dataframe_to_rows(values_df, index=False, header=True), 1):
            for c, val in enumerate(row, 1):
                ws.cell(row=r, column=c, value=val)

        wb.save(excel_file_path)
        print(f"  [Step 9/9] Saved!")

    print(f"\n  ✅ AlphaNet TabNet complete in {_fmt_time(total_time)}")
    return summary_df

In [74]:
conformal_predictions_AlphaNet_tabnet(
    X_train=X_train,
    y_train=y_train,
    X_test=X_test,
    y_test=y_test,
    best_params=best_params,
    model_name="TabNet",
    excel_file_path="./drive/MyDrive/Data_folder/Conformal_Predictions(NEXCP,AdaptiveCP,mfcs)/TabNet.xlsx",
    alpha=0.05,
)

  [Info] n_calib=548 | alpha_min=0.0118
  [Step 2/9] Training base TabNet model...
epoch 0  | loss: 40277640.0|  0:00:00s
epoch 1  | loss: 39293208.0|  0:00:00s
epoch 2  | loss: 26523136.0|  0:00:00s
epoch 3  | loss: 40403280.0|  0:00:00s
epoch 4  | loss: 40825408.0|  0:00:00s
epoch 5  | loss: 39739024.0|  0:00:00s
epoch 6  | loss: 40623796.0|  0:00:00s
epoch 7  | loss: 32275562.0|  0:00:00s
epoch 8  | loss: 39879136.0|  0:00:00s
epoch 9  | loss: 39754040.0|  0:00:00s
epoch 10 | loss: 39529480.0|  0:00:00s
epoch 11 | loss: 39309416.0|  0:00:00s
epoch 12 | loss: 38591528.0|  0:00:00s
epoch 13 | loss: 37422084.0|  0:00:00s
epoch 14 | loss: 37519048.0|  0:00:00s
epoch 15 | loss: 36663632.0|  0:00:01s
epoch 16 | loss: 37757680.0|  0:00:01s
epoch 17 | loss: 36695816.0|  0:00:01s
epoch 18 | loss: 37143824.0|  0:00:01s
epoch 19 | loss: 29360484.0|  0:00:01s
epoch 20 | loss: 30202736.0|  0:00:01s
epoch 21 | loss: 36320216.0|  0:00:01s
epoch 22 | loss: 35235736.0|  0:00:01s
epoch 23 | loss: 35317648.0|  0:00:01s
epoch 24 | loss: 35269420.0|  0:00:01s
epoch 25 | loss: 34912724.0|  0:00:01s
epoch 26 | loss: 22593308.0|  0:00:01s
epoch 27 | loss: 28145920.0|  0:00:01s
epoch 28 | loss: 33648496.0|  0:00:01s
epoch 29 | loss: 34477384.0|  0:00:01s
epoch 30 | loss: 33309278.0|  0:00:01s
epoch 31 | loss: 32766184.0|  0:00:02s
epoch 32 | loss: 31957668.0|  0:00:02s
epoch 33 | loss: 31473762.0|  0:00:02s
epoch 34 | loss: 25277304.0|  0:00:02s
epoch 35 | loss: 30884640.0|  0:00:02s
epoch 36 | loss: 28472624.0|  0:00:02s
epoch 37 | loss: 30969000.0|  0:00:02s
epoch 38 | loss: 24239498.0|  0:00:02s
epoch 39 | loss: 29634030.0|  0:00:02s
epoch 40 | loss: 22057438.0|  0:00:02s
epoch 41 | loss: 28587164.0|  0:00:02s
epoch 42 | loss: 27450130.0|  0:00:02s
epoch 43 | loss: 27238378.0|  0:00:02s
epoch 44 | loss: 27539508.0|  0:00:02s
epoch 45 | loss: 26166796.0|  0:00:02s
epoch 46 | loss: 25903744.0|  0:00:02s
epoch 47 | loss: 25493812.0|  0:00:02s
epoch 48 | loss: 24000278.0|  0:00:03s
epoch 49 | loss: 19478664.0|  0:00:03s
epoch 50 | loss: 25461704.0|  0:00:03s
epoch 51 | loss: 20133596.0|  0:00:03s
epoch 52 | loss: 24285072.0|  0:00:03s
epoch 53 | loss: 24026668.0|  0:00:03s
epoch 54 | loss: 18181340.0|  0:00:03s
epoch 55 | loss: 22098164.0|  0:00:03s
epoch 56 | loss: 21939782.0|  0:00:03s
epoch 57 | loss: 22132978.0|  0:00:03s
epoch 58 | loss: 20879440.0|  0:00:03s
epoch 59 | loss: 20025892.0|  0:00:03s
epoch 60 | loss: 20515868.0|  0:00:03s
epoch 61 | loss: 19099248.0|  0:00:03s
epoch 62 | loss: 13482014.0|  0:00:03s
epoch 63 | loss: 18852420.0|  0:00:03s
epoch 64 | loss: 18266148.0|  0:00:04s
epoch 65 | loss: 17043358.0|  0:00:04s
epoch 66 | loss: 12786066.0|  0:00:04s
epoch 67 | loss: 16517682.0|  0:00:04s
epoch 68 | loss: 15162817.0|  0:00:04s
epoch 69 | loss: 15582178.0|  0:00:04s
epoch 70 | loss: 11770417.0|  0:00:04s
epoch 71 | loss: 14039747.0|  0:00:04s
epoch 72 | loss: 13534921.0|  0:00:04s
epoch 73 | loss: 9099130.0|  0:00:04s
epoch 74 | loss: 12666752.0|  0:00:04s
epoch 75 | loss: 8895131.0|  0:00:04s
epoch 76 | loss: 11908936.0|  0:00:04s
epoch 77 | loss: 11365812.0|  0:00:04s
epoch 78 | loss: 10892478.0|  0:00:04s
epoch 79 | loss: 9944270.0|  0:00:04s
epoch 80 | loss: 9713497.0|  0:00:05s
epoch 81 | loss: 9578688.0|  0:00:05s
epoch 82 | loss: 6575795.0|  0:00:05s
epoch 83 | loss: 8092216.0|  0:00:05s
epoch 84 | loss: 3159468.25|  0:00:05s
epoch 85 | loss: 6893689.5|  0:00:05s
epoch 86 | loss: 7390317.5|  0:00:05s
epoch 87 | loss: 6950566.0|  0:00:05s
epoch 88 | loss: 6450062.5|  0:00:05s
epoch 89 | loss: 5394081.0|  0:00:05s
epoch 90 | loss: 3694976.75|  0:00:05s
epoch 91 | loss: 4734583.0|  0:00:05s
epoch 92 | loss: 4671195.5|  0:00:05s
epoch 93 | loss: 4239990.5|  0:00:05s
epoch 94 | loss: 4288436.5|  0:00:05s
epoch 95 | loss: 3803134.5|  0:00:05s
epoch 96 | loss: 3443708.75|  0:00:06s
epoch 97 | loss: 1672421.5|  0:00:06s
epoch 98 | loss: 3103808.75|  0:00:06s
epoch 99 | loss: 2781362.5|  0:00:06s
  [Step 2/9] Done in 6s
  [Step 3/9] Precomputing 548 LOO score vectors...

    LOO precompute:   0%|          | 0/548 [00:00<?, ?it/s]

  [Step 3/9] Done in 15s
  [Step 4/9] Training AlphaNet: 4 runs × 50 epochs

    Run 1/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 1/4 | Epoch 0/50 | Loss: 159054.6606 | Size: 159054.4280 | α̃: 0.0118 | ⏱ 0.21s/epoch | ETA: 44s
  λ=20.0 | Run 1/4 | Epoch 10/50 | Loss: 159054.9905 | Size: 159054.7569 | α̃: 0.0118 | ⏱ 0.27s/epoch | ETA: 37s
  λ=20.0 | Run 1/4 | Epoch 20/50 | Loss: 159036.3759 | Size: 159036.1398 | α̃: 0.0118 | ⏱ 0.27s/epoch | ETA: 40s
  λ=20.0 | Run 1/4 | Epoch 30/50 | Loss: 159054.8845 | Size: 159054.6458 | α̃: 0.0118 | ⏱ 0.18s/epoch | ETA: 36s
  λ=20.0 | Run 1/4 | Epoch 40/50 | Loss: 159054.3715 | Size: 159054.1328 | α̃: 0.0118 | ⏱ 0.18s/epoch | ETA: 33s
  λ=20.0 | Run 1/4 | Epoch 49/50 | Loss: 159028.2023 | Size: 159027.9688 | α̃: 0.0118 | ⏱ 0.19s/epoch | ETA: 30s
  ✓ Run 1 complete | Final loss: 159028.2023

    Run 2/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 2/4 | Epoch 0/50 | Loss: 1612.8655 | Size: 1592.8655 | α̃: 1.0000 | ⏱ 0.19s/epoch | ETA: 30s
  λ=20.0 | Run 2/4 | Epoch 10/50 | Loss: 1612.8957 | Size: 1592.8957 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 28s
  λ=20.0 | Run 2/4 | Epoch 20/50 | Loss: 1612.8274 | Size: 1592.8274 | α̃: 1.0000 | ⏱ 0.19s/epoch | ETA: 26s
  λ=20.0 | Run 2/4 | Epoch 30/50 | Loss: 1612.9157 | Size: 1592.9157 | α̃: 1.0000 | ⏱ 0.23s/epoch | ETA: 24s
  λ=20.0 | Run 2/4 | Epoch 40/50 | Loss: 1612.9125 | Size: 1592.9125 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 22s
  λ=20.0 | Run 2/4 | Epoch 49/50 | Loss: 1612.9173 | Size: 1592.9173 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 20s
  ✓ Run 2 complete | Final loss: 1612.9173

    Run 3/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 3/4 | Epoch 0/50 | Loss: 1612.9164 | Size: 1592.9164 | α̃: 1.0000 | ⏱ 0.19s/epoch | ETA: 20s
  λ=20.0 | Run 3/4 | Epoch 10/50 | Loss: 1612.9308 | Size: 1592.9308 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 18s
  λ=20.0 | Run 3/4 | Epoch 20/50 | Loss: 1612.8917 | Size: 1592.8917 | α̃: 1.0000 | ⏱ 0.20s/epoch | ETA: 16s
  λ=20.0 | Run 3/4 | Epoch 30/50 | Loss: 1612.9223 | Size: 1592.9223 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 14s
  λ=20.0 | Run 3/4 | Epoch 40/50 | Loss: 1612.7784 | Size: 1592.7784 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 12s
  λ=20.0 | Run 3/4 | Epoch 49/50 | Loss: 1612.8924 | Size: 1592.8924 | α̃: 1.0000 | ⏱ 0.24s/epoch | ETA: 10s
  ✓ Run 3 complete | Final loss: 1612.8924

    Run 4/4:   0%|          | 0/50 [00:00<?, ?it/s]

  λ=20.0 | Run 4/4 | Epoch 0/50 | Loss: 1612.9154 | Size: 1592.9154 | α̃: 1.0000 | ⏱ 0.25s/epoch | ETA: 10s
  λ=20.0 | Run 4/4 | Epoch 10/50 | Loss: 1612.8628 | Size: 1592.8628 | α̃: 1.0000 | ⏱ 0.20s/epoch | ETA: 8s
  λ=20.0 | Run 4/4 | Epoch 20/50 | Loss: 1612.9107 | Size: 1592.9107 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 6s
  λ=20.0 | Run 4/4 | Epoch 30/50 | Loss: 1612.9198 | Size: 1592.9198 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 4s
  λ=20.0 | Run 4/4 | Epoch 40/50 | Loss: 1612.9165 | Size: 1592.9165 | α̃: 1.0000 | ⏱ 0.18s/epoch | ETA: 2s
  λ=20.0 | Run 4/4 | Epoch 49/50 | Loss: 1612.8765 | Size: 1592.8765 | α̃: 1.0000 | ⏱ 0.19s/epoch | ETA: 0s
  ✓ Run 4 complete | Final loss: 1612.8765
  [Step 4/9] Training done in 40s
  [Step 5/9] Computing conformal intervals...

=======================================================
  ALPHANET CONFORMAL (TabNet)
=======================================================
  Learned α̃     : 1.0000
  Half-width (r) : 796.4459
  Coverage       : 92.055%
  Avg Width      : 1592.8917
  RMSE           : 724.7133
  Total time     : 1.0min
    ├─ Precompute: 15s
    └─ Training  : 40s
=======================================================
  [Step 8/9] Generating plots...
  [Step 9/9] Saving to Excel...
  [Step 9/9] Saved!

  ✅ AlphaNet TabNet complete in 1.0min

,Strategy,Coverage,Width,RMSE,Alpha_nominal,Alpha_learned,Lambda_reg,Total_time_sec
0,AlphaNet Conformal,0.920548,1592.891724,724.71332,0.05,1.0,20.0,61.04